using System;

public enum ApolloVoiceErr
{
    APOLLO_VOICE_CDNV_CREATE = 400,
    APOLLO_VOICE_CDNV_NULL = 0x191,
    APOLLO_VOICE_CDNV_QUIT = 0x192,
    APOLLO_VOICE_CREATE_ERR = 5,
    APOLLO_VOICE_IN_ROOM = 6,
    APOLLO_VOICE_JOIN_FAIL = 0x35,
    APOLLO_VOICE_JOIN_NOTIN = 0x34,
    APOLLO_VOICE_JOIN_SUCC = 0x33,
    APOLLO_VOICE_JOIN_TIMEOUT = 50,
    APOLLO_VOICE_JOIN_URL = 0x36,
    APOLLO_VOICE_NET_TIMEOUT = 0x79,
    APOLLO_VOICE_NONE = 1,
    APOLLO_VOICE_PERMISSION_MIC = 200,
    APOLLO_VOICE_STATE_ERR = 4,
    APOLLO_VOICE_SUCC = 0,
    APOLLO_VOICE_TVE_CREATE = 300,
    APOLLO_VOICE_TVE_INIT = 0x12f,
    APOLLO_VOICE_TVE_NULL = 0x12d,
    APOLLO_VOICE_TVE_START = 0x130,
    APOLLO_VOICE_TVE_STOP = 0x12e,
    APOLLO_VOICE_UNKNOWN = 3
}

