using System;

public enum NewbieGuideSkipConditionType
{
    hasAdvancedEquip = 0x17,
    hasBoughtHero = 11,
    hasBoughtItem = 12,
    hasCoinDrawFive = 0x2b,
    hasComplete11Match = 0x2e,
    hasComplete33Guide = 0x21,
    hasCompleteBaseGuide = 0x18,
    hasCompleteCoronaGuide = 0x33,
    hasCompleteDungeon = 1,
    hasCompleteEquipping = 3,
    hasCompleteFirst55Warm = 0x31,
    hasCompleteHeroAdv = 5,
    hasCompleteHeroStar = 8,
    hasCompleteHeroUp = 0x25,
    hasCompleteHuman33Match = 0x20,
    hasCompleteHumanAi33 = 40,
    hasCompleteHumanAi33Match = 0x1f,
    hasCompleteLottery = 0x22,
    hasCompleteNewbieArchive = 30,
    hasCompleteNewbieGuide = 2,
    hasCompleteTrainLevel33 = 0x2f,
    hasCompleteTrainLevel55 = 0x2d,
    hasCompleteWeakNewbieArchive = 0x2c,
    hasDiamondDraw = 0x30,
    hasEnoughSymbolOf = 0x2a,
    hasEnteredBurning = 0x12,
    hasEnteredElitePvE = 0x13,
    hasEnteredGuild = 20,
    hasEnteredMysteryShop = 0x16,
    hasEnteredPvP = 15,
    hasEnteredTournament = 0x26,
    hasEnteredTrial = 0x10,
    hasEnteredZhuangzi = 0x11,
    hasGotChapterReward = 13,
    hasHeroSkillUpgraded = 9,
    hasIncreaseEquip = 0x23,
    hasManufacuredSymbol = 0x29,
    hasMopup = 14,
    hasOverThreeHeroes = 7,
    hasRewardTaskPve = 0x24,
    hasRewardTaskPvp = 4,
    hasSummonedHero = 6,
    hasUsedSymbol = 0x15,
    Invalid = 0
}

