using System;

public enum NewbieGuideTriggerTimeType
{
    battleFin = 4,
    enterBattle = 2,
    enterBattleHeroSel = 8,
    enterHall = 1,
    enterPveEntry = 12,
    enterPvpEntry = 11,
    equipSuccess = 5,
    getSymbolReward = 0x11,
    heroSelectedForBattle = 0x10,
    lotterySuccess = 7,
    newbiePvPDragonBuff = 13,
    newbiePvPTalent = 10,
    newbieTalent = 9,
    newbieTalentSecondTime = 20,
    onBattleStart = 0x2b,
    onBuyFirstEquip = 30,
    onClick33Team = 0x24,
    onClick3v3AI = 0x22,
    onClick55Team = 0x23,
    onClickFireMatch = 0x29,
    onClickGloryPoints = 0x2e,
    onEnterCustomRecommendEquip = 40,
    onEnterExploreForm = 0x18,
    onEnterMishu = 0x2d,
    onEnterSymbolForm = 0x19,
    onEnterTaskForm = 0x17,
    onEntryTrainLevelEntry = 0x25,
    onEuipShopGuide = 0x26,
    onHasEnoughMoneyButEquip = 0x1f,
    onHostFirstDead = 0x2c,
    onJungleEquipGuide = 0x21,
    onMiniMapSignGuide = 0x20,
    onOpenMatchingConfirmBox = 0x27,
    onSetLockOrFreeTargetType = 0x2a,
    onTalentLevelChange = 0x16,
    preNewbieGuideComplete = 3,
    preNewBieWeakGuideComleteAll = 0x1b,
    preNewBieWeakGuideStepComplete = 0x1a,
    pvpFin = 14,
    PvPShareFin = 0x1c,
    PvPShowKDA = 0x1d,
    shoppingSuccess = 6,
    timeForNewbieSwitchingCaptain = 0x15,
    timeForOpSetting = 15
}

