namespace ResData
{
    using System;

    public enum RES_ACHIEVE_DONE_TYPE
    {
        RES_ACHIEVE_DONE_GET_GOLD,
        RES_ACHIEVE_DONE_GET_SYMBAL_5,
        RES_ACHIEVE_DONE_GET_HERO,
        RES_ACHIEVE_DONE_GET_SKIN,
        RES_ACHIEVE_DONE_GET_5_PROFICIENCY_HERO,
        RES_ACHIEVE_DONE_KILL_HERO,
        RES_ACHIEVE_DONE_KILL_SOLDIER,
        RES_ACHIEVE_DONE_DESTROY_TOWER,
        RES_ACHIEVE_DONE_DESTROY_CRYSTAL,
        RES_ACHIEVE_DONE_KILL_MONSTER,
        RES_ACHIEVE_DONE_TRIPLE_KILL,
        RES_ACHIEVE_DONE_GAME_HURT,
        RES_ACHIEVE_DONE_TOTAL_HURT,
        RES_ACHIEVE_DONE_GAME_HURT_HERO,
        RES_ACHIEVE_DONE_TOTAL_HURT_HERO,
        RES_ACHIEVE_DONE_GAME_BEHURT,
        RES_ACHIEVE_DONE_TOTAL_BEHURT,
        RES_ACHIEVE_DONE_TOTAL_WIN,
        RES_ACHIEVE_DONE_CONTINUE_WIN,
        RES_ACHIEVE_DONE_WIN_MVP,
        RES_ACHIEVE_DONE_LOSS_MVP,
        RES_ACHIEVE_DONE_PASS_STAGE,
        RES_ACHIEVE_DONE_BURNING,
        RES_ACHIEVE_DONE_ARENA,
        RES_ACHIEVE_DONE_GAME_FRIEND_CNT,
        RES_ACHIEVE_DONE_PLAY_WITH_FRIEND,
        RES_ACHIEVE_DONE_WIN_WITH_FRIEND,
        RES_ACHIEVE_DONE_GUILD_RANK_POINT,
        RES_ACHIEVE_DONE_GUILD_RANK_POINT_LADDER,
        RES_ACHIEVE_DONE_KILL_DRAGON,
        RES_ACHIEVE_DONE_GET_SYMBAL_4,
        RES_ACHIEVE_DONE_GET_SYMBAL_3,
        RES_ACHIEVE_DONE_GET_4_PROFICIENCY_HERO,
        RES_ACHIEVE_DONE_GET_3_PROFICIENCY_HERO,
        RES_ACHIEVE_DONE_DOUBLE_RANK,
        RES_ACHIEVE_DONE_RANK_3_WIN,
        RES_ACHIEVE_DONE_RANK_4_WIN,
        RES_ACHIEVE_DONE_RANK_5_WIN,
        RES_ACHIEVE_DONE_RANK_10_WIN,
        RES_ACHIEVE_DONE_RANK_15_WIN,
        RES_ACHIEVE_DONE_RANK_20_WIN,
        RES_ACHIEVE_DONE_RANK_GRADE,
        RES_ACHIEVE_DONE_VIP_LEVEL,
        RES_ACHIEVE_DONE_TYPE_MAX
    }
}

