namespace ResData
{
    using System;

    public enum RES_SRV2CLT_GLOBAL_CONF_TYPE
    {
        RES_SRV2CLT_GLOBAL_CONF_TYPE_LOGIN_ACTIVITY_POP_NUM,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_PVPCOIN_DAILYLIMIT,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_TASKCOIN_DAILYLIMIT,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_FRIENDCOIN_DAILYLIMIT,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_SINGLECOIN_NUM,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_PULISH_CREDIT_SCORE_BAN_LADDER,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_ENABLE_IOS_9_REPLAY_KIT,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_IOS_9_REPLAY_KIT_DISABLE_STORAGE_LIMIT,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_IOS_9_REPLAY_KIT_WARNING_STORAGE_LIMIT,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_ENABLE_WIN_TRICK,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_OBSERVE_DELAY,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_LADDER_BP_GRADE_LIMIT,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_RECORDER_KINGTIME_IOS_ENABLE,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_RECORDER_KINGTIME_ANDROID_ENABLE,
        RES_SRV2CLT_GLOBAL_CONF_TYPE_MAX
    }
}

