namespace ResData
{
    using System;

    public enum RES_RANDOM_REWARD_INIT_HERO_LIMIT
    {
        RES_RANDOM_REWARD_INIT_HERO_LIMIT_LIANPO = 0x69,
        RES_RANDOM_REWARD_INIT_HERO_LIMIT_NULL = 0,
        RES_RANDOM_REWARD_INIT_HERO_LIMIT_XIAOQIAO = 0x6a,
        RES_RANDOM_REWARD_INIT_HERO_LIMIT_ZHAOYUN = 0x6b
    }
}

