namespace ResData
{
    using System;

    public enum RES_REWARDS_TYPE
    {
        RES_REWARDS_TYPE_AP = 12,
        RES_REWARDS_TYPE_ARENACOIN = 8,
        RES_REWARDS_TYPE_BURNINGCOIN = 7,
        RES_REWARDS_TYPE_COUPONS = 4,
        RES_REWARDS_TYPE_DIAMOND = 0x10,
        RES_REWARDS_TYPE_EQUIP = 5,
        RES_REWARDS_TYPE_EXP = 3,
        RES_REWARDS_TYPE_HEADIMAGE = 20,
        RES_REWARDS_TYPE_HEROPOOLEXP = 11,
        RES_REWARDS_TYPE_HONOUR = 9,
        RES_REWARDS_TYPE_HUOYUEDU = 0x11,
        RES_REWARDS_TYPE_ITEM = 2,
        RES_REWARDS_TYPE_MATCHPOINT_GUILD = 0x13,
        RES_REWARDS_TYPE_MATCHPOINT_PERSON = 0x12,
        RES_REWARDS_TYPE_MAX = 0x15,
        RES_REWARDS_TYPE_NULL = 0,
        RES_REWARDS_TYPE_PVPEXP = 15,
        RES_REWARDS_TYPE_SKIN = 13,
        RES_REWARDS_TYPE_SKINCOIN = 10,
        RES_REWARDS_TYPE_SYMBOL = 6,
        RES_REWARDS_TYPE_SYMBOLCOIN = 14
    }
}

