namespace ResData
{
    using System;

    public enum RES_PVP_ACHIEVEMENT_CONTI_KILL_TYPE
    {
        RES_STAR_CONDITION_ACHIEVEMENT_DOMINATE_BATTLE = 12,
        RES_STAR_CONDITION_ACHIEVEMENT_LEGENDARY = 13,
        RES_STAR_CONDITION_ACHIEVEMENT_MONSTER_KILL = 11,
        RES_STAR_CONDITION_ACHIEVEMENT_ODYSSEY = 15,
        RES_STAR_CONDITION_ACHIEVEMENT_TOTAL_ANNIHILAT = 14
    }
}

