namespace ResData
{
    using System;

    public enum RES_WARM_BATTLE_STAGE
    {
        RES_WARM_BATTLE_STAGE_NUM = 10,
        RES_WARM_BATTLE_STAGE_OF_BAIYIN = 5,
        RES_WARM_BATTLE_STAGE_OF_BOJING = 7,
        RES_WARM_BATTLE_STAGE_OF_HIGH = 3,
        RES_WARM_BATTLE_STAGE_OF_HUANGJIN = 6,
        RES_WARM_BATTLE_STAGE_OF_LOW = 1,
        RES_WARM_BATTLE_STAGE_OF_MID = 2,
        RES_WARM_BATTLE_STAGE_OF_QINGTONG = 4,
        RES_WARM_BATTLE_STAGE_OF_WANGZHE = 9,
        RES_WARM_BATTLE_STAGE_OF_ZUANSHI = 8
    }
}

