namespace ResData
{
    using System;

    public enum RES_PVP_ACHIEVEMENT_MULTI_KILL_TYPE
    {
        RES_STAR_CONDITION_ACHIEVEMENT_ASSIST,
        RES_STAR_CONDITION_ACHIEVEMENT_FIRST_KILL,
        RES_STAR_CONDITION_ACHIEVEMENT_KILL,
        RES_STAR_CONDITION_ACHIEVEMENT_DOUBLE_KILL,
        RES_STAR_CONDITION_ACHIEVEMENT_TRIPLE_KILL,
        RES_STAR_CONDITION_ACHIEVEMENT_QUATARY_KILL,
        RES_STAR_CONDITION_ACHIEVEMENT_PENTA_KILL
    }
}

