namespace ResData
{
    using System;

    public enum RES_STAR_CONDITION_EXT_TYPE
    {
        RES_STAR_CONDITION_CLEAR_STAT = 1,
        RES_STAR_CONDITION_CLEARANCE_APPOINT_TIME = 14,
        RES_STAR_CONDITION_CLEARANCE_RESTRICT_CAREER_TYPE = 9,
        RES_STAR_CONDITION_CLEARANCE_TEAM_COUNT = 10,
        RES_STAR_CONDITION_CLEARANCE_TIME_LIMIT = 11,
        RES_STAR_CONDITION_DATA_STAT = 7,
        RES_STAR_CONDITION_DATA_STAT_TIMER = 0x10,
        RES_STAR_CONDITION_DEATH_STAT = 3,
        RES_STAR_CONDITION_HEALTH_STAT = 2,
        RES_STAR_CONDITION_MONSTER_TRIGGER = 15,
        RES_STAR_CONDITION_PVP_ACHIEVEMENT = 13,
        RES_STAR_CONDITION_PVP_KILL_ALL_ENEMY = 6,
        RES_STAR_CONDITION_RESTRICT_HERO = 4,
        RES_STAR_CONDITION_TEAM_EXTINCTION = 12,
        RES_STAR_CONDITION_TIME_LIMIT_STAT = 8
    }
}

