namespace ResData
{
    using System;

    public enum RES_PROP_VALFUNC_TYPE
    {
        RES_PROP_VALFUNC_EXP = 1,
        RES_PROP_VALFUNC_GUILD_NAMECHANGE = 7,
        RES_PROP_VALFUNC_HERO_EXPERIENCE = 4,
        RES_PROP_VALFUNC_MONTH_CARD = 8,
        RES_PROP_VALFUNC_MULTIPLE_COIN = 3,
        RES_PROP_VALFUNC_MULTIPLE_EXP = 2,
        RES_PROP_VALFUNC_PLAYER_NAMECHANGE = 6,
        RES_PROP_VALFUNC_SKIN_EXPERIENCE = 5,
        RES_PROP_VALFUNC_WEEK_CARD = 9
    }
}

