namespace ResData
{
    using System;

    public enum RES_SHOPBUY_TYPE
    {
        RES_BUYTYPE_APBUY = 4,
        RES_BUYTYPE_ARENACHALLENGECNT = 9,
        RES_BUYTYPE_COINDRAW = 1,
        RES_BUYTYPE_DRAWHERO = 2,
        RES_BUYTYPE_DRAWSKIN = 3,
        RES_BUYTYPE_DRAWSYMBOLCOMMON = 10,
        RES_BUYTYPE_DRAWSYMBOLSENIOR = 11,
        RES_BUYTYPE_ENTERTAINMENTRANDHERO = 13,
        RES_BUYTYPE_LVLCHALLENGE = 6,
        RES_BUYTYPE_MAX = 14,
        RES_BUYTYPE_OPENBOXBYCOUPONS = 8,
        RES_BUYTYPE_SPBUY = 5,
        RES_BUYTYPE_SYMBOLPAGE = 7,
        RES_BUYTYPE_SYMBOLPAGEPOS = 12
    }
}

