namespace ResData
{
    using System;

    public enum RES_PERREQUISITE_PVPKILLCNT_TYPE
    {
        RES_PERREQUISITE_PVPKILLCNT_TYPE,
        RES_PERREQUISITE_PVPKILLCNT_COMMON,
        RES_PERREQUISITE_PVPKILLCNT_KA,
        RES_PERREQUISITE_PVPKILLCNT_KILLTOWER,
        RES_PERREQUISITE_PVPKILLCNT_KILLMONSTER,
        RES_PERREQUISITE_PVPKILLCNT_KILLDRANGON,
        RES_PERREQUISITE_PVPKILLCNT_MAX
    }
}

