namespace ResData
{
    using System;

    public enum RES_SHOPBUY_COINTYPE
    {
        RES_SHOPBUY_TYPE_ARENACOIN = 6,
        RES_SHOPBUY_TYPE_BURNINGCOIN = 5,
        RES_SHOPBUY_TYPE_COUPONS = 2,
        RES_SHOPBUY_TYPE_DIAMOND = 10,
        RES_SHOPBUY_TYPE_ENCHANTPT = 3,
        RES_SHOPBUY_TYPE_GUILDCOIN = 8,
        RES_SHOPBUY_TYPE_MAX = 13,
        RES_SHOPBUY_TYPE_MIXPAY = 11,
        RES_SHOPBUY_TYPE_NULL = 0,
        RES_SHOPBUY_TYPE_PVPCOIN = 4,
        RES_SHOPBUY_TYPE_SCORE = 12,
        RES_SHOPBUY_TYPE_SKINCOIN = 7,
        RES_SHOPBUY_TYPE_SYMBOLCOIN = 9
    }
}

