namespace Assets.Scripts.GameSystem
{
    using System;

    public enum enBattleFormWidget
    {
        Bigmap = 0x43,
        BigMapEffectRoot = 0x42,
        Button_Attack = 7,
        Button_ComAtkSelectHero = 0x44,
        Button_ComAtkSelectSoldier = 0x39,
        Button_EquipShop = 0x3a,
        Button_OpenBigMap = 0x47,
        Button_Pause = 0x27,
        Button_Recover = 11,
        Button_Resume = 40,
        Button_Signal_1 = 12,
        Button_Signal_2 = 13,
        Button_Signal_3 = 14,
        Button_Signal_4 = 15,
        Button_Skill_1 = 8,
        Button_Skill_2 = 9,
        Button_Skill_3 = 10,
        Button_Skill_6 = 0x37,
        Button_Skill_Ornament = 0x4d,
        Button_Talent = 0x1a,
        Button_Voice = 0x36,
        CancelSkill = 0x1f,
        Container_BigMapPointer_Alies = 0x3e,
        Container_BigMapPointer_Dragon = 60,
        Container_BigMapPointer_Enemy = 0x40,
        Container_BigMapPointer_Hero = 0x3f,
        Container_BigMapPointer_Organ = 0x3d,
        Container_BigMapPointer_Signal = 0x41,
        Container_MinimapPointer_Alies = 4,
        Container_MinimapPointer_Enemy = 5,
        Container_MinimapPointer_Hero = 3,
        Container_MinimapPointer_Organ = 0x1c,
        Container_MinimapPointer_Signal = 0x21,
        Container_TextHud = 0x18,
        Effect_QuicklyBuy_0 = 50,
        Effect_QuicklyBuy_1 = 0x33,
        Effect_QuicklyBuy_Get_0 = 0x34,
        Effect_QuicklyBuy_Get_1 = 0x35,
        FpsAndLag = 0x20,
        Input_Mask = 0x29,
        JoyStick = 0x26,
        Joystick_Camera = 0x49,
        List_SignalTips = 0x2b,
        MenuBtn = 0x45,
        Minimap = 6,
        MiniMapEffectRoot = 0x22,
        None = -1,
        Panel_AllHeroInfo = 0x48,
        Panel_EnemyHeroHud = 0x15,
        Panel_EnemySoliderHud = 20,
        Panel_Equip = 0x2d,
        Panel_QuicklyBuyEquip = 0x3b,
        Panel_SelfHeroHud = 0x17,
        Panel_SelfSoliderHud = 0x16,
        Panel_Surrender = 0x31,
        Recommend_Equip_0 = 0x2f,
        Recommend_Equip_1 = 0x30,
        ReplayKit = 0x4b,
        Reserve = 0,
        SkillButton4FixedPosition = 70,
        SkillJoystick = 0x19,
        SkillJoystick_SelectTarget = 0x4c,
        Text_GoldCoinInBattle = 0x2e,
        Text_Skill_1_CD = 0x10,
        Text_Skill_2_CD = 0x11,
        Text_Skill_3_CD = 0x12,
        Text_Skill_4_CD = 0x13,
        Text_Skill_5_CD = 0x1b,
        Text_Skill_6_CD = 0x38,
        Text_Skill_Ornament_CD = 0x4e,
        TouchPad_Camera = 0x4a,
        WifiIcon = 0x23,
        WifiInfo = 0x25,
        WifiPing = 0x24,
        WifiTimer = 0x2c
    }
}

