namespace Assets.Scripts.GameSystem
{
    using System;

    public enum enNewbieAchieve
    {
        Androiod_Diamond_0 = 20,
        Androiod_Diamond_1 = 0x15,
        Androiod_Diamond_10 = 30,
        Androiod_Diamond_11 = 0x1f,
        Androiod_Diamond_12 = 0x20,
        Androiod_Diamond_13 = 0x21,
        Androiod_Diamond_14 = 0x22,
        Androiod_Diamond_15 = 0x23,
        Androiod_Diamond_2 = 0x16,
        Androiod_Diamond_3 = 0x17,
        Androiod_Diamond_4 = 0x18,
        Androiod_Diamond_5 = 0x19,
        Androiod_Diamond_6 = 0x1a,
        Androiod_Diamond_7 = 0x1b,
        Androiod_Diamond_8 = 0x1c,
        Androiod_Diamond_9 = 0x1d,
        BigMapSignGuideFirstTime = 0x4c,
        BigMapSignGuideSecondTime = 0x4d,
        cameraMoveGuide1 = 0x40,
        cameraMoveGuide2 = 0x41,
        cameraMoveGuide3 = 0x42,
        clickEnterTain55YesAndComplete = 0x3f,
        clickEnterTrain55No = 0x3e,
        clickEnterTrain55Yes = 0x3d,
        COM_ACNT_CLIENT_BITS_TYPE_1_1_1_ENTER = 12,
        COM_ACNT_CLIENT_BITS_TYPE_1_1_1_LOADOK = 13,
        COM_ACNT_CLIENT_BITS_TYPE_ARENA_ENTER = 15,
        COM_ACNT_CLIENT_BITS_TYPE_BURNING_ENTER = 0x10,
        COM_ACNT_CLIENT_BITS_TYPE_COMBAT_3V3_ENTER = 9,
        COM_ACNT_CLIENT_BITS_TYPE_COMBAT_3V3_LOADOK = 10,
        COM_ACNT_CLIENT_BITS_TYPE_DESTORY_ARROWTOWER = 1,
        COM_ACNT_CLIENT_BITS_TYPE_DESTORY_BASETOWER = 2,
        COM_ACNT_CLIENT_BITS_TYPE_DESTORY_MONSTERHOME = 3,
        COM_ACNT_CLIENT_BITS_TYPE_GET_HERO = 7,
        COM_ACNT_CLIENT_BITS_TYPE_KILL_HERO = 8,
        COM_ACNT_CLIENT_BITS_TYPE_KILL_LITTLEDRAGON = 4,
        COM_ACNT_CLIENT_BITS_TYPE_KILL_SOLDIER = 0,
        COM_ACNT_CLIENT_BITS_TYPE_LEARN_TALENT = 5,
        COM_ACNT_CLIENT_BITS_TYPE_OLDPLAYERGUILDED = 0x11,
        COM_ACNT_CLIENT_BITS_TYPE_SINGLE_3V3_LOADOK = 11,
        COM_ACNT_CLIENT_BITS_TYPE_SYMBOL_ENTER = 14,
        COM_ACNT_CLIENT_BITS_TYPE_UPGRADE_EQUIP = 6,
        CompleteLunPan = 0x65,
        CompleteLunPanInV8AndLater = 0x76,
        GuideEnterHall = 0x54,
        INVALID = 0x77,
        IOS_Diamond_0 = 40,
        IOS_Diamond_1 = 0x29,
        IOS_Diamond_10 = 50,
        IOS_Diamond_11 = 0x33,
        IOS_Diamond_12 = 0x34,
        IOS_Diamond_13 = 0x35,
        IOS_Diamond_14 = 0x36,
        IOS_Diamond_15 = 0x37,
        IOS_Diamond_2 = 0x2a,
        IOS_Diamond_3 = 0x2b,
        IOS_Diamond_4 = 0x2c,
        IOS_Diamond_5 = 0x2d,
        IOS_Diamond_6 = 0x2e,
        IOS_Diamond_7 = 0x2f,
        IOS_Diamond_8 = 0x30,
        IOS_Diamond_9 = 0x31,
        MapSignGuide = 0x5e,
        OldPlayerGrow = 0x48,
        OldPlayerSelectMode = 0x4b,
        SelectFreeTargetMode = 0x4f,
        SelectLockTargetMode = 0x51
    }
}

