namespace Assets.Scripts.GameSystem
{
    using System;

    public enum SettingFormWidget
    {
        AutoOpenNetAcc = 0x24,
        BasicBattleOnlyWidgets = 0x35,
        BasicExitBattle = 0,
        BasicLgoinArea = 10,
        BasicLogin = 9,
        BasicLoobyOnlyWidgets = 0x36,
        BasicModelLod = 6,
        BasicMusicBar = 4,
        BasicParticleLod = 7,
        BasicSetting = 1,
        BasicSkillTipBar = 8,
        BasicSoundBar = 5,
        BattleBg = 0x38,
        CameraSensitivity = 0x30,
        CommonAttackType1 = 0x18,
        CommonAttackType2 = 0x19,
        ContractBtn = 0x34,
        FpsBar = 0x16,
        HDBar = 0x31,
        HelpMeBtn = 0x11,
        InputChat = 0x26,
        KingTimeBar = 0x39,
        LobbyBg = 0x37,
        MoveCameraSlider = 0x2a,
        MusicLevel = 0x1c,
        NetAccDetailDelay = 0x1f,
        NetAccDetailServer = 0x20,
        NetAccDetailState = 0x22,
        NetAccDetailType = 0x21,
        None = -1,
        OpCameraHeight = 0x10,
        OpenNetAcc = 0x23,
        OpLunPanCast = 12,
        OpLunPanSensi = 13,
        OpPickMinHp = 15,
        OpPickNearest = 14,
        OpSetting = 2,
        OpSmartCast = 11,
        PanelAdvSet = 0x13,
        PrivacyPolicyBtn = 50,
        RecorderBar = 0x3a,
        ReplayHelpBtn = 0x3b,
        ReplayKitEnableDesc = 0x2e,
        ReplayKitEnableSlider = 0x2c,
        ReplayKitSetting = 0x2b,
        RepllayKitModeDesc = 0x2f,
        RepllayKitModeSlider = 0x2d,
        RightJoyStickBtnLoc = 20,
        RightJoyStickFingerLoc = 0x15,
        SkillCancleType1 = 0x27,
        SkillCancleType2 = 40,
        SoundEffectLevel = 0x1d,
        Surrender = 0x1a,
        TabListBattle = 0x12,
        TabListLobby = 3,
        TabNetAcc = 0x25,
        TermOfserviceBtn = 0x33,
        VibrateSilider = 0x29,
        VoiceButton = 0x17,
        VoiceEffectLevel = 30,
        VoiceSettingMeun = 0x1b
    }
}

