namespace CSProtocol
{
    using System;

    public enum COM_MAILOPTRESULT_TYPE
    {
        COM_MAILOPTRESULT_GETHEARTLIMIT = 8,
        COM_MAILOPTRESULT_LISTGETING = 6,
        COM_MAILOPTRESULT_MAILCONTENT = 10,
        COM_MAILOPTRESULT_MAILTITLE = 9,
        COM_MAILOPTRESULT_NEWMAIL = 3,
        COM_MAILOPTRESULT_PACKAGECLEAN = 5,
        COM_MAILOPTRESULT_PACKAGEFULL = 4,
        COM_MAILOPTRESULT_SAMEVERSION = 7,
        COM_MAILOPTRESULT_SENDFAIL = 2,
        COM_MAILOPTRESULT_SENDSUCCESS = 1
    }
}

