namespace CSProtocol
{
    using System;

    public enum COM_MAILSOURCE_TYPE
    {
        COM_MAILSOURCE_ACHIEVEMENT = 0x10,
        COM_MAILSOURCE_ACTIVITY = 7,
        COM_MAILSOURCE_AREAN = 6,
        COM_MAILSOURCE_CREDITREWARD = 0x19,
        COM_MAILSOURCE_EXPCARD = 0x12,
        COM_MAILSOURCE_FRIENDDONATE = 0x17,
        COM_MAILSOURCE_GAINCHEST = 0x15,
        COM_MAILSOURCE_GAMECENTER = 0x1a,
        COM_MAILSOURCE_GAMEVIP = 13,
        COM_MAILSOURCE_GLOABALREWARD = 2,
        COM_MAILSOURCE_GM = 1,
        COM_MAILSOURCE_GUILD = 3,
        COM_MAILSOURCE_HERO = 15,
        COM_MAILSOURCE_IDIP = 4,
        COM_MAILSOURCE_ITEM = 9,
        COM_MAILSOURCE_LUCKYDRAW = 0x11,
        COM_MAILSOURCE_LUCKYREWARD = 0x18,
        COM_MAILSOURCE_MONTHWEEK = 20,
        COM_MAILSOURCE_PAY = 8,
        COM_MAILSOURCE_PVE = 12,
        COM_MAILSOURCE_PVP = 11,
        COM_MAILSOURCE_RANDDRAW = 0x13,
        COM_MAILSOURCE_RANK = 14,
        COM_MAILSOURCE_REWARDMATCH = 0x16,
        COM_MAILSOURCE_SWEEP = 10,
        COM_MAILSOURCE_TASK = 5
    }
}

