namespace CSProtocol
{
    using System;

    public enum COM_APOLLO_PAY_TYPE
    {
        COM_APOLLO_PAY_CHAT = 0x13,
        COM_APOLLO_PAY_CLRCD = 9,
        COM_APOLLO_PAY_DELETE = 14,
        COM_APOLLO_PAY_DIRECTBUYITEM = 13,
        COM_APOLLO_PAY_IDIPDELETE = 0x19,
        COM_APOLLO_PAY_LUCKYDRAW = 0x12,
        COM_APOLLO_PAY_MATCHTICKET = 0x18,
        COM_APOLLO_PAY_MAX = 0x1a,
        COM_APOLLO_PAY_MONTHFILLIN = 12,
        COM_APOLLO_PAY_PAYCOINBUY = 3,
        COM_APOLLO_PAY_PAYGAMESWEEP = 6,
        COM_APOLLO_PAY_PAYGUILDCRT = 7,
        COM_APOLLO_PAY_PAYGUILDDONATE = 10,
        COM_APOLLO_PAY_PAYGUILDUPD = 0x10,
        COM_APOLLO_PAY_PAYHEROBUY = 5,
        COM_APOLLO_PAY_PAYITEMBUY = 2,
        COM_APOLLO_PAY_PAYMANUALREF = 4,
        COM_APOLLO_PAY_PAYSHOPBUY = 1,
        COM_APOLLO_PAY_PAYSKINBUY = 8,
        COM_APOLLO_PAY_PAYTALENTBUY = 0x11,
        COM_APOLLO_PAY_PRESENTHERO = 0x16,
        COM_APOLLO_PAY_PRESENTSKIN = 0x17,
        COM_APOLLO_PAY_PVE_REVIVE = 15,
        COM_APOLLO_PAY_RANDDRAW = 0x15,
        COM_APOLLO_PAY_SALERECMD_BUY = 20,
        COM_APOLLO_PAY_SPECSALE = 11
    }
}

