namespace CSProtocol
{
    using System;

    public enum COM_TRANSACTION_TCAPLUST_EVNET_TYPE
    {
        COM_TRANSACTION_TCAP_ADDARENA_FIGHTHISTORY = 0x16,
        COM_TRANSACTION_TCAP_ADDFIGHTHISTORYRECORD = 0x27,
        COM_TRANSACTION_TCAP_ADDRANKCURSEASONRECORD = 0x21,
        COM_TRANSACTION_TCAP_ADDRANKPASTSEASONRECORD = 0x22,
        COM_TRANSACTION_TCAP_DELETE_BURNINGENEMY = 0x17,
        COM_TRANSACTION_TCAP_DELETERANKDETAIL = 2,
        COM_TRANSACTION_TCAP_DELETEREGISTER = 0x25,
        COM_TRANSACTION_TCAP_DELGUILDINVITE = 0x11,
        COM_TRANSACTION_TCAP_DELGUILDMEMBER = 11,
        COM_TRANSACTION_TCAP_DELJOINGUILDREQ = 10,
        COM_TRANSACTION_TCAP_GETACNTINFO = 9,
        COM_TRANSACTION_TCAP_GETACNTINFOFROMVISITORSVR = 0x1a,
        COM_TRANSACTION_TCAP_GETARENA_TARGETHERO = 20,
        COM_TRANSACTION_TCAP_GETARENA_TARGETITEM = 0x15,
        COM_TRANSACTION_TCAP_GETGLOBALREWARD = 0x13,
        COM_TRANSACTION_TCAP_GETGUILDID = 15,
        COM_TRANSACTION_TCAP_GETGUILDINVITE = 12,
        COM_TRANSACTION_TCAP_GETGUILDMAIN = 0x10,
        COM_TRANSACTION_TCAP_GETHEROINFOFROMVISITORSVR = 0x1b,
        COM_TRANSACTION_TCAP_GETITEMINFOFROMVISITORSVR = 0x1c,
        COM_TRANSACTION_TCAP_GETONLINEINFO = 4,
        COM_TRANSACTION_TCAP_INSERT_BURNINGENEMY = 0x18,
        COM_TRANSACTION_TCAP_INSERTACNTINFO = 30,
        COM_TRANSACTION_TCAP_INSERTGUILDINVITE = 14,
        COM_TRANSACTION_TCAP_INSERTGUILDMEMBER = 7,
        COM_TRANSACTION_TCAP_INSERTGUILDRECOMMEND = 0x12,
        COM_TRANSACTION_TCAP_INSERTHEROINFO = 0x1f,
        COM_TRANSACTION_TCAP_INSERTITEMINFO = 0x20,
        COM_TRANSACTION_TCAP_INSERTONLINEINFO = 5,
        COM_TRANSACTION_TCAP_INSERTRANKDETAIL = 1,
        COM_TRANSACTION_TCAP_INSERTREGISTER = 0x23,
        COM_TRANSACTION_TCAP_INSERTREGISTERINFO = 0x1d,
        COM_TRANSACTION_TCAP_UPDACNTGUILDINFO = 8,
        COM_TRANSACTION_TCAP_UPDACNTNAME = 0x24,
        COM_TRANSACTION_TCAP_UPDATERANKCLASSID = 3,
        COM_TRANSACTION_TCAP_UPDGUILDINVITETIME = 13,
        COM_TRANSACTION_TCAP_UPDGUILDNAME = 0x26,
        COM_TRANSACTION_TCAP_UPDONLINEINFO = 6,
        COM_TRANSACTION_TCAP_UPDVISITORSVRTRANSFLAG = 0x19
    }
}

