namespace CSProtocol
{
    using System;

    public enum COM_MATCHTEAMERRORCODE_DEF
    {
        COM_MATCHTEAMEERR_BANTIME = 13,
        COM_MATCHTEAMEERR_BEGIN_MATCH = 8,
        COM_MATCHTEAMEERR_BEPUNISHED = 0x11,
        COM_MATCHTEAMEERR_DESTROY = 7,
        COM_MATCHTEAMEERR_DUPJOIN = 0x19,
        COM_MATCHTEAMEERR_FRIEND_BUSY = 5,
        COM_MATCHTEAMEERR_FRIEND_OFFLINE = 4,
        COM_MATCHTEAMEERR_GAMEREADY_ERROR = 10,
        COM_MATCHTEAMEERR_HIGHVERSION = 14,
        COM_MATCHTEAMEERR_INVALID_CREDIT_VALUE = 0x17,
        COM_MATCHTEAMEERR_INVALID_RANKSTATE_OF_REWARD = 0x15,
        COM_MATCHTEAMEERR_INVALID_TIME = 0x16,
        COM_MATCHTEAMEERR_INVALIDPARAM = 2,
        COM_MATCHTEAMEERR_INVITE_DENY = 6,
        COM_MATCHTEAMEERR_LEAVETEAM_FAILED = 11,
        COM_MATCHTEAMEERR_LIMIT_ENTERTAINMENT_FUNC = 0x10,
        COM_MATCHTEAMEERR_LIMIT_PRIVILEGE = 1,
        COM_MATCHTEAMEERR_LIMIT_RANK_FUNC = 12,
        COM_MATCHTEAMEERR_LOWVERSION = 15,
        COM_MATCHTEAMEERR_MEMBER_FULL = 9,
        COM_MATCHTEAMEERR_NOTFOUND_FRIEND = 3,
        COM_MATCHTEAMEERR_OBING = 0x1b,
        COM_MATCHTEAMEERR_OTHERS = 0x18,
        COM_MATCHTEAMEERR_PLAT_CHANNEL_CLOSE = 0x1a,
        COM_MATCHTEAMEERR_RANK_INVALID_GRADEDIFF = 0x12,
        COM_MATCHTEAMEERR_RANK_INVALID_GUILDMEM = 0x13,
        COM_MATCHTEAMEERR_TEAMERLEAVE = 20
    }
}

