namespace CSProtocol
{
    using System;

    public enum COM_TRANSACTION_MSG_EVNET_TYPE
    {
        COM_TRANSACTION_MSG_DUPKICK = 0x13,
        COM_TRANSACTION_MSG_GETCLASSIDREQ = 1,
        COM_TRANSACTION_MSG_GETCLASSIDRSP = 2,
        COM_TRANSACTION_MSG_GETGUILDNAMEREQ = 3,
        COM_TRANSACTION_MSG_GETGUILDNAMERSP = 4,
        COM_TRANSACTION_MSG_IDIP_BANACNTREQ = 7,
        COM_TRANSACTION_MSG_IDIP_BANACNTRSP = 8,
        COM_TRANSACTION_MSG_IDIP_BANTIMESYNREQ = 9,
        COM_TRANSACTION_MSG_IDIP_BANTIMESYNRSP = 10,
        COM_TRANSACTION_MSG_IDIP_CHGACNTINFOONLINEREQ = 13,
        COM_TRANSACTION_MSG_IDIP_CHGACNTINFOONLINERSP = 14,
        COM_TRANSACTION_MSG_IDIP_SENDMAILREQ = 5,
        COM_TRANSACTION_MSG_IDIP_SENDMAILRSP = 6,
        COM_TRANSACTION_MSG_OF_IDIP_DELACNTPKGINFOREQ = 15,
        COM_TRANSACTION_MSG_OF_IDIP_DELACNTPKGINFORSP = 0x10,
        COM_TRANSACTION_MSG_OF_IDIP_QUERYGOLDRANKINFOREQ = 0x11,
        COM_TRANSACTION_MSG_OF_IDIP_QUERYGOLDRANKINFORSP = 0x12,
        COM_TRANSACTION_MSG_WORLD_REWARDLIMITREQ = 11,
        COM_TRANSACTION_MSG_WORLD_REWARDLIMITRSP = 12
    }
}

