namespace CSProtocol
{
    using System;

    public enum COM_APOLLO_TRANK_USERBUFFER_TYPE
    {
        COM_APOLLO_TRANK_USERBUFFER_TYPE_CLEAR_SPECIAL_TOPN = 4,
        COM_APOLLO_TRANK_USERBUFFER_TYPE_GET_SPECIAL_SCORE = 5,
        COM_APOLLO_TRANK_USERBUFFER_TYPE_GET_TOPN = 2,
        COM_APOLLO_TRANK_USERBUFFER_TYPE_GET_TOPN_LUCKY = 6,
        COM_APOLLO_TRANK_USERBUFFER_TYPE_GET_USER_INFO = 3,
        COM_APOLLO_TRANK_USERBUFFER_TYPE_MAX = 7,
        COM_APOLLO_TRANK_USERBUFFER_TYPE_UPLOAD_SCORE = 1
    }
}

