namespace CSProtocol
{
    using System;

    public enum COM_APPOINT_POSITION_TRANS_TYPE
    {
        COM_APPOINT_POSITION_TRANS_TYPE_APPOINT,
        COM_APPOINT_POSITION_TRANS_TYPE_DEAL_SELF_RECOMMEND,
        COM_APPOINT_POSITION_TRANS_TYPE_SELF_RECOMMEND_TIMEOUT
    }
}

