namespace CSProtocol
{
    using System;

    public enum COM_ACNT_NEWCLIENT_BITS_TYPE
    {
        COM_ACNT_NEWCLIENT_BITS_TYPE_CLTUSE_END = 200,
        COM_ACNT_NEWCLIENT_BITS_TYPE_CLTUSE_START = 100,
        COM_ACNT_NEWCLIENT_BITS_TYPE_GIFTITEM_ADD = 2,
        COM_ACNT_NEWCLIENT_BITS_TYPE_MAX = 0xc9,
        COM_ACNT_NEWCLIENT_BITS_TYPE_NEWBITGIFT_SHOW = 0,
        COM_ACNT_NEWCLIENT_BITS_TYPE_PROPITEM_ADD = 1,
        COM_ACNT_NEWCLIENT_BITS_TYPE_SHOW_HERO_TRICK_TIPS = 3,
        COM_ACNT_NEWCLIENT_BITS_TYPE_ShOW_LBS_GUIDE = 4
    }
}

