namespace CSProtocol
{
    using System;

    public enum COM_MAILACCESSMONEY_TYPE
    {
        COM_MAILACCESSMONEY_BURNINGDAIBI = 4,
        COM_MAILACCESSMONEY_COIN = 1,
        COM_MAILACCESSMONEY_COUPONS = 2,
        COM_MAILACCESSMONEY_DIAMOND = 7,
        COM_MAILACCESSMONEY_GUILDSHOPDAIBI = 5,
        COM_MAILACCESSMONEY_RACEDAIBI = 3,
        COM_MAILACCESSMONEY_SYMBOLCOIN = 6
    }
}

