namespace CSProtocol
{
    using System;

    public enum CS_AKALISHOP_ERROR
    {
        CS_AKALISHOP_SUCCESS,
        CS_AKALISHOP_ERROR_SHOPNOTOPEN,
        CS_AKALISHOP_ERROR_SHOPNOTCLOSE,
        CS_AKALISHOP_ERROR_OVERTOTALLIMIT,
        CS_AKALISHOP_ERROR_NOTHAVEZHEKOU,
        CS_AKALISHOP_ERROR_GOODSNOTINSHOP,
        CS_AKALISHOP_ERROR_OVERGOODSLIMIT,
        CS_AKALISHOP_ERROR_ACNTNULL,
        CS_AKALISHOP_ERROR_HAVEROUZHEKOU,
        CS_AKALISHOP_ERROR_VALIDSHOP
    }
}

