namespace CSProtocol
{
    using System;

    public enum CS_PRESENTHEROSKIN_ERRCODE
    {
        CS_PRESENTHEROSKIN_COINLIMIT = 5,
        CS_PRESENTHEROSKIN_FRIENDTIME = 11,
        CS_PRESENTHEROSKIN_HEROINVALID = 8,
        CS_PRESENTHEROSKIN_INVALID_PLAT = 12,
        CS_PRESENTHEROSKIN_LIMITMAX = 10,
        CS_PRESENTHEROSKIN_LOCK = 2,
        CS_PRESENTHEROSKIN_MAILFAIL = 6,
        CS_PRESENTHEROSKIN_NOALLOW = 3,
        CS_PRESENTHEROSKIN_PROMOTION = 7,
        CS_PRESENTHEROSKIN_SELF = 13,
        CS_PRESENTHEROSKIN_SKININVALID = 9,
        CS_PRESENTHEROSKIN_SYS = 1,
        CS_PRESENTHEROSKIN_UNFRIEND = 4
    }
}

