namespace CSProtocol
{
    using System;

    public enum CS_ROOMERRORCODE_DEF
    {
        CS_ROOMERR_ACNTLEAVE = 4,
        CS_ROOMERR_GAMEABORT = 2,
        CS_ROOMERR_PLAT_CHANNEL_CLOSE = 0x1d,
        CS_ROOMERR_RELAYSVR_LIMIT = 1,
        CS_ROOMERR_ROOM_ALREADY_START = 6,
        CS_ROOMERR_ROOM_BAN_PICK_HERO_LIMIT = 30,
        CS_ROOMERR_ROOM_BAN_PICK_LIMIT = 0x1c,
        CS_ROOMERR_ROOM_BANTIME = 20,
        CS_ROOMERR_ROOM_FRIEND_BUSY = 13,
        CS_ROOMERR_ROOM_FRIEND_OFFLINE = 12,
        CS_ROOMERR_ROOM_HIGHVERSION = 0x16,
        CS_ROOMERR_ROOM_INBANTIME = 0x1a,
        CS_ROOMERR_ROOM_INVALIDPARAM = 10,
        CS_ROOMERR_ROOM_INVITE_DENY = 14,
        CS_ROOMERR_ROOM_LIMIT_ENTERTAINMENT_FUNC = 0x18,
        CS_ROOMERR_ROOM_LIMIT_FUNC = 0x1b,
        CS_ROOMERR_ROOM_LIMIT_PRIVILEGE = 9,
        CS_ROOMERR_ROOM_LIMIT_REWARDMATCH_FUNC = 0x19,
        CS_ROOMERR_ROOM_LOWVERSION = 0x17,
        CS_ROOMERR_ROOM_MEMBERFULL = 7,
        CS_ROOMERR_ROOM_NOT_FOUND = 5,
        CS_ROOMERR_ROOM_NOTFOUND_FRIEND = 11,
        CS_ROOMERR_ROOM_OTHERS = 8,
        CS_ROOMERR_ROOM_OTHERSLEAVE = 0x13,
        CS_ROOMERR_ROOM_OTHERSUNCONFIRM = 0x12,
        CS_ROOMERR_ROOM_TEAMERLEAVE = 0x11,
        CS_ROOMERR_ROOM_TEAMERUNCONFIRM = 0x10,
        CS_ROOMERR_ROOM_UNCONFIRM = 15,
        CS_ROOMERR_ROOM_VERSION_LIMIT = 0x15,
        CS_ROOMERR_TIMEOUT = 3
    }
}

