namespace CSProtocol
{
    using System;

    public enum CS_SALERECOMMEND_ERRCODE
    {
        CS_SALERECOMMEND_ERR_BUYFAIL = 9,
        CS_SALERECOMMEND_ERR_DUP = 4,
        CS_SALERECOMMEND_ERR_ID = 2,
        CS_SALERECOMMEND_ERR_INVALDITEM = 10,
        CS_SALERECOMMEND_ERR_ITEM = 7,
        CS_SALERECOMMEND_ERR_ITEM_INVALID = 8,
        CS_SALERECOMMEND_ERR_MONEY = 6,
        CS_SALERECOMMEND_ERR_OUTDATE = 3,
        CS_SALERECOMMEND_ERR_PAY = 5,
        CS_SALERECOMMEND_ERR_SYS = 1
    }
}

