namespace CSProtocol
{
    using System;

    public enum CS_SINGLEGAME_ERRCODE
    {
        CS_SINGLEGAME_ERR_BANTIME = 10,
        CS_SINGLEGAME_ERR_EXPSKIN = 12,
        CS_SINGLEGAME_ERR_FAIL = 1,
        CS_SINGLEGAME_ERR_FREEHERO = 11,
        CS_SINGLEGAMEOFARENA_ERR_LIMIT_CD = 8,
        CS_SINGLEGAMEOFARENA_ERR_LIMIT_CNT = 7,
        CS_SINGLEGAMEOFARENA_ERR_NOTFINDTARGET = 5,
        CS_SINGLEGAMEOFARENA_ERR_OTHERS = 6,
        CS_SINGLEGAMEOFARENA_ERR_REWARD_STATE = 9,
        CS_SINGLEGAMEOFARENA_ERR_SELFLOCK = 2,
        CS_SINGLEGAMEOFARENA_ERR_TARGETCHG = 4,
        CS_SINGLEGAMEOFARENA_ERR_TARGETLOCK = 3
    }
}

