namespace CSProtocol
{
    using System;

    public enum CS_WEALDRAW_ERRCODE
    {
        CS_WEALDRAW_ERR_DRAWED = 4,
        CS_WEALDRAW_ERR_FILLINPRICE = 6,
        CS_WEALDRAW_ERR_INCOMPLETE = 3,
        CS_WEALDRAW_ERR_INVALIDPERIODTIME = 2,
        CS_WEALDRAW_ERR_INVALIDTIME = 1,
        CS_WEALDRAW_ERR_LACKCOUPONS = 7,
        CS_WEALDRAW_ERR_LACKITEM = 15,
        CS_WEALDRAW_ERR_LACKPOINT = 0x11,
        CS_WEALDRAW_ERR_NORES = 5,
        CS_WEALDRAW_ERR_NOREWARDDATA = 12,
        CS_WEALDRAW_ERR_NOWWEALCON = 10,
        CS_WEALDRAW_ERR_OTHERS = 14,
        CS_WEALDRAW_ERR_PAY = 8,
        CS_WEALDRAW_ERR_PAYTIMEOUT = 9,
        CS_WEALDRAW_ERR_PERIOD = 11,
        CS_WEALDRAW_ERR_RECORDFULL = 0x10,
        CS_WEALDRAW_ERR_REWARDACNT = 13
    }
}

