namespace CSProtocol
{
    using System;

    public enum FRAMECMD_ID_DEF
    {
        FRAME_CMD_ASSISTSTATECHG = 0x16,
        FRAME_CMD_ATTACKACTOR = 5,
        FRAME_CMD_ATTACKPOSITION = 4,
        FRAME_CMD_BUY_HORIZON_EQUIP = 0x22,
        FRAME_CMD_CHGAUTOAI = 0x17,
        FRAME_CMD_INVALID = 0,
        FRAME_CMD_LEARNSKILL = 6,
        FRAME_CMD_LEARNTALENT = 15,
        FRAME_CMD_LOCKATTACKTARGET = 0x1d,
        FRAME_CMD_PLAYATTACKTARGETMODE = 20,
        FRAME_CMD_PLAYCOMMONATTACKTMODE = 0x1c,
        FRAME_CMD_PLAYER_ADD_GOLD_COIN_IN_BATTLE = 0x1a,
        FRAME_CMD_PLAYER_BUY_EQUIP = 0x18,
        FRAME_CMD_PLAYER_SELL_EQUIP = 0x19,
        FRAME_CMD_PLAYERDISCONNECT = 0x12,
        FRAME_CMD_PLAYERMOVE = 1,
        FRAME_CMD_PLAYERMOVEDIRECTION = 2,
        FRAME_CMD_PLAYERRECONNECT = 0x13,
        FRAME_CMD_PLAYERRUNAWAY = 0x11,
        FRAME_CMD_PLAYERSTOPMOVE = 3,
        FRAME_CMD_SET_SKILL_LEVEL = 0x1b,
        FRAME_CMD_Signal_Btn_Position = 30,
        FRAME_CMD_Signal_MiniMap_Position = 0x1f,
        FRAME_CMD_Signal_MiniMap_Target = 0x20,
        FRAME_CMD_SVRNTF_GAMEOVER = 0x21,
        FRAME_CMD_SVRNTFCHGKFRAMELATER = 0x15,
        FRAME_CMD_SWITCHAOUTAI = 11,
        FRAME_CMD_SWITCHCAPTAIN = 12,
        FRAME_CMD_SWITCHGODMODE = 14,
        FRAME_CMD_SWITCHSUPERKILLER = 13,
        FRAME_CMD_TESTCOMMANDDELAY = 0x10,
        FRAME_CMD_USECOMMONATTACK = 10,
        FRAME_CMD_USECURVETRACKSKILL = 9
    }
}

