namespace TMPro
{
    using System;

    public enum FontStyles
    {
        Bold = 1,
        BoldItalic = 3,
        BoldItalicStrikethrough = 0x43,
        BoldItalicUnderline = 7,
        BoldItalicUnderlineStrikethrough = 0x47,
        BoldStrikethrough = 0x41,
        BoldUnderline = 5,
        BoldUnderlineStrikethrough = 0x45,
        Italic = 2,
        ItalicStrikethrough = 0x42,
        ItalicUnderline = 6,
        ItalicUnderlineStrikethrough = 70,
        LowerCase = 8,
        LowerCaseBold = 9,
        LowerCaseBoldItalic = 11,
        LowerCaseBoldItalicStrikethrough = 0x4b,
        LowerCaseBoldItalicUnderline = 15,
        LowerCaseBoldItalicUnderlineStrikethrough = 0x4f,
        LowerCaseBoldStrikethrough = 0x49,
        LowerCaseBoldUnderline = 13,
        LowerCaseBoldUnderlineStrikethrough = 0x4d,
        LowerCaseItalic = 10,
        LowerCaseItalicStrikethrough = 0x4a,
        LowerCaseStrikethrough = 0x48,
        LowerCaseUnderline = 12,
        Normal = 0,
        SmallCaps = 0x20,
        SmallCapsBold = 0x21,
        SmallCapsBoldItalic = 0x23,
        SmallCapsBoldItalicStrikethrough = 0x63,
        SmallCapsBoldItalicUnderline = 0x27,
        SmallCapsBoldItalicUnderlineStrikethrough = 0x67,
        SmallCapsBoldStrikethrough = 0x61,
        SmallCapsBoldUnderline = 0x25,
        SmallCapsBoldUnderlineStrikethrough = 0x65,
        SmallCapsItalic = 0x22,
        SmallCapsItalicStrikethrough = 0x62,
        SmallCapsStrikethrough = 0x60,
        SmallCapsUnderline = 0x24,
        Strikethrough = 0x40,
        Underline = 4,
        UpperCase = 0x10,
        UpperCaseBold = 0x11,
        UpperCaseBoldItalic = 0x13,
        UpperCaseBoldItalicStrikethrough = 0x53,
        UpperCaseBoldItalicUnderlineStrikethrough = 0x57,
        UpperCaseBoldStrikethrough = 0x51,
        UpperCaseBoldUnderline = 0x15,
        UpperCaseBoldUnderlineStrikethrough = 0x55,
        UpperCaseBoltItalicUnderline = 0x17,
        UpperCaseItalic = 0x12,
        UpperCaseItalicStrikethrough = 0x52,
        UpperCaseStrikethrough = 80,
        UpperCaseUnderline = 20
    }
}

