namespace Apollo
{
    using System;

    public enum ApolloResult
    {
        AccessTokenExpired = 0x10,
        AuthFailed = 0x80,
        ConnectFailed = 0x67,
        Empty = 7,
        Error = 1,
        GcpError = 120,
        GooglePlayNotSupport = 0x38,
        HttpBadHeader = 0x113,
        HttpBadMethod = 0x111,
        HttpBadURL = 0x110,
        HttpBadVersion = 0x10f,
        HttpOtherError = 270,
        HttpReqToLong = 0x112,
        Incomplete = 0x35,
        InitializeError = 50,
        InnerError = 100,
        InvalidArgument = 4,
        InvalidServiceId = 0x68,
        IsConnecting = 0x69,
        ItemInvalidate = 0x34,
        LengthError = 5,
        LoginFailed = 14,
        MarketError = 0x33,
        NeedReset = 0x13,
        NetworkException = 2,
        NoAccessToken = 15,
        NoConnection = 0x66,
        NoPermission = 20,
        NotInitialized = 0x65,
        NotYetConsume = 0x36,
        Others = 0x2710,
        PayTokenExpired = 0x12,
        PeerCloseConnection = 0x79,
        PeerStopSession = 0x7a,
        PkgNotCompleted = 0x7b,
        PlatformNotInstall = 10,
        PlatformNotSupportApi = 11,
        PluginEnd = 0x63,
        RefreshTokenExpired = 0x11,
        SendFailed = 0x7c,
        StayInQueue = 0x7d,
        Success = 0,
        SvrIsFull = 0x7e,
        Timeout = 3,
        TokenInvalid = 0x10,
        TokenSvrError = 0x7f,
        TransactionIdNotExist = 0x37,
        Unknown = 6,
        UserCancel = 12,
        UserDenied = 13
    }
}

