namespace behaviac
{
    using System;

    public static class bt_WrapperAI_Monster_BTMonsterZhaoHuanWu
    {
        public static bool build_behavior_tree(BehaviorTree bt)
        {
            bt.SetClassNameString("BehaviorTree");
            bt.SetId(-1);
            bt.SetName("WrapperAI/Monster/BTMonsterZhaoHuanWu");
            bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
            bt.AddPar("uint", "p_targetID", "0", string.Empty);
            bt.AddPar("int", "p_srchRange", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
            bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
            bt.AddPar("uint", "p_CmdID", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_skillAttackRange", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_orignalPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_pursuitRange", "0", string.Empty);
            bt.AddPar("uint", "p_selfID", "0", string.Empty);
            bt.AddPar("uint", "p_teamTarget", "0", string.Empty);
            bt.AddPar("uint", "p_captainID", "0", string.Empty);
            bt.AddPar("uint", "p_nearstMember", "0", string.Empty);
            bt.AddPar("bool", "p_forceToApproachHero", "false", string.Empty);
            bt.AddPar("uint", "p_terrorMeActor", "0", string.Empty);
            Sequence pChild = new Sequence();
            pChild.SetClassNameString("Sequence");
            pChild.SetId(0);
            bt.AddChild(pChild);
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node98 _node = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node98();
            _node.SetClassNameString("Assignment");
            _node.SetId(0x62);
            pChild.AddChild(_node);
            pChild.SetHasEvents(pChild.HasEvents() | _node.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node31 _node2 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node31();
            _node2.SetClassNameString("Assignment");
            _node2.SetId(0x1f);
            pChild.AddChild(_node2);
            pChild.SetHasEvents(pChild.HasEvents() | _node2.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node48 _node3 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node48();
            _node3.SetClassNameString("Assignment");
            _node3.SetId(0x30);
            pChild.AddChild(_node3);
            pChild.SetHasEvents(pChild.HasEvents() | _node3.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node11 _node4 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node11();
            _node4.SetClassNameString("Assignment");
            _node4.SetId(11);
            pChild.AddChild(_node4);
            pChild.SetHasEvents(pChild.HasEvents() | _node4.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node14 _node5 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node14();
            _node5.SetClassNameString("DecoratorLoop");
            _node5.SetId(14);
            pChild.AddChild(_node5);
            SelectorLoop loop = new SelectorLoop();
            loop.SetClassNameString("SelectorLoop");
            loop.SetId(1);
            _node5.AddChild(loop);
            WithPrecondition precondition = new WithPrecondition();
            precondition.SetClassNameString("WithPrecondition");
            precondition.SetId(60);
            loop.AddChild(precondition);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node61 _node6 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node61();
            _node6.SetClassNameString("Condition");
            _node6.SetId(0x3d);
            precondition.AddChild(_node6);
            precondition.SetHasEvents(precondition.HasEvents() | _node6.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node64 _node7 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node64();
            _node7.SetClassNameString("Action");
            _node7.SetId(0x40);
            precondition.AddChild(_node7);
            precondition.SetHasEvents(precondition.HasEvents() | _node7.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition.HasEvents());
            WithPrecondition precondition2 = new WithPrecondition();
            precondition2.SetClassNameString("WithPrecondition");
            precondition2.SetId(70);
            loop.AddChild(precondition2);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node71 _node8 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node71();
            _node8.SetClassNameString("Condition");
            _node8.SetId(0x47);
            precondition2.AddChild(_node8);
            precondition2.SetHasEvents(precondition2.HasEvents() | _node8.HasEvents());
            SelectorLoop loop2 = new SelectorLoop();
            loop2.SetClassNameString("SelectorLoop");
            loop2.SetId(0x41);
            precondition2.AddChild(loop2);
            WithPrecondition precondition3 = new WithPrecondition();
            precondition3.SetClassNameString("WithPrecondition");
            precondition3.SetId(0x167);
            loop2.AddChild(precondition3);
            Sequence sequence2 = new Sequence();
            sequence2.SetClassNameString("Sequence");
            sequence2.SetId(0x16b);
            precondition3.AddChild(sequence2);
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node364 _node9 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node364();
            _node9.SetClassNameString("Assignment");
            _node9.SetId(0x16c);
            sequence2.AddChild(_node9);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node9.HasEvents());
            IfElse @else = new IfElse();
            @else.SetClassNameString("IfElse");
            @else.SetId(0x16d);
            sequence2.AddChild(@else);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node361 _node10 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node361();
            _node10.SetClassNameString("Condition");
            _node10.SetId(0x169);
            @else.AddChild(_node10);
            @else.SetHasEvents(@else.HasEvents() | _node10.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node366 _node11 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node366();
            _node11.SetClassNameString("Assignment");
            _node11.SetId(0x16e);
            @else.AddChild(_node11);
            @else.SetHasEvents(@else.HasEvents() | _node11.HasEvents());
            Noop noop = new Noop();
            noop.SetClassNameString("Noop");
            noop.SetId(0x16f);
            @else.AddChild(noop);
            @else.SetHasEvents(@else.HasEvents() | noop.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | @else.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node360 _node12 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node360();
            _node12.SetClassNameString("Condition");
            _node12.SetId(360);
            sequence2.AddChild(_node12);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node12.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node557 _node13 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node557();
            _node13.SetClassNameString("Assignment");
            _node13.SetId(0x22d);
            sequence2.AddChild(_node13);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node13.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node561 _node14 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node561();
            _node14.SetClassNameString("Action");
            _node14.SetId(0x231);
            sequence2.AddChild(_node14);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node14.HasEvents());
            precondition3.SetHasEvents(precondition3.HasEvents() | sequence2.HasEvents());
            Selector selector = new Selector();
            selector.SetClassNameString("Selector");
            selector.SetId(370);
            precondition3.AddChild(selector);
            Sequence sequence3 = new Sequence();
            sequence3.SetClassNameString("Sequence");
            sequence3.SetId(0x173);
            selector.AddChild(sequence3);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node16 _node15 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node16();
            _node15.SetClassNameString("Action");
            _node15.SetId(0x10);
            sequence3.AddChild(_node15);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node15.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node223 _node16 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node223();
            _node16.SetClassNameString("Condition");
            _node16.SetId(0xdf);
            sequence3.AddChild(_node16);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node16.HasEvents());
            Sequence sequence4 = new Sequence();
            sequence4.SetClassNameString("Sequence");
            sequence4.SetId(0xe1);
            sequence3.AddChild(sequence4);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node118 _node17 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node118();
            _node17.SetClassNameString("Action");
            _node17.SetId(0x76);
            sequence4.AddChild(_node17);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node17.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node227 _node18 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node227();
            _node18.SetClassNameString("Action");
            _node18.SetId(0xe3);
            sequence4.AddChild(_node18);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node18.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node334 _node19 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node334();
            _node19.SetClassNameString("Action");
            _node19.SetId(0x14e);
            sequence4.AddChild(_node19);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node19.HasEvents());
            sequence3.SetHasEvents(sequence3.HasEvents() | sequence4.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence3.HasEvents());
            Sequence sequence5 = new Sequence();
            sequence5.SetClassNameString("Sequence");
            sequence5.SetId(0x182);
            selector.AddChild(sequence5);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node387 _node20 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node387();
            _node20.SetClassNameString("Condition");
            _node20.SetId(0x183);
            sequence5.AddChild(_node20);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node20.HasEvents());
            Sequence sequence6 = new Sequence();
            sequence6.SetClassNameString("Sequence");
            sequence6.SetId(0x184);
            sequence5.AddChild(sequence6);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node389 _node21 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node389();
            _node21.SetClassNameString("Action");
            _node21.SetId(0x185);
            sequence6.AddChild(_node21);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node21.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node390 _node22 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node390();
            _node22.SetClassNameString("Action");
            _node22.SetId(390);
            sequence6.AddChild(_node22);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node22.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node394 _node23 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node394();
            _node23.SetClassNameString("Assignment");
            _node23.SetId(0x18a);
            sequence6.AddChild(_node23);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node23.HasEvents());
            sequence5.SetHasEvents(sequence5.HasEvents() | sequence6.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
            Sequence sequence7 = new Sequence();
            sequence7.SetClassNameString("Sequence");
            sequence7.SetId(0x187);
            selector.AddChild(sequence7);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node392 _node24 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node392();
            _node24.SetClassNameString("Condition");
            _node24.SetId(0x188);
            sequence7.AddChild(_node24);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node24.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node393 _node25 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node393();
            _node25.SetClassNameString("Action");
            _node25.SetId(0x189);
            sequence7.AddChild(_node25);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node25.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node395 _node26 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node395();
            _node26.SetClassNameString("Assignment");
            _node26.SetId(0x18b);
            sequence7.AddChild(_node26);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node26.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence7.HasEvents());
            precondition3.SetHasEvents(precondition3.HasEvents() | selector.HasEvents());
            loop2.SetHasEvents(loop2.HasEvents() | precondition3.HasEvents());
            WithPrecondition precondition4 = new WithPrecondition();
            precondition4.SetClassNameString("WithPrecondition");
            precondition4.SetId(2);
            loop2.AddChild(precondition4);
            True @true = new True();
            @true.SetClassNameString("True");
            @true.SetId(0x48);
            precondition4.AddChild(@true);
            precondition4.SetHasEvents(precondition4.HasEvents() | @true.HasEvents());
            Sequence sequence8 = new Sequence();
            sequence8.SetClassNameString("Sequence");
            sequence8.SetId(0x4b);
            precondition4.AddChild(sequence8);
            IfElse else2 = new IfElse();
            else2.SetClassNameString("IfElse");
            else2.SetId(0xd7);
            sequence8.AddChild(else2);
            And and = new And();
            and.SetClassNameString("And");
            and.SetId(0xd8);
            else2.AddChild(and);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node217 _node27 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node217();
            _node27.SetClassNameString("Condition");
            _node27.SetId(0xd9);
            and.AddChild(_node27);
            and.SetHasEvents(and.HasEvents() | _node27.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node218 _node28 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node218();
            _node28.SetClassNameString("Condition");
            _node28.SetId(0xda);
            and.AddChild(_node28);
            and.SetHasEvents(and.HasEvents() | _node28.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | and.HasEvents());
            Noop noop2 = new Noop();
            noop2.SetClassNameString("Noop");
            noop2.SetId(0xdb);
            else2.AddChild(noop2);
            else2.SetHasEvents(else2.HasEvents() | noop2.HasEvents());
            DecoratorAlwaysSuccess_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node327 _node29 = new DecoratorAlwaysSuccess_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node327();
            _node29.SetClassNameString("DecoratorAlwaysSuccess");
            _node29.SetId(0x147);
            else2.AddChild(_node29);
            Sequence sequence9 = new Sequence();
            sequence9.SetClassNameString("Sequence");
            sequence9.SetId(0x148);
            _node29.AddChild(sequence9);
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node128 _node30 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node128();
            _node30.SetClassNameString("Assignment");
            _node30.SetId(0x80);
            sequence9.AddChild(_node30);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node30.HasEvents());
            IfElse else3 = new IfElse();
            else3.SetClassNameString("IfElse");
            else3.SetId(0x149);
            sequence9.AddChild(else3);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node335 _node31 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node335();
            _node31.SetClassNameString("Condition");
            _node31.SetId(0x14f);
            else3.AddChild(_node31);
            else3.SetHasEvents(else3.HasEvents() | _node31.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node336 _node32 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node336();
            _node32.SetClassNameString("Assignment");
            _node32.SetId(0x150);
            else3.AddChild(_node32);
            else3.SetHasEvents(else3.HasEvents() | _node32.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node337 _node33 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node337();
            _node33.SetClassNameString("Assignment");
            _node33.SetId(0x151);
            else3.AddChild(_node33);
            else3.SetHasEvents(else3.HasEvents() | _node33.HasEvents());
            sequence9.SetHasEvents(sequence9.HasEvents() | else3.HasEvents());
            _node29.SetHasEvents(_node29.HasEvents() | sequence9.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | _node29.HasEvents());
            sequence8.SetHasEvents(sequence8.HasEvents() | else2.HasEvents());
            IfElse else4 = new IfElse();
            else4.SetClassNameString("IfElse");
            else4.SetId(0x86);
            sequence8.AddChild(else4);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node5 _node34 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node5();
            _node34.SetClassNameString("Condition");
            _node34.SetId(5);
            else4.AddChild(_node34);
            else4.SetHasEvents(else4.HasEvents() | _node34.HasEvents());
            Sequence sequence10 = new Sequence();
            sequence10.SetClassNameString("Sequence");
            sequence10.SetId(0x89);
            else4.AddChild(sequence10);
            Selector selector2 = new Selector();
            selector2.SetClassNameString("Selector");
            selector2.SetId(0x8a);
            sequence10.AddChild(selector2);
            Sequence sequence11 = new Sequence();
            sequence11.SetClassNameString("Sequence");
            sequence11.SetId(0x99);
            selector2.AddChild(sequence11);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node94 _node35 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node94();
            _node35.SetClassNameString("Action");
            _node35.SetId(0x5e);
            sequence11.AddChild(_node35);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node35.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node159 _node36 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node159();
            _node36.SetClassNameString("Assignment");
            _node36.SetId(0x9f);
            sequence11.AddChild(_node36);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node36.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node160 _node37 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node160();
            _node37.SetClassNameString("Assignment");
            _node37.SetId(160);
            sequence11.AddChild(_node37);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node37.HasEvents());
            Selector selector3 = new Selector();
            selector3.SetClassNameString("Selector");
            selector3.SetId(0x11);
            sequence11.AddChild(selector3);
            Sequence sequence12 = new Sequence();
            sequence12.SetClassNameString("Sequence");
            sequence12.SetId(0x67);
            selector3.AddChild(sequence12);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node712 _node38 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node712();
            _node38.SetClassNameString("Action");
            _node38.SetId(0x2c8);
            sequence12.AddChild(_node38);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node38.HasEvents());
            Selector selector4 = new Selector();
            selector4.SetClassNameString("Selector");
            selector4.SetId(3);
            sequence12.AddChild(selector4);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node109 _node39 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node109();
            _node39.SetClassNameString("Condition");
            _node39.SetId(0x6d);
            selector4.AddChild(_node39);
            selector4.SetHasEvents(selector4.HasEvents() | _node39.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node4 _node40 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node4();
            _node40.SetClassNameString("Condition");
            _node40.SetId(4);
            selector4.AddChild(_node40);
            selector4.SetHasEvents(selector4.HasEvents() | _node40.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node9 _node41 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node9();
            _node41.SetClassNameString("Condition");
            _node41.SetId(9);
            selector4.AddChild(_node41);
            selector4.SetHasEvents(selector4.HasEvents() | _node41.HasEvents());
            sequence12.SetHasEvents(sequence12.HasEvents() | selector4.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node6 _node42 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node6();
            _node42.SetClassNameString("Condition");
            _node42.SetId(6);
            sequence12.AddChild(_node42);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node42.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node10 _node43 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node10();
            _node43.SetClassNameString("Action");
            _node43.SetId(10);
            sequence12.AddChild(_node43);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node43.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence12.HasEvents());
            Sequence sequence13 = new Sequence();
            sequence13.SetClassNameString("Sequence");
            sequence13.SetId(13);
            selector3.AddChild(sequence13);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node15 _node44 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node15();
            _node44.SetClassNameString("Condition");
            _node44.SetId(15);
            sequence13.AddChild(_node44);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node44.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node110 _node45 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node110();
            _node45.SetClassNameString("Assignment");
            _node45.SetId(110);
            sequence13.AddChild(_node45);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node45.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node19 _node46 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node19();
            _node46.SetClassNameString("Condition");
            _node46.SetId(0x13);
            sequence13.AddChild(_node46);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node46.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node12 _node47 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node12();
            _node47.SetClassNameString("Action");
            _node47.SetId(12);
            sequence13.AddChild(_node47);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node47.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence13.HasEvents());
            Sequence sequence14 = new Sequence();
            sequence14.SetClassNameString("Sequence");
            sequence14.SetId(20);
            selector3.AddChild(sequence14);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node21 _node48 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node21();
            _node48.SetClassNameString("Condition");
            _node48.SetId(0x15);
            sequence14.AddChild(_node48);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node48.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node22 _node49 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node22();
            _node49.SetClassNameString("Condition");
            _node49.SetId(0x16);
            sequence14.AddChild(_node49);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node49.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node23 _node50 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node23();
            _node50.SetClassNameString("Action");
            _node50.SetId(0x17);
            sequence14.AddChild(_node50);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node50.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence14.HasEvents());
            sequence11.SetHasEvents(sequence11.HasEvents() | selector3.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence11.HasEvents());
            Sequence sequence15 = new Sequence();
            sequence15.SetClassNameString("Sequence");
            sequence15.SetId(0x33);
            selector2.AddChild(sequence15);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node140 _node51 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node140();
            _node51.SetClassNameString("Action");
            _node51.SetId(140);
            sequence15.AddChild(_node51);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node51.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node52 _node52 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node52();
            _node52.SetClassNameString("Assignment");
            _node52.SetId(0x34);
            sequence15.AddChild(_node52);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node52.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node53 _node53 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node53();
            _node53.SetClassNameString("Assignment");
            _node53.SetId(0x35);
            sequence15.AddChild(_node53);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node53.HasEvents());
            Selector selector5 = new Selector();
            selector5.SetClassNameString("Selector");
            selector5.SetId(0x36);
            sequence15.AddChild(selector5);
            Sequence sequence16 = new Sequence();
            sequence16.SetClassNameString("Sequence");
            sequence16.SetId(0x18);
            selector5.AddChild(sequence16);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node25 _node54 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node25();
            _node54.SetClassNameString("Action");
            _node54.SetId(0x19);
            sequence16.AddChild(_node54);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node54.HasEvents());
            Selector selector6 = new Selector();
            selector6.SetClassNameString("Selector");
            selector6.SetId(0x1a);
            sequence16.AddChild(selector6);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node27 _node55 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node27();
            _node55.SetClassNameString("Condition");
            _node55.SetId(0x1b);
            selector6.AddChild(_node55);
            selector6.SetHasEvents(selector6.HasEvents() | _node55.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node28 _node56 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node28();
            _node56.SetClassNameString("Condition");
            _node56.SetId(0x1c);
            selector6.AddChild(_node56);
            selector6.SetHasEvents(selector6.HasEvents() | _node56.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node29 _node57 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node29();
            _node57.SetClassNameString("Condition");
            _node57.SetId(0x1d);
            selector6.AddChild(_node57);
            selector6.SetHasEvents(selector6.HasEvents() | _node57.HasEvents());
            sequence16.SetHasEvents(sequence16.HasEvents() | selector6.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node30 _node58 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node30();
            _node58.SetClassNameString("Condition");
            _node58.SetId(30);
            sequence16.AddChild(_node58);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node58.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node32 _node59 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node32();
            _node59.SetClassNameString("Action");
            _node59.SetId(0x20);
            sequence16.AddChild(_node59);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node59.HasEvents());
            selector5.SetHasEvents(selector5.HasEvents() | sequence16.HasEvents());
            Sequence sequence17 = new Sequence();
            sequence17.SetClassNameString("Sequence");
            sequence17.SetId(0x21);
            selector5.AddChild(sequence17);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node34 _node60 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node34();
            _node60.SetClassNameString("Condition");
            _node60.SetId(0x22);
            sequence17.AddChild(_node60);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node60.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node111 _node61 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node111();
            _node61.SetClassNameString("Assignment");
            _node61.SetId(0x6f);
            sequence17.AddChild(_node61);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node61.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node36 _node62 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node36();
            _node62.SetClassNameString("Condition");
            _node62.SetId(0x24);
            sequence17.AddChild(_node62);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node62.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node37 _node63 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node37();
            _node63.SetClassNameString("Action");
            _node63.SetId(0x25);
            sequence17.AddChild(_node63);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node63.HasEvents());
            selector5.SetHasEvents(selector5.HasEvents() | sequence17.HasEvents());
            Sequence sequence18 = new Sequence();
            sequence18.SetClassNameString("Sequence");
            sequence18.SetId(0x26);
            selector5.AddChild(sequence18);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node39 _node64 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node39();
            _node64.SetClassNameString("Condition");
            _node64.SetId(0x27);
            sequence18.AddChild(_node64);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node64.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node112 _node65 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node112();
            _node65.SetClassNameString("Condition");
            _node65.SetId(0x70);
            sequence18.AddChild(_node65);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node65.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node113 _node66 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node113();
            _node66.SetClassNameString("Action");
            _node66.SetId(0x71);
            sequence18.AddChild(_node66);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node66.HasEvents());
            selector5.SetHasEvents(selector5.HasEvents() | sequence18.HasEvents());
            sequence15.SetHasEvents(sequence15.HasEvents() | selector5.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence15.HasEvents());
            Sequence sequence19 = new Sequence();
            sequence19.SetClassNameString("Sequence");
            sequence19.SetId(0x68);
            selector2.AddChild(sequence19);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node105 _node67 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node105();
            _node67.SetClassNameString("Action");
            _node67.SetId(0x69);
            sequence19.AddChild(_node67);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node67.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node106 _node68 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node106();
            _node68.SetClassNameString("Assignment");
            _node68.SetId(0x6a);
            sequence19.AddChild(_node68);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node68.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node107 _node69 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node107();
            _node69.SetClassNameString("Assignment");
            _node69.SetId(0x6b);
            sequence19.AddChild(_node69);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node69.HasEvents());
            Selector selector7 = new Selector();
            selector7.SetClassNameString("Selector");
            selector7.SetId(0x6c);
            sequence19.AddChild(selector7);
            Sequence sequence20 = new Sequence();
            sequence20.SetClassNameString("Sequence");
            sequence20.SetId(0x2a);
            selector7.AddChild(sequence20);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node114 _node70 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node114();
            _node70.SetClassNameString("Action");
            _node70.SetId(0x72);
            sequence20.AddChild(_node70);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node70.HasEvents());
            Selector selector8 = new Selector();
            selector8.SetClassNameString("Selector");
            selector8.SetId(0x2c);
            sequence20.AddChild(selector8);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node45 _node71 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node45();
            _node71.SetClassNameString("Condition");
            _node71.SetId(0x2d);
            selector8.AddChild(_node71);
            selector8.SetHasEvents(selector8.HasEvents() | _node71.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node46 _node72 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node46();
            _node72.SetClassNameString("Condition");
            _node72.SetId(0x2e);
            selector8.AddChild(_node72);
            selector8.SetHasEvents(selector8.HasEvents() | _node72.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node47 _node73 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node47();
            _node73.SetClassNameString("Condition");
            _node73.SetId(0x2f);
            selector8.AddChild(_node73);
            selector8.SetHasEvents(selector8.HasEvents() | _node73.HasEvents());
            sequence20.SetHasEvents(sequence20.HasEvents() | selector8.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node49 _node74 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node49();
            _node74.SetClassNameString("Condition");
            _node74.SetId(0x31);
            sequence20.AddChild(_node74);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node74.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node50 _node75 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node50();
            _node75.SetClassNameString("Action");
            _node75.SetId(50);
            sequence20.AddChild(_node75);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node75.HasEvents());
            selector7.SetHasEvents(selector7.HasEvents() | sequence20.HasEvents());
            Sequence sequence21 = new Sequence();
            sequence21.SetClassNameString("Sequence");
            sequence21.SetId(0x37);
            selector7.AddChild(sequence21);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node56 _node76 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node56();
            _node76.SetClassNameString("Condition");
            _node76.SetId(0x38);
            sequence21.AddChild(_node76);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node76.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node115 _node77 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node115();
            _node77.SetClassNameString("Assignment");
            _node77.SetId(0x73);
            sequence21.AddChild(_node77);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node77.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node117 _node78 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node117();
            _node78.SetClassNameString("Condition");
            _node78.SetId(0x75);
            sequence21.AddChild(_node78);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node78.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node119 _node79 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node119();
            _node79.SetClassNameString("Action");
            _node79.SetId(0x77);
            sequence21.AddChild(_node79);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node79.HasEvents());
            selector7.SetHasEvents(selector7.HasEvents() | sequence21.HasEvents());
            Sequence sequence22 = new Sequence();
            sequence22.SetClassNameString("Sequence");
            sequence22.SetId(0x7a);
            selector7.AddChild(sequence22);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node63 _node80 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node63();
            _node80.SetClassNameString("Condition");
            _node80.SetId(0x3f);
            sequence22.AddChild(_node80);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node80.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node66 _node81 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node66();
            _node81.SetClassNameString("Condition");
            _node81.SetId(0x42);
            sequence22.AddChild(_node81);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node81.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node67 _node82 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node67();
            _node82.SetClassNameString("Action");
            _node82.SetId(0x43);
            sequence22.AddChild(_node82);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node82.HasEvents());
            selector7.SetHasEvents(selector7.HasEvents() | sequence22.HasEvents());
            sequence19.SetHasEvents(sequence19.HasEvents() | selector7.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence19.HasEvents());
            Sequence sequence23 = new Sequence();
            sequence23.SetClassNameString("Sequence");
            sequence23.SetId(0x79);
            selector2.AddChild(sequence23);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node116 _node83 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node116();
            _node83.SetClassNameString("Action");
            _node83.SetId(0x74);
            sequence23.AddChild(_node83);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node83.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node123 _node84 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node123();
            _node84.SetClassNameString("Assignment");
            _node84.SetId(0x7b);
            sequence23.AddChild(_node84);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node84.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node124 _node85 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node124();
            _node85.SetClassNameString("Assignment");
            _node85.SetId(0x7c);
            sequence23.AddChild(_node85);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node85.HasEvents());
            Selector selector9 = new Selector();
            selector9.SetClassNameString("Selector");
            selector9.SetId(0x7d);
            sequence23.AddChild(selector9);
            Sequence sequence24 = new Sequence();
            sequence24.SetClassNameString("Sequence");
            sequence24.SetId(0x44);
            selector9.AddChild(sequence24);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node69 _node86 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node69();
            _node86.SetClassNameString("Action");
            _node86.SetId(0x45);
            sequence24.AddChild(_node86);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node86.HasEvents());
            Selector selector10 = new Selector();
            selector10.SetClassNameString("Selector");
            selector10.SetId(0x49);
            sequence24.AddChild(selector10);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node74 _node87 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node74();
            _node87.SetClassNameString("Condition");
            _node87.SetId(0x4a);
            selector10.AddChild(_node87);
            selector10.SetHasEvents(selector10.HasEvents() | _node87.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node76 _node88 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node76();
            _node88.SetClassNameString("Condition");
            _node88.SetId(0x4c);
            selector10.AddChild(_node88);
            selector10.SetHasEvents(selector10.HasEvents() | _node88.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node77 _node89 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node77();
            _node89.SetClassNameString("Condition");
            _node89.SetId(0x4d);
            selector10.AddChild(_node89);
            selector10.SetHasEvents(selector10.HasEvents() | _node89.HasEvents());
            sequence24.SetHasEvents(sequence24.HasEvents() | selector10.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node78 _node90 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node78();
            _node90.SetClassNameString("Condition");
            _node90.SetId(0x4e);
            sequence24.AddChild(_node90);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node90.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node79 _node91 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node79();
            _node91.SetClassNameString("Action");
            _node91.SetId(0x4f);
            sequence24.AddChild(_node91);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node91.HasEvents());
            selector9.SetHasEvents(selector9.HasEvents() | sequence24.HasEvents());
            Sequence sequence25 = new Sequence();
            sequence25.SetClassNameString("Sequence");
            sequence25.SetId(80);
            selector9.AddChild(sequence25);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node81 _node92 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node81();
            _node92.SetClassNameString("Condition");
            _node92.SetId(0x51);
            sequence25.AddChild(_node92);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node92.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node82 _node93 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node82();
            _node93.SetClassNameString("Assignment");
            _node93.SetId(0x52);
            sequence25.AddChild(_node93);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node93.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node83 _node94 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node83();
            _node94.SetClassNameString("Condition");
            _node94.SetId(0x53);
            sequence25.AddChild(_node94);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node94.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node84 _node95 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node84();
            _node95.SetClassNameString("Action");
            _node95.SetId(0x54);
            sequence25.AddChild(_node95);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node95.HasEvents());
            selector9.SetHasEvents(selector9.HasEvents() | sequence25.HasEvents());
            Sequence sequence26 = new Sequence();
            sequence26.SetClassNameString("Sequence");
            sequence26.SetId(0x7e);
            selector9.AddChild(sequence26);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node127 _node96 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node127();
            _node96.SetClassNameString("Condition");
            _node96.SetId(0x7f);
            sequence26.AddChild(_node96);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node96.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node129 _node97 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node129();
            _node97.SetClassNameString("Condition");
            _node97.SetId(0x81);
            sequence26.AddChild(_node97);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node97.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node130 _node98 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node130();
            _node98.SetClassNameString("Action");
            _node98.SetId(130);
            sequence26.AddChild(_node98);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node98.HasEvents());
            selector9.SetHasEvents(selector9.HasEvents() | sequence26.HasEvents());
            sequence23.SetHasEvents(sequence23.HasEvents() | selector9.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence23.HasEvents());
            IfElse else5 = new IfElse();
            else5.SetClassNameString("IfElse");
            else5.SetId(0x3a);
            selector2.AddChild(else5);
            Sequence sequence27 = new Sequence();
            sequence27.SetClassNameString("Sequence");
            sequence27.SetId(0x3e);
            else5.AddChild(sequence27);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node57 _node99 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node57();
            _node99.SetClassNameString("Condition");
            _node99.SetId(0x39);
            sequence27.AddChild(_node99);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node99.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node8 _node100 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node8();
            _node100.SetClassNameString("Action");
            _node100.SetId(8);
            sequence27.AddChild(_node100);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node100.HasEvents());
            else5.SetHasEvents(else5.HasEvents() | sequence27.HasEvents());
            Sequence sequence28 = new Sequence();
            sequence28.SetClassNameString("Sequence");
            sequence28.SetId(0x3b);
            else5.AddChild(sequence28);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node444 _node101 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node444();
            _node101.SetClassNameString("Action");
            _node101.SetId(0x1bc);
            sequence28.AddChild(_node101);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node101.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node201 _node102 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node201();
            _node102.SetClassNameString("Action");
            _node102.SetId(0xc9);
            sequence28.AddChild(_node102);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node102.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node241 _node103 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node241();
            _node103.SetClassNameString("Action");
            _node103.SetId(0xf1);
            sequence28.AddChild(_node103);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node103.HasEvents());
            else5.SetHasEvents(else5.HasEvents() | sequence28.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node7 _node104 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node7();
            _node104.SetClassNameString("Action");
            _node104.SetId(7);
            else5.AddChild(_node104);
            else5.SetHasEvents(else5.HasEvents() | _node104.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | else5.HasEvents());
            sequence10.SetHasEvents(sequence10.HasEvents() | selector2.HasEvents());
            Sequence sequence29 = new Sequence();
            sequence29.SetClassNameString("Sequence");
            sequence29.SetId(0xca);
            sequence10.AddChild(sequence29);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node85 _node105 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node85();
            _node105.SetClassNameString("Action");
            _node105.SetId(0x55);
            sequence29.AddChild(_node105);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node105.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node86 _node106 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node86();
            _node106.SetClassNameString("Action");
            _node106.SetId(0x56);
            sequence29.AddChild(_node106);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node106.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node87 _node107 = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node87();
            _node107.SetClassNameString("DecoratorLoopUntil");
            _node107.SetId(0x57);
            sequence29.AddChild(_node107);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node88 _node108 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node88();
            _node108.SetClassNameString("Condition");
            _node108.SetId(0x58);
            _node107.AddChild(_node108);
            _node107.SetHasEvents(_node107.HasEvents() | _node108.HasEvents());
            sequence29.SetHasEvents(sequence29.HasEvents() | _node107.HasEvents());
            sequence10.SetHasEvents(sequence10.HasEvents() | sequence29.HasEvents());
            else4.SetHasEvents(else4.HasEvents() | sequence10.HasEvents());
            Sequence sequence30 = new Sequence();
            sequence30.SetClassNameString("Sequence");
            sequence30.SetId(0xd0);
            else4.AddChild(sequence30);
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node229 _node109 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node229();
            _node109.SetClassNameString("Assignment");
            _node109.SetId(0xe5);
            sequence30.AddChild(_node109);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node109.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node463 _node110 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node463();
            _node110.SetClassNameString("Action");
            _node110.SetId(0x1cf);
            sequence30.AddChild(_node110);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node110.HasEvents());
            Sequence sequence31 = new Sequence();
            sequence31.SetClassNameString("Sequence");
            sequence31.SetId(0xdd);
            sequence30.AddChild(sequence31);
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node222 _node111 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node222();
            _node111.SetClassNameString("Assignment");
            _node111.SetId(0xde);
            sequence31.AddChild(_node111);
            sequence31.SetHasEvents(sequence31.HasEvents() | _node111.HasEvents());
            Selector selector11 = new Selector();
            selector11.SetClassNameString("Selector");
            selector11.SetId(0xee);
            sequence31.AddChild(selector11);
            Sequence sequence32 = new Sequence();
            sequence32.SetClassNameString("Sequence");
            sequence32.SetId(0xef);
            selector11.AddChild(sequence32);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node382 _node112 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node382();
            _node112.SetClassNameString("Condition");
            _node112.SetId(0x17e);
            sequence32.AddChild(_node112);
            sequence32.SetHasEvents(sequence32.HasEvents() | _node112.HasEvents());
            Sequence sequence33 = new Sequence();
            sequence33.SetClassNameString("Sequence");
            sequence33.SetId(0x17f);
            sequence32.AddChild(sequence33);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node489 _node113 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node489();
            _node113.SetClassNameString("Action");
            _node113.SetId(0x1e9);
            sequence33.AddChild(_node113);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node113.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node410 _node114 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node410();
            _node114.SetClassNameString("Action");
            _node114.SetId(410);
            sequence33.AddChild(_node114);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node114.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node18 _node115 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node18();
            _node115.SetClassNameString("Action");
            _node115.SetId(0x12);
            sequence33.AddChild(_node115);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node115.HasEvents());
            sequence32.SetHasEvents(sequence32.HasEvents() | sequence33.HasEvents());
            selector11.SetHasEvents(selector11.HasEvents() | sequence32.HasEvents());
            Sequence sequence34 = new Sequence();
            sequence34.SetClassNameString("Sequence");
            sequence34.SetId(240);
            selector11.AddChild(sequence34);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node89 _node116 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node89();
            _node116.SetClassNameString("Condition");
            _node116.SetId(0x59);
            sequence34.AddChild(_node116);
            sequence34.SetHasEvents(sequence34.HasEvents() | _node116.HasEvents());
            Sequence sequence35 = new Sequence();
            sequence35.SetClassNameString("Sequence");
            sequence35.SetId(0xe4);
            sequence34.AddChild(sequence35);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node90 _node117 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node90();
            _node117.SetClassNameString("Action");
            _node117.SetId(90);
            sequence35.AddChild(_node117);
            sequence35.SetHasEvents(sequence35.HasEvents() | _node117.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node230 _node118 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node230();
            _node118.SetClassNameString("Action");
            _node118.SetId(230);
            sequence35.AddChild(_node118);
            sequence35.SetHasEvents(sequence35.HasEvents() | _node118.HasEvents());
            sequence34.SetHasEvents(sequence34.HasEvents() | sequence35.HasEvents());
            selector11.SetHasEvents(selector11.HasEvents() | sequence34.HasEvents());
            Sequence sequence36 = new Sequence();
            sequence36.SetClassNameString("Sequence");
            sequence36.SetId(0x11a);
            selector11.AddChild(sequence36);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node283 _node119 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node283();
            _node119.SetClassNameString("Condition");
            _node119.SetId(0x11b);
            sequence36.AddChild(_node119);
            sequence36.SetHasEvents(sequence36.HasEvents() | _node119.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node120 _node120 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node120();
            _node120.SetClassNameString("Action");
            _node120.SetId(120);
            sequence36.AddChild(_node120);
            sequence36.SetHasEvents(sequence36.HasEvents() | _node120.HasEvents());
            selector11.SetHasEvents(selector11.HasEvents() | sequence36.HasEvents());
            sequence31.SetHasEvents(sequence31.HasEvents() | selector11.HasEvents());
            sequence30.SetHasEvents(sequence30.HasEvents() | sequence31.HasEvents());
            else4.SetHasEvents(else4.HasEvents() | sequence30.HasEvents());
            sequence8.SetHasEvents(sequence8.HasEvents() | else4.HasEvents());
            precondition4.SetHasEvents(precondition4.HasEvents() | sequence8.HasEvents());
            loop2.SetHasEvents(loop2.HasEvents() | precondition4.HasEvents());
            precondition2.SetHasEvents(precondition2.HasEvents() | loop2.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition2.HasEvents());
            WithPrecondition precondition5 = new WithPrecondition();
            precondition5.SetClassNameString("WithPrecondition");
            precondition5.SetId(0x203);
            loop.AddChild(precondition5);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node516 _node121 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node516();
            _node121.SetClassNameString("Condition");
            _node121.SetId(0x204);
            precondition5.AddChild(_node121);
            precondition5.SetHasEvents(precondition5.HasEvents() | _node121.HasEvents());
            Selector selector12 = new Selector();
            selector12.SetClassNameString("Selector");
            selector12.SetId(0x5b);
            precondition5.AddChild(selector12);
            Sequence sequence37 = new Sequence();
            sequence37.SetClassNameString("Sequence");
            sequence37.SetId(0x5c);
            selector12.AddChild(sequence37);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node93 _node122 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node93();
            _node122.SetClassNameString("Condition");
            _node122.SetId(0x5d);
            sequence37.AddChild(_node122);
            sequence37.SetHasEvents(sequence37.HasEvents() | _node122.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node95 _node123 = new Assignment_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node95();
            _node123.SetClassNameString("Assignment");
            _node123.SetId(0x5f);
            sequence37.AddChild(_node123);
            sequence37.SetHasEvents(sequence37.HasEvents() | _node123.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node96 _node124 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node96();
            _node124.SetClassNameString("Action");
            _node124.SetId(0x60);
            sequence37.AddChild(_node124);
            sequence37.SetHasEvents(sequence37.HasEvents() | _node124.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node97 _node125 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node97();
            _node125.SetClassNameString("Action");
            _node125.SetId(0x61);
            sequence37.AddChild(_node125);
            sequence37.SetHasEvents(sequence37.HasEvents() | _node125.HasEvents());
            selector12.SetHasEvents(selector12.HasEvents() | sequence37.HasEvents());
            Sequence sequence38 = new Sequence();
            sequence38.SetClassNameString("Sequence");
            sequence38.SetId(0x205);
            selector12.AddChild(sequence38);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node99 _node126 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node99();
            _node126.SetClassNameString("Condition");
            _node126.SetId(0x63);
            sequence38.AddChild(_node126);
            sequence38.SetHasEvents(sequence38.HasEvents() | _node126.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node518 _node127 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node518();
            _node127.SetClassNameString("Action");
            _node127.SetId(0x206);
            sequence38.AddChild(_node127);
            sequence38.SetHasEvents(sequence38.HasEvents() | _node127.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node519 _node128 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node519();
            _node128.SetClassNameString("Action");
            _node128.SetId(0x207);
            sequence38.AddChild(_node128);
            sequence38.SetHasEvents(sequence38.HasEvents() | _node128.HasEvents());
            IfElse else6 = new IfElse();
            else6.SetClassNameString("IfElse");
            else6.SetId(520);
            sequence38.AddChild(else6);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node521 _node129 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node521();
            _node129.SetClassNameString("Condition");
            _node129.SetId(0x209);
            else6.AddChild(_node129);
            else6.SetHasEvents(else6.HasEvents() | _node129.HasEvents());
            Sequence sequence39 = new Sequence();
            sequence39.SetClassNameString("Sequence");
            sequence39.SetId(0x20a);
            else6.AddChild(sequence39);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node523 _node130 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node523();
            _node130.SetClassNameString("Action");
            _node130.SetId(0x20b);
            sequence39.AddChild(_node130);
            sequence39.SetHasEvents(sequence39.HasEvents() | _node130.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node524 _node131 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node524();
            _node131.SetClassNameString("Action");
            _node131.SetId(0x20c);
            sequence39.AddChild(_node131);
            sequence39.SetHasEvents(sequence39.HasEvents() | _node131.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node526 _node132 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node526();
            _node132.SetClassNameString("Action");
            _node132.SetId(0x20e);
            sequence39.AddChild(_node132);
            sequence39.SetHasEvents(sequence39.HasEvents() | _node132.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node100 _node133 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node100();
            _node133.SetClassNameString("Action");
            _node133.SetId(100);
            sequence39.AddChild(_node133);
            sequence39.SetHasEvents(sequence39.HasEvents() | _node133.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node530 _node134 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node530();
            _node134.SetClassNameString("Action");
            _node134.SetId(530);
            sequence39.AddChild(_node134);
            sequence39.SetHasEvents(sequence39.HasEvents() | _node134.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node531 _node135 = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node531();
            _node135.SetClassNameString("DecoratorLoopUntil");
            _node135.SetId(0x213);
            sequence39.AddChild(_node135);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node532 _node136 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node532();
            _node136.SetClassNameString("Condition");
            _node136.SetId(0x214);
            _node135.AddChild(_node136);
            _node135.SetHasEvents(_node135.HasEvents() | _node136.HasEvents());
            sequence39.SetHasEvents(sequence39.HasEvents() | _node135.HasEvents());
            else6.SetHasEvents(else6.HasEvents() | sequence39.HasEvents());
            Sequence sequence40 = new Sequence();
            sequence40.SetClassNameString("Sequence");
            sequence40.SetId(0x215);
            else6.AddChild(sequence40);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node101 _node137 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node101();
            _node137.SetClassNameString("Action");
            _node137.SetId(0x65);
            sequence40.AddChild(_node137);
            sequence40.SetHasEvents(sequence40.HasEvents() | _node137.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node535 _node138 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node535();
            _node138.SetClassNameString("Action");
            _node138.SetId(0x217);
            sequence40.AddChild(_node138);
            sequence40.SetHasEvents(sequence40.HasEvents() | _node138.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node536 _node139 = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node536();
            _node139.SetClassNameString("DecoratorLoopUntil");
            _node139.SetId(0x218);
            sequence40.AddChild(_node139);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node537 _node140 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node537();
            _node140.SetClassNameString("Condition");
            _node140.SetId(0x219);
            _node139.AddChild(_node140);
            _node139.SetHasEvents(_node139.HasEvents() | _node140.HasEvents());
            sequence40.SetHasEvents(sequence40.HasEvents() | _node139.HasEvents());
            else6.SetHasEvents(else6.HasEvents() | sequence40.HasEvents());
            sequence38.SetHasEvents(sequence38.HasEvents() | else6.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node538 _node141 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node538();
            _node141.SetClassNameString("Action");
            _node141.SetId(0x21a);
            sequence38.AddChild(_node141);
            sequence38.SetHasEvents(sequence38.HasEvents() | _node141.HasEvents());
            selector12.SetHasEvents(selector12.HasEvents() | sequence38.HasEvents());
            precondition5.SetHasEvents(precondition5.HasEvents() | selector12.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition5.HasEvents());
            WithPrecondition precondition6 = new WithPrecondition();
            precondition6.SetClassNameString("WithPrecondition");
            precondition6.SetId(0xa3);
            loop.AddChild(precondition6);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node164 _node142 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node164();
            _node142.SetClassNameString("Condition");
            _node142.SetId(0xa4);
            precondition6.AddChild(_node142);
            precondition6.SetHasEvents(precondition6.HasEvents() | _node142.HasEvents());
            Sequence sequence41 = new Sequence();
            sequence41.SetClassNameString("Sequence");
            sequence41.SetId(0xa5);
            precondition6.AddChild(sequence41);
            Selector selector13 = new Selector();
            selector13.SetClassNameString("Selector");
            selector13.SetId(0x1e7);
            sequence41.AddChild(selector13);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node488 _node143 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node488();
            _node143.SetClassNameString("Action");
            _node143.SetId(0x1e8);
            selector13.AddChild(_node143);
            selector13.SetHasEvents(selector13.HasEvents() | _node143.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node166 _node144 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node166();
            _node144.SetClassNameString("Action");
            _node144.SetId(0xa6);
            selector13.AddChild(_node144);
            selector13.SetHasEvents(selector13.HasEvents() | _node144.HasEvents());
            sequence41.SetHasEvents(sequence41.HasEvents() | selector13.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node167 _node145 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node167();
            _node145.SetClassNameString("DecoratorLoop");
            _node145.SetId(0xa7);
            sequence41.AddChild(_node145);
            Noop noop3 = new Noop();
            noop3.SetClassNameString("Noop");
            noop3.SetId(0xa8);
            _node145.AddChild(noop3);
            _node145.SetHasEvents(_node145.HasEvents() | noop3.HasEvents());
            sequence41.SetHasEvents(sequence41.HasEvents() | _node145.HasEvents());
            precondition6.SetHasEvents(precondition6.HasEvents() | sequence41.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition6.HasEvents());
            WithPrecondition precondition7 = new WithPrecondition();
            precondition7.SetClassNameString("WithPrecondition");
            precondition7.SetId(0x23);
            loop.AddChild(precondition7);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node40 _node146 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node40();
            _node146.SetClassNameString("Condition");
            _node146.SetId(40);
            precondition7.AddChild(_node146);
            precondition7.SetHasEvents(precondition7.HasEvents() | _node146.HasEvents());
            Sequence sequence42 = new Sequence();
            sequence42.SetClassNameString("Sequence");
            sequence42.SetId(0x29);
            precondition7.AddChild(sequence42);
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node43 _node147 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node43();
            _node147.SetClassNameString("DecoratorLoop");
            _node147.SetId(0x2b);
            sequence42.AddChild(_node147);
            Noop noop4 = new Noop();
            noop4.SetClassNameString("Noop");
            noop4.SetId(0x1ca);
            _node147.AddChild(noop4);
            _node147.SetHasEvents(_node147.HasEvents() | noop4.HasEvents());
            sequence42.SetHasEvents(sequence42.HasEvents() | _node147.HasEvents());
            precondition7.SetHasEvents(precondition7.HasEvents() | sequence42.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition7.HasEvents());
            WithPrecondition precondition8 = new WithPrecondition();
            precondition8.SetClassNameString("WithPrecondition");
            precondition8.SetId(450);
            loop.AddChild(precondition8);
            Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node454 _node148 = new Condition_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node454();
            _node148.SetClassNameString("Condition");
            _node148.SetId(0x1c6);
            precondition8.AddChild(_node148);
            precondition8.SetHasEvents(precondition8.HasEvents() | _node148.HasEvents());
            Sequence sequence43 = new Sequence();
            sequence43.SetClassNameString("Sequence");
            sequence43.SetId(0x1c7);
            precondition8.AddChild(sequence43);
            Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node456 _node149 = new Action_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node456();
            _node149.SetClassNameString("Action");
            _node149.SetId(0x1c8);
            sequence43.AddChild(_node149);
            sequence43.SetHasEvents(sequence43.HasEvents() | _node149.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node457 _node150 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterZhaoHuanWu_node457();
            _node150.SetClassNameString("DecoratorLoop");
            _node150.SetId(0x1c9);
            sequence43.AddChild(_node150);
            Noop noop5 = new Noop();
            noop5.SetClassNameString("Noop");
            noop5.SetId(0x66);
            _node150.AddChild(noop5);
            _node150.SetHasEvents(_node150.HasEvents() | noop5.HasEvents());
            sequence43.SetHasEvents(sequence43.HasEvents() | _node150.HasEvents());
            precondition8.SetHasEvents(precondition8.HasEvents() | sequence43.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition8.HasEvents());
            _node5.SetHasEvents(_node5.HasEvents() | loop.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | _node5.HasEvents());
            bt.SetHasEvents(bt.HasEvents() | pChild.HasEvents());
            return true;
        }
    }
}

