namespace behaviac
{
    using System;

    public static class bt_WrapperAI_Monster_BTMonsterPassiveThief
    {
        public static bool build_behavior_tree(BehaviorTree bt)
        {
            bt.SetClassNameString("BehaviorTree");
            bt.SetId(-1);
            bt.SetName("WrapperAI/Monster/BTMonsterPassiveThief");
            bt.AddPar("uint", "p_targetID", "0", string.Empty);
            bt.AddPar("int", "p_srchRange", "0", string.Empty);
            bt.AddPar("uint", "p_selfID", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_randomPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            Sequence pChild = new Sequence();
            pChild.SetClassNameString("Sequence");
            pChild.SetId(0);
            bt.AddChild(pChild);
            Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node98 _node = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node98();
            _node.SetClassNameString("Assignment");
            _node.SetId(0x62);
            pChild.AddChild(_node);
            pChild.SetHasEvents(pChild.HasEvents() | _node.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node48 _node2 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node48();
            _node2.SetClassNameString("Assignment");
            _node2.SetId(0x30);
            pChild.AddChild(_node2);
            pChild.SetHasEvents(pChild.HasEvents() | _node2.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node11 _node3 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node11();
            _node3.SetClassNameString("Assignment");
            _node3.SetId(11);
            pChild.AddChild(_node3);
            pChild.SetHasEvents(pChild.HasEvents() | _node3.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node14 _node4 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node14();
            _node4.SetClassNameString("DecoratorLoop");
            _node4.SetId(14);
            pChild.AddChild(_node4);
            SelectorLoop loop = new SelectorLoop();
            loop.SetClassNameString("SelectorLoop");
            loop.SetId(1);
            _node4.AddChild(loop);
            WithPrecondition precondition = new WithPrecondition();
            precondition.SetClassNameString("WithPrecondition");
            precondition.SetId(60);
            loop.AddChild(precondition);
            Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node61 _node5 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node61();
            _node5.SetClassNameString("Condition");
            _node5.SetId(0x3d);
            precondition.AddChild(_node5);
            precondition.SetHasEvents(precondition.HasEvents() | _node5.HasEvents());
            IfElse @else = new IfElse();
            @else.SetClassNameString("IfElse");
            @else.SetId(0xf5);
            precondition.AddChild(@else);
            Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node246 _node6 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node246();
            _node6.SetClassNameString("Condition");
            _node6.SetId(0xf6);
            @else.AddChild(_node6);
            @else.SetHasEvents(@else.HasEvents() | _node6.HasEvents());
            IfElse else2 = new IfElse();
            else2.SetClassNameString("IfElse");
            else2.SetId(0x1b);
            @else.AddChild(else2);
            Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node28 _node7 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node28();
            _node7.SetClassNameString("Condition");
            _node7.SetId(0x1c);
            else2.AddChild(_node7);
            else2.SetHasEvents(else2.HasEvents() | _node7.HasEvents());
            Sequence sequence2 = new Sequence();
            sequence2.SetClassNameString("Sequence");
            sequence2.SetId(0xf7);
            else2.AddChild(sequence2);
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node248 _node8 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node248();
            _node8.SetClassNameString("Action");
            _node8.SetId(0xf8);
            sequence2.AddChild(_node8);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node8.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node66 _node9 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node66();
            _node9.SetClassNameString("DecoratorLoop");
            _node9.SetId(0x42);
            sequence2.AddChild(_node9);
            Sequence sequence3 = new Sequence();
            sequence3.SetClassNameString("Sequence");
            sequence3.SetId(7);
            _node9.AddChild(sequence3);
            Selector selector = new Selector();
            selector.SetClassNameString("Selector");
            selector.SetId(15);
            sequence3.AddChild(selector);
            Sequence sequence4 = new Sequence();
            sequence4.SetClassNameString("Sequence");
            sequence4.SetId(0x11);
            selector.AddChild(sequence4);
            Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node30 _node10 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node30();
            _node10.SetClassNameString("Assignment");
            _node10.SetId(30);
            sequence4.AddChild(_node10);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node10.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node18 _node11 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node18();
            _node11.SetClassNameString("Assignment");
            _node11.SetId(0x12);
            sequence4.AddChild(_node11);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node11.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node20 _node12 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node20();
            _node12.SetClassNameString("Condition");
            _node12.SetId(20);
            sequence4.AddChild(_node12);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node12.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node26 _node13 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node26();
            _node13.SetClassNameString("Action");
            _node13.SetId(0x1a);
            sequence4.AddChild(_node13);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node13.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node21 _node14 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node21();
            _node14.SetClassNameString("Action");
            _node14.SetId(0x15);
            sequence4.AddChild(_node14);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node14.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence4.HasEvents());
            Sequence sequence5 = new Sequence();
            sequence5.SetClassNameString("Sequence");
            sequence5.SetId(0x44);
            selector.AddChild(sequence5);
            Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node69 _node15 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node69();
            _node15.SetClassNameString("Condition");
            _node15.SetId(0x45);
            sequence5.AddChild(_node15);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node15.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node231 _node16 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node231();
            _node16.SetClassNameString("Action");
            _node16.SetId(0xe7);
            sequence5.AddChild(_node16);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node16.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node232 _node17 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node232();
            _node17.SetClassNameString("Action");
            _node17.SetId(0xe8);
            sequence5.AddChild(_node17);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node17.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node233 _node18 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node233();
            _node18.SetClassNameString("Action");
            _node18.SetId(0xe9);
            sequence5.AddChild(_node18);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node18.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node234 _node19 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node234();
            _node19.SetClassNameString("Assignment");
            _node19.SetId(0xea);
            sequence5.AddChild(_node19);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node19.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node32 _node20 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node32();
            _node20.SetClassNameString("Action");
            _node20.SetId(0x20);
            sequence5.AddChild(_node20);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node20.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node13 _node21 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node13();
            _node21.SetClassNameString("Action");
            _node21.SetId(13);
            sequence5.AddChild(_node21);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node21.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence5.HasEvents());
            sequence3.SetHasEvents(sequence3.HasEvents() | selector.HasEvents());
            WaitFrames_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8 _node22 = new WaitFrames_bt_WrapperAI_Monster_BTMonsterPassiveThief_node8();
            _node22.SetClassNameString("WaitFrames");
            _node22.SetId(8);
            sequence3.AddChild(_node22);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node22.HasEvents());
            _node9.SetHasEvents(_node9.HasEvents() | sequence3.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | _node9.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | sequence2.HasEvents());
            Noop noop = new Noop();
            noop.SetClassNameString("Noop");
            noop.SetId(0x1d);
            else2.AddChild(noop);
            else2.SetHasEvents(else2.HasEvents() | noop.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | else2.HasEvents());
            Sequence sequence6 = new Sequence();
            sequence6.SetClassNameString("Sequence");
            sequence6.SetId(0xff);
            @else.AddChild(sequence6);
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node19 _node23 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node19();
            _node23.SetClassNameString("Action");
            _node23.SetId(0x13);
            sequence6.AddChild(_node23);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node23.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node256 _node24 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node256();
            _node24.SetClassNameString("Action");
            _node24.SetId(0x100);
            sequence6.AddChild(_node24);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node24.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node257 _node25 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node257();
            _node25.SetClassNameString("Action");
            _node25.SetId(0x101);
            sequence6.AddChild(_node25);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node25.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | sequence6.HasEvents());
            precondition.SetHasEvents(precondition.HasEvents() | @else.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition.HasEvents());
            WithPrecondition precondition2 = new WithPrecondition();
            precondition2.SetClassNameString("WithPrecondition");
            precondition2.SetId(70);
            loop.AddChild(precondition2);
            Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node71 _node26 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node71();
            _node26.SetClassNameString("Condition");
            _node26.SetId(0x47);
            precondition2.AddChild(_node26);
            precondition2.SetHasEvents(precondition2.HasEvents() | _node26.HasEvents());
            Sequence sequence7 = new Sequence();
            sequence7.SetClassNameString("Sequence");
            sequence7.SetId(12);
            precondition2.AddChild(sequence7);
            Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node16 _node27 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node16();
            _node27.SetClassNameString("Assignment");
            _node27.SetId(0x10);
            sequence7.AddChild(_node27);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node27.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node224 _node28 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node224();
            _node28.SetClassNameString("Action");
            _node28.SetId(0xe0);
            sequence7.AddChild(_node28);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node28.HasEvents());
            precondition2.SetHasEvents(precondition2.HasEvents() | sequence7.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition2.HasEvents());
            WithPrecondition precondition3 = new WithPrecondition();
            precondition3.SetClassNameString("WithPrecondition");
            precondition3.SetId(0x203);
            loop.AddChild(precondition3);
            Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node516 _node29 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node516();
            _node29.SetClassNameString("Condition");
            _node29.SetId(0x204);
            precondition3.AddChild(_node29);
            precondition3.SetHasEvents(precondition3.HasEvents() | _node29.HasEvents());
            Sequence sequence8 = new Sequence();
            sequence8.SetClassNameString("Sequence");
            sequence8.SetId(0x205);
            precondition3.AddChild(sequence8);
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node518 _node30 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node518();
            _node30.SetClassNameString("Action");
            _node30.SetId(0x206);
            sequence8.AddChild(_node30);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node30.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9 _node31 = new Assignment_bt_WrapperAI_Monster_BTMonsterPassiveThief_node9();
            _node31.SetClassNameString("Assignment");
            _node31.SetId(9);
            sequence8.AddChild(_node31);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node31.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10 _node32 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node10();
            _node32.SetClassNameString("Action");
            _node32.SetId(10);
            sequence8.AddChild(_node32);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node32.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node538 _node33 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node538();
            _node33.SetClassNameString("Action");
            _node33.SetId(0x21a);
            sequence8.AddChild(_node33);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node33.HasEvents());
            precondition3.SetHasEvents(precondition3.HasEvents() | sequence8.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition3.HasEvents());
            WithPrecondition precondition4 = new WithPrecondition();
            precondition4.SetClassNameString("WithPrecondition");
            precondition4.SetId(0x18);
            loop.AddChild(precondition4);
            Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node25 _node34 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node25();
            _node34.SetClassNameString("Condition");
            _node34.SetId(0x19);
            precondition4.AddChild(_node34);
            precondition4.SetHasEvents(precondition4.HasEvents() | _node34.HasEvents());
            Sequence sequence9 = new Sequence();
            sequence9.SetClassNameString("Sequence");
            sequence9.SetId(0x3b);
            precondition4.AddChild(sequence9);
            Selector selector2 = new Selector();
            selector2.SetClassNameString("Selector");
            selector2.SetId(0x1e7);
            sequence9.AddChild(selector2);
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node488 _node35 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node488();
            _node35.SetClassNameString("Action");
            _node35.SetId(0x1e8);
            selector2.AddChild(_node35);
            selector2.SetHasEvents(selector2.HasEvents() | _node35.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node31 _node36 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node31();
            _node36.SetClassNameString("Action");
            _node36.SetId(0x1f);
            selector2.AddChild(_node36);
            selector2.SetHasEvents(selector2.HasEvents() | _node36.HasEvents());
            sequence9.SetHasEvents(sequence9.HasEvents() | selector2.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node65 _node37 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node65();
            _node37.SetClassNameString("DecoratorLoop");
            _node37.SetId(0x41);
            sequence9.AddChild(_node37);
            Noop noop2 = new Noop();
            noop2.SetClassNameString("Noop");
            noop2.SetId(0x21);
            _node37.AddChild(noop2);
            _node37.SetHasEvents(_node37.HasEvents() | noop2.HasEvents());
            sequence9.SetHasEvents(sequence9.HasEvents() | _node37.HasEvents());
            precondition4.SetHasEvents(precondition4.HasEvents() | sequence9.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition4.HasEvents());
            WithPrecondition precondition5 = new WithPrecondition();
            precondition5.SetClassNameString("WithPrecondition");
            precondition5.SetId(0x22);
            loop.AddChild(precondition5);
            Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node40 _node38 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node40();
            _node38.SetClassNameString("Condition");
            _node38.SetId(40);
            precondition5.AddChild(_node38);
            precondition5.SetHasEvents(precondition5.HasEvents() | _node38.HasEvents());
            Sequence sequence10 = new Sequence();
            sequence10.SetClassNameString("Sequence");
            sequence10.SetId(0x29);
            precondition5.AddChild(sequence10);
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node42 _node39 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node42();
            _node39.SetClassNameString("Action");
            _node39.SetId(0x2a);
            sequence10.AddChild(_node39);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node39.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node43 _node40 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node43();
            _node40.SetClassNameString("DecoratorLoop");
            _node40.SetId(0x2b);
            sequence10.AddChild(_node40);
            Noop noop3 = new Noop();
            noop3.SetClassNameString("Noop");
            noop3.SetId(0x1ca);
            _node40.AddChild(noop3);
            _node40.SetHasEvents(_node40.HasEvents() | noop3.HasEvents());
            sequence10.SetHasEvents(sequence10.HasEvents() | _node40.HasEvents());
            precondition5.SetHasEvents(precondition5.HasEvents() | sequence10.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition5.HasEvents());
            WithPrecondition precondition6 = new WithPrecondition();
            precondition6.SetClassNameString("WithPrecondition");
            precondition6.SetId(450);
            loop.AddChild(precondition6);
            Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node454 _node41 = new Condition_bt_WrapperAI_Monster_BTMonsterPassiveThief_node454();
            _node41.SetClassNameString("Condition");
            _node41.SetId(0x1c6);
            precondition6.AddChild(_node41);
            precondition6.SetHasEvents(precondition6.HasEvents() | _node41.HasEvents());
            Sequence sequence11 = new Sequence();
            sequence11.SetClassNameString("Sequence");
            sequence11.SetId(0x1c7);
            precondition6.AddChild(sequence11);
            Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node456 _node42 = new Action_bt_WrapperAI_Monster_BTMonsterPassiveThief_node456();
            _node42.SetClassNameString("Action");
            _node42.SetId(0x1c8);
            sequence11.AddChild(_node42);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node42.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node457 _node43 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterPassiveThief_node457();
            _node43.SetClassNameString("DecoratorLoop");
            _node43.SetId(0x1c9);
            sequence11.AddChild(_node43);
            Noop noop4 = new Noop();
            noop4.SetClassNameString("Noop");
            noop4.SetId(2);
            _node43.AddChild(noop4);
            _node43.SetHasEvents(_node43.HasEvents() | noop4.HasEvents());
            sequence11.SetHasEvents(sequence11.HasEvents() | _node43.HasEvents());
            precondition6.SetHasEvents(precondition6.HasEvents() | sequence11.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition6.HasEvents());
            _node4.SetHasEvents(_node4.HasEvents() | loop.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | _node4.HasEvents());
            bt.SetHasEvents(bt.HasEvents() | pChild.HasEvents());
            return true;
        }
    }
}

