namespace behaviac
{
    using System;

    public static class bt_WrapperAI_Soldier_BTSoldierNormal
    {
        public static bool build_behavior_tree(BehaviorTree bt)
        {
            bt.SetClassNameString("BehaviorTree");
            bt.SetId(-1);
            bt.SetName("WrapperAI/Soldier/BTSoldierNormal");
            bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
            bt.AddPar("uint", "p_targetID", "0", string.Empty);
            bt.AddPar("int", "p_srchRange", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
            bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
            bt.AddPar("uint", "p_CmdID", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_pursueTime", "0", string.Empty);
            bt.AddPar("uint", "p_abandonTargetID", "0", string.Empty);
            Sequence pChild = new Sequence();
            pChild.SetClassNameString("Sequence");
            pChild.SetId(0);
            bt.AddChild(pChild);
            Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node106 _node = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node106();
            _node.SetClassNameString("Assignment");
            _node.SetId(0x6a);
            pChild.AddChild(_node);
            pChild.SetHasEvents(pChild.HasEvents() | _node.HasEvents());
            DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node14 _node2 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node14();
            _node2.SetClassNameString("DecoratorLoop");
            _node2.SetId(14);
            pChild.AddChild(_node2);
            SelectorLoop loop = new SelectorLoop();
            loop.SetClassNameString("SelectorLoop");
            loop.SetId(1);
            _node2.AddChild(loop);
            WithPrecondition precondition = new WithPrecondition();
            precondition.SetClassNameString("WithPrecondition");
            precondition.SetId(0x3b);
            loop.AddChild(precondition);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node78 _node3 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node78();
            _node3.SetClassNameString("Condition");
            _node3.SetId(0x4e);
            precondition.AddChild(_node3);
            precondition.SetHasEvents(precondition.HasEvents() | _node3.HasEvents());
            Sequence sequence2 = new Sequence();
            sequence2.SetClassNameString("Sequence");
            sequence2.SetId(0x69);
            precondition.AddChild(sequence2);
            IfElse @else = new IfElse();
            @else.SetClassNameString("IfElse");
            @else.SetId(0x21);
            sequence2.AddChild(@else);
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node29 _node4 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node29();
            _node4.SetClassNameString("Action");
            _node4.SetId(0x1d);
            @else.AddChild(_node4);
            @else.SetHasEvents(@else.HasEvents() | _node4.HasEvents());
            Sequence sequence3 = new Sequence();
            sequence3.SetClassNameString("Sequence");
            sequence3.SetId(0x1f);
            @else.AddChild(sequence3);
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node30 _node5 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node30();
            _node5.SetClassNameString("Action");
            _node5.SetId(30);
            sequence3.AddChild(_node5);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node5.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node32 _node6 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node32();
            _node6.SetClassNameString("Assignment");
            _node6.SetId(0x20);
            sequence3.AddChild(_node6);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node6.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | sequence3.HasEvents());
            Noop noop = new Noop();
            noop.SetClassNameString("Noop");
            noop.SetId(0x22);
            @else.AddChild(noop);
            @else.SetHasEvents(@else.HasEvents() | noop.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | @else.HasEvents());
            IfElse else2 = new IfElse();
            else2.SetClassNameString("IfElse");
            else2.SetId(10);
            sequence2.AddChild(else2);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node11 _node7 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node11();
            _node7.SetClassNameString("Condition");
            _node7.SetId(11);
            else2.AddChild(_node7);
            else2.SetHasEvents(else2.HasEvents() | _node7.HasEvents());
            Noop noop2 = new Noop();
            noop2.SetClassNameString("Noop");
            noop2.SetId(12);
            else2.AddChild(noop2);
            else2.SetHasEvents(else2.HasEvents() | noop2.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node107 _node8 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node107();
            _node8.SetClassNameString("Assignment");
            _node8.SetId(0x6b);
            else2.AddChild(_node8);
            else2.SetHasEvents(else2.HasEvents() | _node8.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | else2.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node26 _node9 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node26();
            _node9.SetClassNameString("Assignment");
            _node9.SetId(0x1a);
            sequence2.AddChild(_node9);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node9.HasEvents());
            Parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node2 _node10 = new Parallel_bt_WrapperAI_Soldier_BTSoldierNormal_node2();
            _node10.SetClassNameString("Parallel");
            _node10.SetId(2);
            sequence2.AddChild(_node10);
            Sequence sequence4 = new Sequence();
            sequence4.SetClassNameString("Sequence");
            sequence4.SetId(3);
            _node10.AddChild(sequence4);
            IfElse else3 = new IfElse();
            else3.SetClassNameString("IfElse");
            else3.SetId(0x24);
            sequence4.AddChild(else3);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node4 _node11 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node4();
            _node11.SetClassNameString("Condition");
            _node11.SetId(4);
            else3.AddChild(_node11);
            else3.SetHasEvents(else3.HasEvents() | _node11.HasEvents());
            True @true = new True();
            @true.SetClassNameString("True");
            @true.SetId(0x27);
            else3.AddChild(@true);
            else3.SetHasEvents(else3.HasEvents() | @true.HasEvents());
            DecoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node37 _node12 = new DecoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node37();
            _node12.SetClassNameString("DecoratorAlwaysFailure");
            _node12.SetId(0x25);
            else3.AddChild(_node12);
            Sequence sequence5 = new Sequence();
            sequence5.SetClassNameString("Sequence");
            sequence5.SetId(0x29);
            _node12.AddChild(sequence5);
            Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node38 _node13 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node38();
            _node13.SetClassNameString("Assignment");
            _node13.SetId(0x26);
            sequence5.AddChild(_node13);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node13.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node42 _node14 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node42();
            _node14.SetClassNameString("Assignment");
            _node14.SetId(0x2a);
            sequence5.AddChild(_node14);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node14.HasEvents());
            _node12.SetHasEvents(_node12.HasEvents() | sequence5.HasEvents());
            else3.SetHasEvents(else3.HasEvents() | _node12.HasEvents());
            sequence4.SetHasEvents(sequence4.HasEvents() | else3.HasEvents());
            Compute_bt_WrapperAI_Soldier_BTSoldierNormal_node20 _node15 = new Compute_bt_WrapperAI_Soldier_BTSoldierNormal_node20();
            _node15.SetClassNameString("Compute");
            _node15.SetId(20);
            sequence4.AddChild(_node15);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node15.HasEvents());
            _node10.SetHasEvents(_node10.HasEvents() | sequence4.HasEvents());
            IfElse else4 = new IfElse();
            else4.SetClassNameString("IfElse");
            else4.SetId(0x6c);
            _node10.AddChild(else4);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node109 _node16 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node109();
            _node16.SetClassNameString("Condition");
            _node16.SetId(0x6d);
            else4.AddChild(_node16);
            else4.SetHasEvents(else4.HasEvents() | _node16.HasEvents());
            Sequence sequence6 = new Sequence();
            sequence6.SetClassNameString("Sequence");
            sequence6.SetId(110);
            else4.AddChild(sequence6);
            Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node40 _node17 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node40();
            _node17.SetClassNameString("Assignment");
            _node17.SetId(40);
            sequence6.AddChild(_node17);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node17.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node111 _node18 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node111();
            _node18.SetClassNameString("Action");
            _node18.SetId(0x6f);
            sequence6.AddChild(_node18);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node18.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node112 _node19 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node112();
            _node19.SetClassNameString("Action");
            _node19.SetId(0x70);
            sequence6.AddChild(_node19);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node19.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node44 _node20 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node44();
            _node20.SetClassNameString("Assignment");
            _node20.SetId(0x2c);
            sequence6.AddChild(_node20);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node20.HasEvents());
            IfElse else5 = new IfElse();
            else5.SetClassNameString("IfElse");
            else5.SetId(5);
            sequence6.AddChild(else5);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node6 _node21 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node6();
            _node21.SetClassNameString("Condition");
            _node21.SetId(6);
            else5.AddChild(_node21);
            else5.SetHasEvents(else5.HasEvents() | _node21.HasEvents());
            Sequence sequence7 = new Sequence();
            sequence7.SetClassNameString("Sequence");
            sequence7.SetId(7);
            else5.AddChild(sequence7);
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node23 _node22 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node23();
            _node22.SetClassNameString("Action");
            _node22.SetId(0x17);
            sequence7.AddChild(_node22);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node22.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node113 _node23 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node113();
            _node23.SetClassNameString("Action");
            _node23.SetId(0x71);
            sequence7.AddChild(_node23);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node23.HasEvents());
            Selector selector = new Selector();
            selector.SetClassNameString("Selector");
            selector.SetId(0x11);
            sequence7.AddChild(selector);
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node114 _node24 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node114();
            _node24.SetClassNameString("Action");
            _node24.SetId(0x72);
            selector.AddChild(_node24);
            selector.SetHasEvents(selector.HasEvents() | _node24.HasEvents());
            DecoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node19 _node25 = new DecoratorAlwaysFailure_bt_WrapperAI_Soldier_BTSoldierNormal_node19();
            _node25.SetClassNameString("DecoratorAlwaysFailure");
            _node25.SetId(0x13);
            selector.AddChild(_node25);
            Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node18 _node26 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node18();
            _node26.SetClassNameString("Assignment");
            _node26.SetId(0x12);
            _node25.AddChild(_node26);
            _node25.SetHasEvents(_node25.HasEvents() | _node26.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | _node25.HasEvents());
            sequence7.SetHasEvents(sequence7.HasEvents() | selector.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node140 _node27 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node140();
            _node27.SetClassNameString("Action");
            _node27.SetId(140);
            sequence7.AddChild(_node27);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node27.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node116 _node28 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node116();
            _node28.SetClassNameString("Action");
            _node28.SetId(0x74);
            sequence7.AddChild(_node28);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node28.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node117 _node29 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node117();
            _node29.SetClassNameString("DecoratorLoopUntil");
            _node29.SetId(0x75);
            sequence7.AddChild(_node29);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node118 _node30 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node118();
            _node30.SetClassNameString("Condition");
            _node30.SetId(0x76);
            _node29.AddChild(_node30);
            _node29.SetHasEvents(_node29.HasEvents() | _node30.HasEvents());
            sequence7.SetHasEvents(sequence7.HasEvents() | _node29.HasEvents());
            else5.SetHasEvents(else5.HasEvents() | sequence7.HasEvents());
            Sequence sequence8 = new Sequence();
            sequence8.SetClassNameString("Sequence");
            sequence8.SetId(9);
            else5.AddChild(sequence8);
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node8 _node31 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node8();
            _node31.SetClassNameString("Action");
            _node31.SetId(8);
            sequence8.AddChild(_node31);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node31.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node13 _node32 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node13();
            _node32.SetClassNameString("Action");
            _node32.SetId(13);
            sequence8.AddChild(_node32);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node32.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node15 _node33 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node15();
            _node33.SetClassNameString("DecoratorLoopUntil");
            _node33.SetId(15);
            sequence8.AddChild(_node33);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node16 _node34 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node16();
            _node34.SetClassNameString("Condition");
            _node34.SetId(0x10);
            _node33.AddChild(_node34);
            _node33.SetHasEvents(_node33.HasEvents() | _node34.HasEvents());
            sequence8.SetHasEvents(sequence8.HasEvents() | _node33.HasEvents());
            else5.SetHasEvents(else5.HasEvents() | sequence8.HasEvents());
            sequence6.SetHasEvents(sequence6.HasEvents() | else5.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node28 _node35 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node28();
            _node35.SetClassNameString("Action");
            _node35.SetId(0x1c);
            sequence6.AddChild(_node35);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node35.HasEvents());
            else4.SetHasEvents(else4.HasEvents() | sequence6.HasEvents());
            Sequence sequence9 = new Sequence();
            sequence9.SetClassNameString("Sequence");
            sequence9.SetId(0x80);
            else4.AddChild(sequence9);
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node129 _node36 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node129();
            _node36.SetClassNameString("Action");
            _node36.SetId(0x81);
            sequence9.AddChild(_node36);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node36.HasEvents());
            IfElse else6 = new IfElse();
            else6.SetClassNameString("IfElse");
            else6.SetId(0x77);
            sequence9.AddChild(else6);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node120 _node37 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node120();
            _node37.SetClassNameString("Condition");
            _node37.SetId(120);
            else6.AddChild(_node37);
            else6.SetHasEvents(else6.HasEvents() | _node37.HasEvents());
            Sequence sequence10 = new Sequence();
            sequence10.SetClassNameString("Sequence");
            sequence10.SetId(0x79);
            else6.AddChild(sequence10);
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node24 _node38 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node24();
            _node38.SetClassNameString("Action");
            _node38.SetId(0x18);
            sequence10.AddChild(_node38);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node38.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node444 _node39 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node444();
            _node39.SetClassNameString("Action");
            _node39.SetId(0x1bc);
            sequence10.AddChild(_node39);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node39.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node122 _node40 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node122();
            _node40.SetClassNameString("Assignment");
            _node40.SetId(0x7a);
            sequence10.AddChild(_node40);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node40.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node123 _node41 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node123();
            _node41.SetClassNameString("Action");
            _node41.SetId(0x7b);
            sequence10.AddChild(_node41);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node41.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node124 _node42 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node124();
            _node42.SetClassNameString("Action");
            _node42.SetId(0x7c);
            sequence10.AddChild(_node42);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node42.HasEvents());
            else6.SetHasEvents(else6.HasEvents() | sequence10.HasEvents());
            Sequence sequence11 = new Sequence();
            sequence11.SetClassNameString("Sequence");
            sequence11.SetId(0x7d);
            else6.AddChild(sequence11);
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node126 _node43 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node126();
            _node43.SetClassNameString("Action");
            _node43.SetId(0x7e);
            sequence11.AddChild(_node43);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node43.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node127 _node44 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node127();
            _node44.SetClassNameString("Action");
            _node44.SetId(0x7f);
            sequence11.AddChild(_node44);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node44.HasEvents());
            else6.SetHasEvents(else6.HasEvents() | sequence11.HasEvents());
            sequence9.SetHasEvents(sequence9.HasEvents() | else6.HasEvents());
            else4.SetHasEvents(else4.HasEvents() | sequence9.HasEvents());
            _node10.SetHasEvents(_node10.HasEvents() | else4.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | _node10.HasEvents());
            precondition.SetHasEvents(precondition.HasEvents() | sequence2.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition.HasEvents());
            WithPrecondition precondition2 = new WithPrecondition();
            precondition2.SetClassNameString("WithPrecondition");
            precondition2.SetId(0x203);
            loop.AddChild(precondition2);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node516 _node45 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node516();
            _node45.SetClassNameString("Condition");
            _node45.SetId(0x204);
            precondition2.AddChild(_node45);
            precondition2.SetHasEvents(precondition2.HasEvents() | _node45.HasEvents());
            Selector selector2 = new Selector();
            selector2.SetClassNameString("Selector");
            selector2.SetId(0x30);
            precondition2.AddChild(selector2);
            Sequence sequence12 = new Sequence();
            sequence12.SetClassNameString("Sequence");
            sequence12.SetId(0x31);
            selector2.AddChild(sequence12);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node25 _node46 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node25();
            _node46.SetClassNameString("Condition");
            _node46.SetId(0x19);
            sequence12.AddChild(_node46);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node46.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node50 _node47 = new Assignment_bt_WrapperAI_Soldier_BTSoldierNormal_node50();
            _node47.SetClassNameString("Assignment");
            _node47.SetId(50);
            sequence12.AddChild(_node47);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node47.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node51 _node48 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node51();
            _node48.SetClassNameString("Action");
            _node48.SetId(0x33);
            sequence12.AddChild(_node48);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node48.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node43 _node49 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node43();
            _node49.SetClassNameString("Action");
            _node49.SetId(0x2b);
            sequence12.AddChild(_node49);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node49.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence12.HasEvents());
            Sequence sequence13 = new Sequence();
            sequence13.SetClassNameString("Sequence");
            sequence13.SetId(0x205);
            selector2.AddChild(sequence13);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node45 _node50 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node45();
            _node50.SetClassNameString("Condition");
            _node50.SetId(0x2d);
            sequence13.AddChild(_node50);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node50.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node518 _node51 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node518();
            _node51.SetClassNameString("Action");
            _node51.SetId(0x206);
            sequence13.AddChild(_node51);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node51.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node519 _node52 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node519();
            _node52.SetClassNameString("Action");
            _node52.SetId(0x207);
            sequence13.AddChild(_node52);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node52.HasEvents());
            IfElse else7 = new IfElse();
            else7.SetClassNameString("IfElse");
            else7.SetId(520);
            sequence13.AddChild(else7);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node521 _node53 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node521();
            _node53.SetClassNameString("Condition");
            _node53.SetId(0x209);
            else7.AddChild(_node53);
            else7.SetHasEvents(else7.HasEvents() | _node53.HasEvents());
            Sequence sequence14 = new Sequence();
            sequence14.SetClassNameString("Sequence");
            sequence14.SetId(0x20a);
            else7.AddChild(sequence14);
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node523 _node54 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node523();
            _node54.SetClassNameString("Action");
            _node54.SetId(0x20b);
            sequence14.AddChild(_node54);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node54.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node524 _node55 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node524();
            _node55.SetClassNameString("Action");
            _node55.SetId(0x20c);
            sequence14.AddChild(_node55);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node55.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node526 _node56 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node526();
            _node56.SetClassNameString("Action");
            _node56.SetId(0x20e);
            sequence14.AddChild(_node56);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node56.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node46 _node57 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node46();
            _node57.SetClassNameString("Action");
            _node57.SetId(0x2e);
            sequence14.AddChild(_node57);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node57.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node530 _node58 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node530();
            _node58.SetClassNameString("Action");
            _node58.SetId(530);
            sequence14.AddChild(_node58);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node58.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node531 _node59 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node531();
            _node59.SetClassNameString("DecoratorLoopUntil");
            _node59.SetId(0x213);
            sequence14.AddChild(_node59);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node532 _node60 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node532();
            _node60.SetClassNameString("Condition");
            _node60.SetId(0x214);
            _node59.AddChild(_node60);
            _node59.SetHasEvents(_node59.HasEvents() | _node60.HasEvents());
            sequence14.SetHasEvents(sequence14.HasEvents() | _node59.HasEvents());
            else7.SetHasEvents(else7.HasEvents() | sequence14.HasEvents());
            Sequence sequence15 = new Sequence();
            sequence15.SetClassNameString("Sequence");
            sequence15.SetId(0x215);
            else7.AddChild(sequence15);
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node47 _node61 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node47();
            _node61.SetClassNameString("Action");
            _node61.SetId(0x2f);
            sequence15.AddChild(_node61);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node61.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node535 _node62 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node535();
            _node62.SetClassNameString("Action");
            _node62.SetId(0x217);
            sequence15.AddChild(_node62);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node62.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node536 _node63 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierNormal_node536();
            _node63.SetClassNameString("DecoratorLoopUntil");
            _node63.SetId(0x218);
            sequence15.AddChild(_node63);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node537 _node64 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node537();
            _node64.SetClassNameString("Condition");
            _node64.SetId(0x219);
            _node63.AddChild(_node64);
            _node63.SetHasEvents(_node63.HasEvents() | _node64.HasEvents());
            sequence15.SetHasEvents(sequence15.HasEvents() | _node63.HasEvents());
            else7.SetHasEvents(else7.HasEvents() | sequence15.HasEvents());
            sequence13.SetHasEvents(sequence13.HasEvents() | else7.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node538 _node65 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node538();
            _node65.SetClassNameString("Action");
            _node65.SetId(0x21a);
            sequence13.AddChild(_node65);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node65.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence13.HasEvents());
            precondition2.SetHasEvents(precondition2.HasEvents() | selector2.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition2.HasEvents());
            WithPrecondition precondition3 = new WithPrecondition();
            precondition3.SetClassNameString("WithPrecondition");
            precondition3.SetId(0x15);
            loop.AddChild(precondition3);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node22 _node66 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node22();
            _node66.SetClassNameString("Condition");
            _node66.SetId(0x16);
            precondition3.AddChild(_node66);
            precondition3.SetHasEvents(precondition3.HasEvents() | _node66.HasEvents());
            Sequence sequence16 = new Sequence();
            sequence16.SetClassNameString("Sequence");
            sequence16.SetId(0x1b);
            precondition3.AddChild(sequence16);
            Selector selector3 = new Selector();
            selector3.SetClassNameString("Selector");
            selector3.SetId(0x1e7);
            sequence16.AddChild(selector3);
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node488 _node67 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node488();
            _node67.SetClassNameString("Action");
            _node67.SetId(0x1e8);
            selector3.AddChild(_node67);
            selector3.SetHasEvents(selector3.HasEvents() | _node67.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node35 _node68 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node35();
            _node68.SetClassNameString("Action");
            _node68.SetId(0x23);
            selector3.AddChild(_node68);
            selector3.SetHasEvents(selector3.HasEvents() | _node68.HasEvents());
            sequence16.SetHasEvents(sequence16.HasEvents() | selector3.HasEvents());
            DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node65 _node69 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node65();
            _node69.SetClassNameString("DecoratorLoop");
            _node69.SetId(0x41);
            sequence16.AddChild(_node69);
            Noop noop3 = new Noop();
            noop3.SetClassNameString("Noop");
            noop3.SetId(0x42);
            _node69.AddChild(noop3);
            _node69.SetHasEvents(_node69.HasEvents() | noop3.HasEvents());
            sequence16.SetHasEvents(sequence16.HasEvents() | _node69.HasEvents());
            precondition3.SetHasEvents(precondition3.HasEvents() | sequence16.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition3.HasEvents());
            WithPrecondition precondition4 = new WithPrecondition();
            precondition4.SetClassNameString("WithPrecondition");
            precondition4.SetId(450);
            loop.AddChild(precondition4);
            Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node454 _node70 = new Condition_bt_WrapperAI_Soldier_BTSoldierNormal_node454();
            _node70.SetClassNameString("Condition");
            _node70.SetId(0x1c6);
            precondition4.AddChild(_node70);
            precondition4.SetHasEvents(precondition4.HasEvents() | _node70.HasEvents());
            Sequence sequence17 = new Sequence();
            sequence17.SetClassNameString("Sequence");
            sequence17.SetId(0x1c7);
            precondition4.AddChild(sequence17);
            Action_bt_WrapperAI_Soldier_BTSoldierNormal_node456 _node71 = new Action_bt_WrapperAI_Soldier_BTSoldierNormal_node456();
            _node71.SetClassNameString("Action");
            _node71.SetId(0x1c8);
            sequence17.AddChild(_node71);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node71.HasEvents());
            DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node457 _node72 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierNormal_node457();
            _node72.SetClassNameString("DecoratorLoop");
            _node72.SetId(0x1c9);
            sequence17.AddChild(_node72);
            Noop noop4 = new Noop();
            noop4.SetClassNameString("Noop");
            noop4.SetId(0x1ca);
            _node72.AddChild(noop4);
            _node72.SetHasEvents(_node72.HasEvents() | noop4.HasEvents());
            sequence17.SetHasEvents(sequence17.HasEvents() | _node72.HasEvents());
            precondition4.SetHasEvents(precondition4.HasEvents() | sequence17.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition4.HasEvents());
            _node2.SetHasEvents(_node2.HasEvents() | loop.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | _node2.HasEvents());
            bt.SetHasEvents(bt.HasEvents() | pChild.HasEvents());
            return true;
        }
    }
}

