namespace behaviac
{
    using System;

    public static class bt_WrapperAI_Soldier_BTSoldierPro
    {
        public static bool build_behavior_tree(BehaviorTree bt)
        {
            bt.SetClassNameString("BehaviorTree");
            bt.SetId(-1);
            bt.SetName("WrapperAI/Soldier/BTSoldierPro");
            bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
            bt.AddPar("uint", "p_targetID", "0", string.Empty);
            bt.AddPar("int", "p_srchRange", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
            bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
            bt.AddPar("uint", "p_CmdID", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_skillAttackRange", "0", string.Empty);
            bt.AddPar("uint", "p_selfID", "0", string.Empty);
            Sequence pChild = new Sequence();
            pChild.SetClassNameString("Sequence");
            pChild.SetId(0);
            bt.AddChild(pChild);
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node106 _node = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node106();
            _node.SetClassNameString("Assignment");
            _node.SetId(0x6a);
            pChild.AddChild(_node);
            pChild.SetHasEvents(pChild.HasEvents() | _node.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node109 _node2 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node109();
            _node2.SetClassNameString("Assignment");
            _node2.SetId(0x6d);
            pChild.AddChild(_node2);
            pChild.SetHasEvents(pChild.HasEvents() | _node2.HasEvents());
            DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node14 _node3 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node14();
            _node3.SetClassNameString("DecoratorLoop");
            _node3.SetId(14);
            pChild.AddChild(_node3);
            SelectorLoop loop = new SelectorLoop();
            loop.SetClassNameString("SelectorLoop");
            loop.SetId(1);
            _node3.AddChild(loop);
            WithPrecondition precondition = new WithPrecondition();
            precondition.SetClassNameString("WithPrecondition");
            precondition.SetId(0x3b);
            loop.AddChild(precondition);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node78 _node4 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node78();
            _node4.SetClassNameString("Condition");
            _node4.SetId(0x4e);
            precondition.AddChild(_node4);
            precondition.SetHasEvents(precondition.HasEvents() | _node4.HasEvents());
            Sequence sequence2 = new Sequence();
            sequence2.SetClassNameString("Sequence");
            sequence2.SetId(0x69);
            precondition.AddChild(sequence2);
            IfElse @else = new IfElse();
            @else.SetClassNameString("IfElse");
            @else.SetId(0x21);
            sequence2.AddChild(@else);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node24 _node5 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node24();
            _node5.SetClassNameString("Action");
            _node5.SetId(0x18);
            @else.AddChild(_node5);
            @else.SetHasEvents(@else.HasEvents() | _node5.HasEvents());
            Sequence sequence3 = new Sequence();
            sequence3.SetClassNameString("Sequence");
            sequence3.SetId(0x1b);
            @else.AddChild(sequence3);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node35 _node6 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node35();
            _node6.SetClassNameString("Action");
            _node6.SetId(0x23);
            sequence3.AddChild(_node6);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node6.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node36 _node7 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node36();
            _node7.SetClassNameString("Assignment");
            _node7.SetId(0x24);
            sequence3.AddChild(_node7);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node7.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | sequence3.HasEvents());
            Noop noop = new Noop();
            noop.SetClassNameString("Noop");
            noop.SetId(0x22);
            @else.AddChild(noop);
            @else.SetHasEvents(@else.HasEvents() | noop.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | @else.HasEvents());
            Sequence sequence4 = new Sequence();
            sequence4.SetClassNameString("Sequence");
            sequence4.SetId(0x8e);
            sequence2.AddChild(sequence4);
            IfElse else2 = new IfElse();
            else2.SetClassNameString("IfElse");
            else2.SetId(0xbb);
            sequence4.AddChild(else2);
            And and = new And();
            and.SetClassNameString("And");
            and.SetId(0xbc);
            else2.AddChild(and);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node189 _node8 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node189();
            _node8.SetClassNameString("Condition");
            _node8.SetId(0xbd);
            and.AddChild(_node8);
            and.SetHasEvents(and.HasEvents() | _node8.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node190 _node9 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node190();
            _node9.SetClassNameString("Condition");
            _node9.SetId(190);
            and.AddChild(_node9);
            and.SetHasEvents(and.HasEvents() | _node9.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | and.HasEvents());
            Noop noop2 = new Noop();
            noop2.SetClassNameString("Noop");
            noop2.SetId(0xbf);
            else2.AddChild(noop2);
            else2.SetHasEvents(else2.HasEvents() | noop2.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node9 _node10 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node9();
            _node10.SetClassNameString("Assignment");
            _node10.SetId(9);
            else2.AddChild(_node10);
            else2.SetHasEvents(else2.HasEvents() | _node10.HasEvents());
            sequence4.SetHasEvents(sequence4.HasEvents() | else2.HasEvents());
            IfElse else3 = new IfElse();
            else3.SetClassNameString("IfElse");
            else3.SetId(0x91);
            sequence4.AddChild(else3);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node146 _node11 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node146();
            _node11.SetClassNameString("Condition");
            _node11.SetId(0x92);
            else3.AddChild(_node11);
            else3.SetHasEvents(else3.HasEvents() | _node11.HasEvents());
            Sequence sequence5 = new Sequence();
            sequence5.SetClassNameString("Sequence");
            sequence5.SetId(0x9a);
            else3.AddChild(sequence5);
            Selector selector = new Selector();
            selector.SetClassNameString("Selector");
            selector.SetId(0x98);
            sequence5.AddChild(selector);
            Sequence sequence6 = new Sequence();
            sequence6.SetClassNameString("Sequence");
            sequence6.SetId(0x99);
            selector.AddChild(sequence6);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node156 _node12 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node156();
            _node12.SetClassNameString("Action");
            _node12.SetId(0x9c);
            sequence6.AddChild(_node12);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node12.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node159 _node13 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node159();
            _node13.SetClassNameString("Assignment");
            _node13.SetId(0x9f);
            sequence6.AddChild(_node13);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node13.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node160 _node14 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node160();
            _node14.SetClassNameString("Assignment");
            _node14.SetId(160);
            sequence6.AddChild(_node14);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node14.HasEvents());
            Selector selector2 = new Selector();
            selector2.SetClassNameString("Selector");
            selector2.SetId(0x55);
            sequence6.AddChild(selector2);
            Sequence sequence7 = new Sequence();
            sequence7.SetClassNameString("Sequence");
            sequence7.SetId(0x5b);
            selector2.AddChild(sequence7);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node712 _node15 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node712();
            _node15.SetClassNameString("Action");
            _node15.SetId(0x2c8);
            sequence7.AddChild(_node15);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node15.HasEvents());
            Selector selector3 = new Selector();
            selector3.SetClassNameString("Selector");
            selector3.SetId(3);
            sequence7.AddChild(selector3);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node2 _node16 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node2();
            _node16.SetClassNameString("Condition");
            _node16.SetId(2);
            selector3.AddChild(_node16);
            selector3.SetHasEvents(selector3.HasEvents() | _node16.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node4 _node17 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node4();
            _node17.SetClassNameString("Condition");
            _node17.SetId(4);
            selector3.AddChild(_node17);
            selector3.SetHasEvents(selector3.HasEvents() | _node17.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node92 _node18 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node92();
            _node18.SetClassNameString("Condition");
            _node18.SetId(0x5c);
            selector3.AddChild(_node18);
            selector3.SetHasEvents(selector3.HasEvents() | _node18.HasEvents());
            sequence7.SetHasEvents(sequence7.HasEvents() | selector3.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node93 _node19 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node93();
            _node19.SetClassNameString("Condition");
            _node19.SetId(0x5d);
            sequence7.AddChild(_node19);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node19.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node94 _node20 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node94();
            _node20.SetClassNameString("Action");
            _node20.SetId(0x5e);
            sequence7.AddChild(_node20);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node20.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence7.HasEvents());
            Sequence sequence8 = new Sequence();
            sequence8.SetClassNameString("Sequence");
            sequence8.SetId(0x5f);
            selector2.AddChild(sequence8);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node96 _node21 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node96();
            _node21.SetClassNameString("Condition");
            _node21.SetId(0x60);
            sequence8.AddChild(_node21);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node21.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node97 _node22 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node97();
            _node22.SetClassNameString("Assignment");
            _node22.SetId(0x61);
            sequence8.AddChild(_node22);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node22.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node98 _node23 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node98();
            _node23.SetClassNameString("Condition");
            _node23.SetId(0x62);
            sequence8.AddChild(_node23);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node23.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node100 _node24 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node100();
            _node24.SetClassNameString("Action");
            _node24.SetId(100);
            sequence8.AddChild(_node24);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node24.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence8.HasEvents());
            Sequence sequence9 = new Sequence();
            sequence9.SetClassNameString("Sequence");
            sequence9.SetId(0x65);
            selector2.AddChild(sequence9);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node18 _node25 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node18();
            _node25.SetClassNameString("Condition");
            _node25.SetId(0x12);
            sequence9.AddChild(_node25);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node25.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node102 _node26 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node102();
            _node26.SetClassNameString("Condition");
            _node26.SetId(0x66);
            sequence9.AddChild(_node26);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node26.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node103 _node27 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node103();
            _node27.SetClassNameString("Action");
            _node27.SetId(0x67);
            sequence9.AddChild(_node27);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node27.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence9.HasEvents());
            sequence6.SetHasEvents(sequence6.HasEvents() | selector2.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence6.HasEvents());
            Sequence sequence10 = new Sequence();
            sequence10.SetClassNameString("Sequence");
            sequence10.SetId(0xa1);
            selector.AddChild(sequence10);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node140 _node28 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node140();
            _node28.SetClassNameString("Action");
            _node28.SetId(140);
            sequence10.AddChild(_node28);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node28.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node162 _node29 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node162();
            _node29.SetClassNameString("Assignment");
            _node29.SetId(0xa2);
            sequence10.AddChild(_node29);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node29.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node166 _node30 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node166();
            _node30.SetClassNameString("Assignment");
            _node30.SetId(0xa6);
            sequence10.AddChild(_node30);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node30.HasEvents());
            Selector selector4 = new Selector();
            selector4.SetClassNameString("Selector");
            selector4.SetId(30);
            sequence10.AddChild(selector4);
            Sequence sequence11 = new Sequence();
            sequence11.SetClassNameString("Sequence");
            sequence11.SetId(0x68);
            selector4.AddChild(sequence11);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node107 _node31 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node107();
            _node31.SetClassNameString("Action");
            _node31.SetId(0x6b);
            sequence11.AddChild(_node31);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node31.HasEvents());
            Selector selector5 = new Selector();
            selector5.SetClassNameString("Selector");
            selector5.SetId(0x16);
            sequence11.AddChild(selector5);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node108 _node32 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node108();
            _node32.SetClassNameString("Condition");
            _node32.SetId(0x6c);
            selector5.AddChild(_node32);
            selector5.SetHasEvents(selector5.HasEvents() | _node32.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node25 _node33 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node25();
            _node33.SetClassNameString("Condition");
            _node33.SetId(0x19);
            selector5.AddChild(_node33);
            selector5.SetHasEvents(selector5.HasEvents() | _node33.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node26 _node34 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node26();
            _node34.SetClassNameString("Condition");
            _node34.SetId(0x1a);
            selector5.AddChild(_node34);
            selector5.SetHasEvents(selector5.HasEvents() | _node34.HasEvents());
            sequence11.SetHasEvents(sequence11.HasEvents() | selector5.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node116 _node35 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node116();
            _node35.SetClassNameString("Condition");
            _node35.SetId(0x74);
            sequence11.AddChild(_node35);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node35.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node117 _node36 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node117();
            _node36.SetClassNameString("Action");
            _node36.SetId(0x75);
            sequence11.AddChild(_node36);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node36.HasEvents());
            selector4.SetHasEvents(selector4.HasEvents() | sequence11.HasEvents());
            Sequence sequence12 = new Sequence();
            sequence12.SetClassNameString("Sequence");
            sequence12.SetId(0x76);
            selector4.AddChild(sequence12);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node119 _node37 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node119();
            _node37.SetClassNameString("Condition");
            _node37.SetId(0x77);
            sequence12.AddChild(_node37);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node37.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node37 _node38 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node37();
            _node38.SetClassNameString("Assignment");
            _node38.SetId(0x25);
            sequence12.AddChild(_node38);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node38.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node38 _node39 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node38();
            _node39.SetClassNameString("Condition");
            _node39.SetId(0x26);
            sequence12.AddChild(_node39);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node39.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node39 _node40 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node39();
            _node40.SetClassNameString("Action");
            _node40.SetId(0x27);
            sequence12.AddChild(_node40);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node40.HasEvents());
            selector4.SetHasEvents(selector4.HasEvents() | sequence12.HasEvents());
            Sequence sequence13 = new Sequence();
            sequence13.SetClassNameString("Sequence");
            sequence13.SetId(40);
            selector4.AddChild(sequence13);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node41 _node41 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node41();
            _node41.SetClassNameString("Condition");
            _node41.SetId(0x29);
            sequence13.AddChild(_node41);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node41.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node42 _node42 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node42();
            _node42.SetClassNameString("Condition");
            _node42.SetId(0x2a);
            sequence13.AddChild(_node42);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node42.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node43 _node43 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node43();
            _node43.SetClassNameString("Action");
            _node43.SetId(0x2b);
            sequence13.AddChild(_node43);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node43.HasEvents());
            selector4.SetHasEvents(selector4.HasEvents() | sequence13.HasEvents());
            sequence10.SetHasEvents(sequence10.HasEvents() | selector4.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence10.HasEvents());
            Sequence sequence14 = new Sequence();
            sequence14.SetClassNameString("Sequence");
            sequence14.SetId(0xa7);
            selector.AddChild(sequence14);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node5 _node44 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node5();
            _node44.SetClassNameString("Action");
            _node44.SetId(5);
            sequence14.AddChild(_node44);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node44.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node168 _node45 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node168();
            _node45.SetClassNameString("Assignment");
            _node45.SetId(0xa8);
            sequence14.AddChild(_node45);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node45.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node172 _node46 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node172();
            _node46.SetClassNameString("Assignment");
            _node46.SetId(0xac);
            sequence14.AddChild(_node46);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node46.HasEvents());
            Selector selector6 = new Selector();
            selector6.SetClassNameString("Selector");
            selector6.SetId(0x1f);
            sequence14.AddChild(selector6);
            Sequence sequence15 = new Sequence();
            sequence15.SetClassNameString("Sequence");
            sequence15.SetId(0x2c);
            selector6.AddChild(sequence15);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node45 _node47 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node45();
            _node47.SetClassNameString("Action");
            _node47.SetId(0x2d);
            sequence15.AddChild(_node47);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node47.HasEvents());
            Selector selector7 = new Selector();
            selector7.SetClassNameString("Selector");
            selector7.SetId(0x2e);
            sequence15.AddChild(selector7);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node47 _node48 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node47();
            _node48.SetClassNameString("Condition");
            _node48.SetId(0x2f);
            selector7.AddChild(_node48);
            selector7.SetHasEvents(selector7.HasEvents() | _node48.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node48 _node49 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node48();
            _node49.SetClassNameString("Condition");
            _node49.SetId(0x30);
            selector7.AddChild(_node49);
            selector7.SetHasEvents(selector7.HasEvents() | _node49.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node49 _node50 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node49();
            _node50.SetClassNameString("Condition");
            _node50.SetId(0x31);
            selector7.AddChild(_node50);
            selector7.SetHasEvents(selector7.HasEvents() | _node50.HasEvents());
            sequence15.SetHasEvents(sequence15.HasEvents() | selector7.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node50 _node51 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node50();
            _node51.SetClassNameString("Condition");
            _node51.SetId(50);
            sequence15.AddChild(_node51);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node51.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node51 _node52 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node51();
            _node52.SetClassNameString("Action");
            _node52.SetId(0x33);
            sequence15.AddChild(_node52);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node52.HasEvents());
            selector6.SetHasEvents(selector6.HasEvents() | sequence15.HasEvents());
            Sequence sequence16 = new Sequence();
            sequence16.SetClassNameString("Sequence");
            sequence16.SetId(0x34);
            selector6.AddChild(sequence16);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node53 _node53 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node53();
            _node53.SetClassNameString("Condition");
            _node53.SetId(0x35);
            sequence16.AddChild(_node53);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node53.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node54 _node54 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node54();
            _node54.SetClassNameString("Assignment");
            _node54.SetId(0x36);
            sequence16.AddChild(_node54);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node54.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node55 _node55 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node55();
            _node55.SetClassNameString("Condition");
            _node55.SetId(0x37);
            sequence16.AddChild(_node55);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node55.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node56 _node56 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node56();
            _node56.SetClassNameString("Action");
            _node56.SetId(0x38);
            sequence16.AddChild(_node56);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node56.HasEvents());
            selector6.SetHasEvents(selector6.HasEvents() | sequence16.HasEvents());
            Sequence sequence17 = new Sequence();
            sequence17.SetClassNameString("Sequence");
            sequence17.SetId(0x39);
            selector6.AddChild(sequence17);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node58 _node57 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node58();
            _node57.SetClassNameString("Condition");
            _node57.SetId(0x3a);
            sequence17.AddChild(_node57);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node57.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node60 _node58 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node60();
            _node58.SetClassNameString("Condition");
            _node58.SetId(60);
            sequence17.AddChild(_node58);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node58.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node61 _node59 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node61();
            _node59.SetClassNameString("Action");
            _node59.SetId(0x3d);
            sequence17.AddChild(_node59);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node59.HasEvents());
            selector6.SetHasEvents(selector6.HasEvents() | sequence17.HasEvents());
            sequence14.SetHasEvents(sequence14.HasEvents() | selector6.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence14.HasEvents());
            Sequence sequence18 = new Sequence();
            sequence18.SetClassNameString("Sequence");
            sequence18.SetId(0xad);
            selector.AddChild(sequence18);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node82 _node60 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node82();
            _node60.SetClassNameString("Action");
            _node60.SetId(0x52);
            sequence18.AddChild(_node60);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node60.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node174 _node61 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node174();
            _node61.SetClassNameString("Assignment");
            _node61.SetId(0xae);
            sequence18.AddChild(_node61);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node61.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node178 _node62 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node178();
            _node62.SetClassNameString("Assignment");
            _node62.SetId(0xb2);
            sequence18.AddChild(_node62);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node62.HasEvents());
            Selector selector8 = new Selector();
            selector8.SetClassNameString("Selector");
            selector8.SetId(0x20);
            sequence18.AddChild(selector8);
            Sequence sequence19 = new Sequence();
            sequence19.SetClassNameString("Sequence");
            sequence19.SetId(0x3e);
            selector8.AddChild(sequence19);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node63 _node63 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node63();
            _node63.SetClassNameString("Action");
            _node63.SetId(0x3f);
            sequence19.AddChild(_node63);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node63.HasEvents());
            Selector selector9 = new Selector();
            selector9.SetClassNameString("Selector");
            selector9.SetId(0x40);
            sequence19.AddChild(selector9);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node65 _node64 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node65();
            _node64.SetClassNameString("Condition");
            _node64.SetId(0x41);
            selector9.AddChild(_node64);
            selector9.SetHasEvents(selector9.HasEvents() | _node64.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node66 _node65 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node66();
            _node65.SetClassNameString("Condition");
            _node65.SetId(0x42);
            selector9.AddChild(_node65);
            selector9.SetHasEvents(selector9.HasEvents() | _node65.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node67 _node66 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node67();
            _node66.SetClassNameString("Condition");
            _node66.SetId(0x43);
            selector9.AddChild(_node66);
            selector9.SetHasEvents(selector9.HasEvents() | _node66.HasEvents());
            sequence19.SetHasEvents(sequence19.HasEvents() | selector9.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node68 _node67 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node68();
            _node67.SetClassNameString("Condition");
            _node67.SetId(0x44);
            sequence19.AddChild(_node67);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node67.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node69 _node68 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node69();
            _node68.SetClassNameString("Action");
            _node68.SetId(0x45);
            sequence19.AddChild(_node68);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node68.HasEvents());
            selector8.SetHasEvents(selector8.HasEvents() | sequence19.HasEvents());
            Sequence sequence20 = new Sequence();
            sequence20.SetClassNameString("Sequence");
            sequence20.SetId(70);
            selector8.AddChild(sequence20);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node71 _node69 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node71();
            _node69.SetClassNameString("Condition");
            _node69.SetId(0x47);
            sequence20.AddChild(_node69);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node69.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node72 _node70 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node72();
            _node70.SetClassNameString("Assignment");
            _node70.SetId(0x48);
            sequence20.AddChild(_node70);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node70.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node73 _node71 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node73();
            _node71.SetClassNameString("Condition");
            _node71.SetId(0x49);
            sequence20.AddChild(_node71);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node71.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node120 _node72 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node120();
            _node72.SetClassNameString("Action");
            _node72.SetId(120);
            sequence20.AddChild(_node72);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node72.HasEvents());
            selector8.SetHasEvents(selector8.HasEvents() | sequence20.HasEvents());
            Sequence sequence21 = new Sequence();
            sequence21.SetClassNameString("Sequence");
            sequence21.SetId(0x4b);
            selector8.AddChild(sequence21);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node76 _node73 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node76();
            _node73.SetClassNameString("Condition");
            _node73.SetId(0x4c);
            sequence21.AddChild(_node73);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node73.HasEvents());
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node77 _node74 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node77();
            _node74.SetClassNameString("Condition");
            _node74.SetId(0x4d);
            sequence21.AddChild(_node74);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node74.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node79 _node75 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node79();
            _node75.SetClassNameString("Action");
            _node75.SetId(0x4f);
            sequence21.AddChild(_node75);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node75.HasEvents());
            selector8.SetHasEvents(selector8.HasEvents() | sequence21.HasEvents());
            sequence18.SetHasEvents(sequence18.HasEvents() | selector8.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence18.HasEvents());
            IfElse else4 = new IfElse();
            else4.SetClassNameString("IfElse");
            else4.SetId(6);
            selector.AddChild(else4);
            Sequence sequence22 = new Sequence();
            sequence22.SetClassNameString("Sequence");
            sequence22.SetId(0x119);
            else4.AddChild(sequence22);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node429 _node76 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node429();
            _node76.SetClassNameString("Condition");
            _node76.SetId(0x1ad);
            sequence22.AddChild(_node76);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node76.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node430 _node77 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node430();
            _node77.SetClassNameString("Action");
            _node77.SetId(430);
            sequence22.AddChild(_node77);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node77.HasEvents());
            else4.SetHasEvents(else4.HasEvents() | sequence22.HasEvents());
            Sequence sequence23 = new Sequence();
            sequence23.SetClassNameString("Sequence");
            sequence23.SetId(0x1af);
            else4.AddChild(sequence23);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node444 _node78 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node444();
            _node78.SetClassNameString("Action");
            _node78.SetId(0x1bc);
            sequence23.AddChild(_node78);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node78.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node432 _node79 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node432();
            _node79.SetClassNameString("Action");
            _node79.SetId(0x1b0);
            sequence23.AddChild(_node79);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node79.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node438 _node80 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node438();
            _node80.SetClassNameString("Action");
            _node80.SetId(0x1b6);
            sequence23.AddChild(_node80);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node80.HasEvents());
            else4.SetHasEvents(else4.HasEvents() | sequence23.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node439 _node81 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node439();
            _node81.SetClassNameString("Action");
            _node81.SetId(0x1b7);
            else4.AddChild(_node81);
            else4.SetHasEvents(else4.HasEvents() | _node81.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | else4.HasEvents());
            sequence5.SetHasEvents(sequence5.HasEvents() | selector.HasEvents());
            Sequence sequence24 = new Sequence();
            sequence24.SetClassNameString("Sequence");
            sequence24.SetId(0x94);
            sequence5.AddChild(sequence24);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node74 _node82 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node74();
            _node82.SetClassNameString("Action");
            _node82.SetId(0x4a);
            sequence24.AddChild(_node82);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node82.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node20 _node83 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node20();
            _node83.SetClassNameString("Action");
            _node83.SetId(20);
            sequence24.AddChild(_node83);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node83.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node99 _node84 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node99();
            _node84.SetClassNameString("DecoratorLoopUntil");
            _node84.SetId(0x63);
            sequence24.AddChild(_node84);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node132 _node85 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node132();
            _node85.SetClassNameString("Condition");
            _node85.SetId(0x84);
            _node84.AddChild(_node85);
            _node84.SetHasEvents(_node84.HasEvents() | _node85.HasEvents());
            sequence24.SetHasEvents(sequence24.HasEvents() | _node84.HasEvents());
            sequence5.SetHasEvents(sequence5.HasEvents() | sequence24.HasEvents());
            else3.SetHasEvents(else3.HasEvents() | sequence5.HasEvents());
            Sequence sequence25 = new Sequence();
            sequence25.SetClassNameString("Sequence");
            sequence25.SetId(7);
            else3.AddChild(sequence25);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node8 _node86 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node8();
            _node86.SetClassNameString("Action");
            _node86.SetId(8);
            sequence25.AddChild(_node86);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node86.HasEvents());
            IfElse else5 = new IfElse();
            else5.SetClassNameString("IfElse");
            else5.SetId(10);
            sequence25.AddChild(else5);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node11 _node87 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node11();
            _node87.SetClassNameString("Condition");
            _node87.SetId(11);
            else5.AddChild(_node87);
            else5.SetHasEvents(else5.HasEvents() | _node87.HasEvents());
            Sequence sequence26 = new Sequence();
            sequence26.SetClassNameString("Sequence");
            sequence26.SetId(12);
            else5.AddChild(sequence26);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node13 _node88 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node13();
            _node88.SetClassNameString("Action");
            _node88.SetId(13);
            sequence26.AddChild(_node88);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node88.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node21 _node89 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node21();
            _node89.SetClassNameString("Action");
            _node89.SetId(0x15);
            sequence26.AddChild(_node89);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node89.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node15 _node90 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node15();
            _node90.SetClassNameString("Assignment");
            _node90.SetId(15);
            sequence26.AddChild(_node90);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node90.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node16 _node91 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node16();
            _node91.SetClassNameString("Action");
            _node91.SetId(0x10);
            sequence26.AddChild(_node91);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node91.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node17 _node92 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node17();
            _node92.SetClassNameString("Action");
            _node92.SetId(0x11);
            sequence26.AddChild(_node92);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node92.HasEvents());
            else5.SetHasEvents(else5.HasEvents() | sequence26.HasEvents());
            Sequence sequence27 = new Sequence();
            sequence27.SetClassNameString("Sequence");
            sequence27.SetId(0x13);
            else5.AddChild(sequence27);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node23 _node93 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node23();
            _node93.SetClassNameString("Action");
            _node93.SetId(0x17);
            sequence27.AddChild(_node93);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node93.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node28 _node94 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node28();
            _node94.SetClassNameString("Action");
            _node94.SetId(0x1c);
            sequence27.AddChild(_node94);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node94.HasEvents());
            WaitFrames_bt_WrapperAI_Soldier_BTSoldierPro_node29 _node95 = new WaitFrames_bt_WrapperAI_Soldier_BTSoldierPro_node29();
            _node95.SetClassNameString("WaitFrames");
            _node95.SetId(0x1d);
            sequence27.AddChild(_node95);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node95.HasEvents());
            else5.SetHasEvents(else5.HasEvents() | sequence27.HasEvents());
            sequence25.SetHasEvents(sequence25.HasEvents() | else5.HasEvents());
            else3.SetHasEvents(else3.HasEvents() | sequence25.HasEvents());
            sequence4.SetHasEvents(sequence4.HasEvents() | else3.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | sequence4.HasEvents());
            precondition.SetHasEvents(precondition.HasEvents() | sequence2.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition.HasEvents());
            WithPrecondition precondition2 = new WithPrecondition();
            precondition2.SetClassNameString("WithPrecondition");
            precondition2.SetId(0x203);
            loop.AddChild(precondition2);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node516 _node96 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node516();
            _node96.SetClassNameString("Condition");
            _node96.SetId(0x204);
            precondition2.AddChild(_node96);
            precondition2.SetHasEvents(precondition2.HasEvents() | _node96.HasEvents());
            Selector selector10 = new Selector();
            selector10.SetClassNameString("Selector");
            selector10.SetId(80);
            precondition2.AddChild(selector10);
            Sequence sequence28 = new Sequence();
            sequence28.SetClassNameString("Sequence");
            sequence28.SetId(0x51);
            selector10.AddChild(sequence28);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node83 _node97 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node83();
            _node97.SetClassNameString("Condition");
            _node97.SetId(0x53);
            sequence28.AddChild(_node97);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node97.HasEvents());
            Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node84 _node98 = new Assignment_bt_WrapperAI_Soldier_BTSoldierPro_node84();
            _node98.SetClassNameString("Assignment");
            _node98.SetId(0x54);
            sequence28.AddChild(_node98);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node98.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node86 _node99 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node86();
            _node99.SetClassNameString("Action");
            _node99.SetId(0x56);
            sequence28.AddChild(_node99);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node99.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node87 _node100 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node87();
            _node100.SetClassNameString("Action");
            _node100.SetId(0x57);
            sequence28.AddChild(_node100);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node100.HasEvents());
            selector10.SetHasEvents(selector10.HasEvents() | sequence28.HasEvents());
            Sequence sequence29 = new Sequence();
            sequence29.SetClassNameString("Sequence");
            sequence29.SetId(0x205);
            selector10.AddChild(sequence29);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node88 _node101 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node88();
            _node101.SetClassNameString("Condition");
            _node101.SetId(0x58);
            sequence29.AddChild(_node101);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node101.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node518 _node102 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node518();
            _node102.SetClassNameString("Action");
            _node102.SetId(0x206);
            sequence29.AddChild(_node102);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node102.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node519 _node103 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node519();
            _node103.SetClassNameString("Action");
            _node103.SetId(0x207);
            sequence29.AddChild(_node103);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node103.HasEvents());
            IfElse else6 = new IfElse();
            else6.SetClassNameString("IfElse");
            else6.SetId(520);
            sequence29.AddChild(else6);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node521 _node104 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node521();
            _node104.SetClassNameString("Condition");
            _node104.SetId(0x209);
            else6.AddChild(_node104);
            else6.SetHasEvents(else6.HasEvents() | _node104.HasEvents());
            Sequence sequence30 = new Sequence();
            sequence30.SetClassNameString("Sequence");
            sequence30.SetId(0x20a);
            else6.AddChild(sequence30);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node523 _node105 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node523();
            _node105.SetClassNameString("Action");
            _node105.SetId(0x20b);
            sequence30.AddChild(_node105);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node105.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node524 _node106 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node524();
            _node106.SetClassNameString("Action");
            _node106.SetId(0x20c);
            sequence30.AddChild(_node106);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node106.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node526 _node107 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node526();
            _node107.SetClassNameString("Action");
            _node107.SetId(0x20e);
            sequence30.AddChild(_node107);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node107.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node89 _node108 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node89();
            _node108.SetClassNameString("Action");
            _node108.SetId(0x59);
            sequence30.AddChild(_node108);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node108.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node530 _node109 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node530();
            _node109.SetClassNameString("Action");
            _node109.SetId(530);
            sequence30.AddChild(_node109);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node109.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node531 _node110 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node531();
            _node110.SetClassNameString("DecoratorLoopUntil");
            _node110.SetId(0x213);
            sequence30.AddChild(_node110);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node532 _node111 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node532();
            _node111.SetClassNameString("Condition");
            _node111.SetId(0x214);
            _node110.AddChild(_node111);
            _node110.SetHasEvents(_node110.HasEvents() | _node111.HasEvents());
            sequence30.SetHasEvents(sequence30.HasEvents() | _node110.HasEvents());
            else6.SetHasEvents(else6.HasEvents() | sequence30.HasEvents());
            Sequence sequence31 = new Sequence();
            sequence31.SetClassNameString("Sequence");
            sequence31.SetId(0x215);
            else6.AddChild(sequence31);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node90 _node112 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node90();
            _node112.SetClassNameString("Action");
            _node112.SetId(90);
            sequence31.AddChild(_node112);
            sequence31.SetHasEvents(sequence31.HasEvents() | _node112.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node535 _node113 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node535();
            _node113.SetClassNameString("Action");
            _node113.SetId(0x217);
            sequence31.AddChild(_node113);
            sequence31.SetHasEvents(sequence31.HasEvents() | _node113.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node536 _node114 = new DecoratorLoopUntil_bt_WrapperAI_Soldier_BTSoldierPro_node536();
            _node114.SetClassNameString("DecoratorLoopUntil");
            _node114.SetId(0x218);
            sequence31.AddChild(_node114);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node537 _node115 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node537();
            _node115.SetClassNameString("Condition");
            _node115.SetId(0x219);
            _node114.AddChild(_node115);
            _node114.SetHasEvents(_node114.HasEvents() | _node115.HasEvents());
            sequence31.SetHasEvents(sequence31.HasEvents() | _node114.HasEvents());
            else6.SetHasEvents(else6.HasEvents() | sequence31.HasEvents());
            sequence29.SetHasEvents(sequence29.HasEvents() | else6.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node538 _node116 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node538();
            _node116.SetClassNameString("Action");
            _node116.SetId(0x21a);
            sequence29.AddChild(_node116);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node116.HasEvents());
            selector10.SetHasEvents(selector10.HasEvents() | sequence29.HasEvents());
            precondition2.SetHasEvents(precondition2.HasEvents() | selector10.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition2.HasEvents());
            WithPrecondition precondition3 = new WithPrecondition();
            precondition3.SetClassNameString("WithPrecondition");
            precondition3.SetId(110);
            loop.AddChild(precondition3);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node111 _node117 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node111();
            _node117.SetClassNameString("Condition");
            _node117.SetId(0x6f);
            precondition3.AddChild(_node117);
            precondition3.SetHasEvents(precondition3.HasEvents() | _node117.HasEvents());
            Sequence sequence32 = new Sequence();
            sequence32.SetClassNameString("Sequence");
            sequence32.SetId(0x70);
            precondition3.AddChild(sequence32);
            Selector selector11 = new Selector();
            selector11.SetClassNameString("Selector");
            selector11.SetId(0x1e7);
            sequence32.AddChild(selector11);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node488 _node118 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node488();
            _node118.SetClassNameString("Action");
            _node118.SetId(0x1e8);
            selector11.AddChild(_node118);
            selector11.SetHasEvents(selector11.HasEvents() | _node118.HasEvents());
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node113 _node119 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node113();
            _node119.SetClassNameString("Action");
            _node119.SetId(0x71);
            selector11.AddChild(_node119);
            selector11.SetHasEvents(selector11.HasEvents() | _node119.HasEvents());
            sequence32.SetHasEvents(sequence32.HasEvents() | selector11.HasEvents());
            DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node114 _node120 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node114();
            _node120.SetClassNameString("DecoratorLoop");
            _node120.SetId(0x72);
            sequence32.AddChild(_node120);
            Noop noop3 = new Noop();
            noop3.SetClassNameString("Noop");
            noop3.SetId(0x73);
            _node120.AddChild(noop3);
            _node120.SetHasEvents(_node120.HasEvents() | noop3.HasEvents());
            sequence32.SetHasEvents(sequence32.HasEvents() | _node120.HasEvents());
            precondition3.SetHasEvents(precondition3.HasEvents() | sequence32.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition3.HasEvents());
            WithPrecondition precondition4 = new WithPrecondition();
            precondition4.SetClassNameString("WithPrecondition");
            precondition4.SetId(450);
            loop.AddChild(precondition4);
            Condition_bt_WrapperAI_Soldier_BTSoldierPro_node454 _node121 = new Condition_bt_WrapperAI_Soldier_BTSoldierPro_node454();
            _node121.SetClassNameString("Condition");
            _node121.SetId(0x1c6);
            precondition4.AddChild(_node121);
            precondition4.SetHasEvents(precondition4.HasEvents() | _node121.HasEvents());
            Sequence sequence33 = new Sequence();
            sequence33.SetClassNameString("Sequence");
            sequence33.SetId(0x1c7);
            precondition4.AddChild(sequence33);
            Action_bt_WrapperAI_Soldier_BTSoldierPro_node456 _node122 = new Action_bt_WrapperAI_Soldier_BTSoldierPro_node456();
            _node122.SetClassNameString("Action");
            _node122.SetId(0x1c8);
            sequence33.AddChild(_node122);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node122.HasEvents());
            DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node457 _node123 = new DecoratorLoop_bt_WrapperAI_Soldier_BTSoldierPro_node457();
            _node123.SetClassNameString("DecoratorLoop");
            _node123.SetId(0x1c9);
            sequence33.AddChild(_node123);
            Noop noop4 = new Noop();
            noop4.SetClassNameString("Noop");
            noop4.SetId(0x1ca);
            _node123.AddChild(noop4);
            _node123.SetHasEvents(_node123.HasEvents() | noop4.HasEvents());
            sequence33.SetHasEvents(sequence33.HasEvents() | _node123.HasEvents());
            precondition4.SetHasEvents(precondition4.HasEvents() | sequence33.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition4.HasEvents());
            _node3.SetHasEvents(_node3.HasEvents() | loop.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | _node3.HasEvents());
            bt.SetHasEvents(bt.HasEvents() | pChild.HasEvents());
            return true;
        }
    }
}

