namespace behaviac
{
    using System;

    public static class bt_WrapperAI_Organ_CrystalWithAttack
    {
        public static bool build_behavior_tree(BehaviorTree bt)
        {
            bt.SetClassNameString("BehaviorTree");
            bt.SetId(-1);
            bt.SetName("WrapperAI/Organ/CrystalWithAttack");
            bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
            bt.AddPar("uint", "p_targetID", "0", string.Empty);
            bt.AddPar("int", "p_srchRange", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
            bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
            bt.AddPar("uint", "p_CmdID", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            DecoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node14 pChild = new DecoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node14();
            pChild.SetClassNameString("DecoratorLoop");
            pChild.SetId(14);
            bt.AddChild(pChild);
            Sequence sequence = new Sequence();
            sequence.SetClassNameString("Sequence");
            sequence.SetId(0);
            pChild.AddChild(sequence);
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node82 _node2 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node82();
            _node2.SetClassNameString("Assignment");
            _node2.SetId(0x52);
            sequence.AddChild(_node2);
            sequence.SetHasEvents(sequence.HasEvents() | _node2.HasEvents());
            SelectorLoop loop = new SelectorLoop();
            loop.SetClassNameString("SelectorLoop");
            loop.SetId(1);
            sequence.AddChild(loop);
            WithPrecondition precondition = new WithPrecondition();
            precondition.SetClassNameString("WithPrecondition");
            precondition.SetId(0x1a);
            loop.AddChild(precondition);
            Sequence sequence2 = new Sequence();
            sequence2.SetClassNameString("Sequence");
            sequence2.SetId(0xfe);
            precondition.AddChild(sequence2);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node255 _node3 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node255();
            _node3.SetClassNameString("Condition");
            _node3.SetId(0xff);
            sequence2.AddChild(_node3);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node3.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node256 _node4 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node256();
            _node4.SetClassNameString("Action");
            _node4.SetId(0x100);
            sequence2.AddChild(_node4);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node4.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node260 _node5 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node260();
            _node5.SetClassNameString("Action");
            _node5.SetId(260);
            sequence2.AddChild(_node5);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node5.HasEvents());
            precondition.SetHasEvents(precondition.HasEvents() | sequence2.HasEvents());
            False @false = new False();
            @false.SetClassNameString("False");
            @false.SetId(0xfc);
            precondition.AddChild(@false);
            precondition.SetHasEvents(precondition.HasEvents() | @false.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition.HasEvents());
            WithPrecondition precondition2 = new WithPrecondition();
            precondition2.SetClassNameString("WithPrecondition");
            precondition2.SetId(11);
            loop.AddChild(precondition2);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node12 _node6 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node12();
            _node6.SetClassNameString("Condition");
            _node6.SetId(12);
            precondition2.AddChild(_node6);
            precondition2.SetHasEvents(precondition2.HasEvents() | _node6.HasEvents());
            Sequence sequence3 = new Sequence();
            sequence3.SetClassNameString("Sequence");
            sequence3.SetId(13);
            precondition2.AddChild(sequence3);
            IfElse @else = new IfElse();
            @else.SetClassNameString("IfElse");
            @else.SetId(9);
            sequence3.AddChild(@else);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node15 _node7 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node15();
            _node7.SetClassNameString("Condition");
            _node7.SetId(15);
            @else.AddChild(_node7);
            @else.SetHasEvents(@else.HasEvents() | _node7.HasEvents());
            Sequence sequence4 = new Sequence();
            sequence4.SetClassNameString("Sequence");
            sequence4.SetId(0x11);
            @else.AddChild(sequence4);
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node16 _node8 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node16();
            _node8.SetClassNameString("Action");
            _node8.SetId(0x10);
            sequence4.AddChild(_node8);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node8.HasEvents());
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node18 _node9 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node18();
            _node9.SetClassNameString("Assignment");
            _node9.SetId(0x12);
            sequence4.AddChild(_node9);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node9.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | sequence4.HasEvents());
            Noop noop = new Noop();
            noop.SetClassNameString("Noop");
            noop.SetId(0x13);
            @else.AddChild(noop);
            @else.SetHasEvents(@else.HasEvents() | noop.HasEvents());
            sequence3.SetHasEvents(sequence3.HasEvents() | @else.HasEvents());
            Sequence sequence5 = new Sequence();
            sequence5.SetClassNameString("Sequence");
            sequence5.SetId(0x51);
            sequence3.AddChild(sequence5);
            IfElse else2 = new IfElse();
            else2.SetClassNameString("IfElse");
            else2.SetId(10);
            sequence5.AddChild(else2);
            And and = new And();
            and.SetClassNameString("And");
            and.SetId(0x15);
            else2.AddChild(and);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node20 _node10 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node20();
            _node10.SetClassNameString("Condition");
            _node10.SetId(20);
            and.AddChild(_node10);
            and.SetHasEvents(and.HasEvents() | _node10.HasEvents());
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node22 _node11 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node22();
            _node11.SetClassNameString("Condition");
            _node11.SetId(0x16);
            and.AddChild(_node11);
            and.SetHasEvents(and.HasEvents() | _node11.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | and.HasEvents());
            Noop noop2 = new Noop();
            noop2.SetClassNameString("Noop");
            noop2.SetId(0x17);
            else2.AddChild(noop2);
            else2.SetHasEvents(else2.HasEvents() | noop2.HasEvents());
            Sequence sequence6 = new Sequence();
            sequence6.SetClassNameString("Sequence");
            sequence6.SetId(0x18);
            else2.AddChild(sequence6);
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node25 _node12 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node25();
            _node12.SetClassNameString("Action");
            _node12.SetId(0x19);
            sequence6.AddChild(_node12);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node12.HasEvents());
            Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node83 _node13 = new Assignment_bt_WrapperAI_Organ_CrystalWithAttack_node83();
            _node13.SetClassNameString("Assignment");
            _node13.SetId(0x53);
            sequence6.AddChild(_node13);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node13.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | sequence6.HasEvents());
            sequence5.SetHasEvents(sequence5.HasEvents() | else2.HasEvents());
            IfElse else3 = new IfElse();
            else3.SetClassNameString("IfElse");
            else3.SetId(0x54);
            sequence5.AddChild(else3);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node85 _node14 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node85();
            _node14.SetClassNameString("Condition");
            _node14.SetId(0x55);
            else3.AddChild(_node14);
            else3.SetHasEvents(else3.HasEvents() | _node14.HasEvents());
            Sequence sequence7 = new Sequence();
            sequence7.SetClassNameString("Sequence");
            sequence7.SetId(0x56);
            else3.AddChild(sequence7);
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node140 _node15 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node140();
            _node15.SetClassNameString("Action");
            _node15.SetId(140);
            sequence7.AddChild(_node15);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node15.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node87 _node16 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node87();
            _node16.SetClassNameString("Action");
            _node16.SetId(0x57);
            sequence7.AddChild(_node16);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node16.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node88 _node17 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node88();
            _node17.SetClassNameString("Action");
            _node17.SetId(0x58);
            sequence7.AddChild(_node17);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node17.HasEvents());
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node91 _node18 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node91();
            _node18.SetClassNameString("Action");
            _node18.SetId(0x5b);
            sequence7.AddChild(_node18);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node18.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node92 _node19 = new DecoratorLoopUntil_bt_WrapperAI_Organ_CrystalWithAttack_node92();
            _node19.SetClassNameString("DecoratorLoopUntil");
            _node19.SetId(0x5c);
            sequence7.AddChild(_node19);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node93 _node20 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node93();
            _node20.SetClassNameString("Condition");
            _node20.SetId(0x5d);
            _node19.AddChild(_node20);
            _node19.SetHasEvents(_node19.HasEvents() | _node20.HasEvents());
            sequence7.SetHasEvents(sequence7.HasEvents() | _node19.HasEvents());
            else3.SetHasEvents(else3.HasEvents() | sequence7.HasEvents());
            WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node5 _node21 = new WaitFrames_bt_WrapperAI_Organ_CrystalWithAttack_node5();
            _node21.SetClassNameString("WaitFrames");
            _node21.SetId(5);
            else3.AddChild(_node21);
            else3.SetHasEvents(else3.HasEvents() | _node21.HasEvents());
            sequence5.SetHasEvents(sequence5.HasEvents() | else3.HasEvents());
            sequence3.SetHasEvents(sequence3.HasEvents() | sequence5.HasEvents());
            precondition2.SetHasEvents(precondition2.HasEvents() | sequence3.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition2.HasEvents());
            WithPrecondition precondition3 = new WithPrecondition();
            precondition3.SetClassNameString("WithPrecondition");
            precondition3.SetId(2);
            loop.AddChild(precondition3);
            Condition_bt_WrapperAI_Organ_CrystalWithAttack_node3 _node22 = new Condition_bt_WrapperAI_Organ_CrystalWithAttack_node3();
            _node22.SetClassNameString("Condition");
            _node22.SetId(3);
            precondition3.AddChild(_node22);
            precondition3.SetHasEvents(precondition3.HasEvents() | _node22.HasEvents());
            Sequence sequence8 = new Sequence();
            sequence8.SetClassNameString("Sequence");
            sequence8.SetId(6);
            precondition3.AddChild(sequence8);
            Action_bt_WrapperAI_Organ_CrystalWithAttack_node4 _node23 = new Action_bt_WrapperAI_Organ_CrystalWithAttack_node4();
            _node23.SetClassNameString("Action");
            _node23.SetId(4);
            sequence8.AddChild(_node23);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node23.HasEvents());
            DecoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node7 _node24 = new DecoratorLoop_bt_WrapperAI_Organ_CrystalWithAttack_node7();
            _node24.SetClassNameString("DecoratorLoop");
            _node24.SetId(7);
            sequence8.AddChild(_node24);
            Noop noop3 = new Noop();
            noop3.SetClassNameString("Noop");
            noop3.SetId(8);
            _node24.AddChild(noop3);
            _node24.SetHasEvents(_node24.HasEvents() | noop3.HasEvents());
            sequence8.SetHasEvents(sequence8.HasEvents() | _node24.HasEvents());
            precondition3.SetHasEvents(precondition3.HasEvents() | sequence8.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition3.HasEvents());
            sequence.SetHasEvents(sequence.HasEvents() | loop.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | sequence.HasEvents());
            bt.SetHasEvents(bt.HasEvents() | pChild.HasEvents());
            return true;
        }
    }
}

