namespace behaviac
{
    using System;

    public static class bt_WrapperAI_Monster_BTMonsterBaozou
    {
        public static bool build_behavior_tree(BehaviorTree bt)
        {
            bt.SetClassNameString("BehaviorTree");
            bt.SetId(-1);
            bt.SetName("WrapperAI/Monster/BTMonsterBaozou");
            bt.AddPar("uint", "p_targetID", "0", string.Empty);
            bt.AddPar("int", "p_srchRange", "0", string.Empty);
            bt.AddPar("uint", "p_selfID", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_targetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_randomIndex", "0", string.Empty);
            Sequence pChild = new Sequence();
            pChild.SetClassNameString("Sequence");
            pChild.SetId(0);
            bt.AddChild(pChild);
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node4 _node = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node4();
            _node.SetClassNameString("Assignment");
            _node.SetId(4);
            pChild.AddChild(_node);
            pChild.SetHasEvents(pChild.HasEvents() | _node.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node98 _node2 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node98();
            _node2.SetClassNameString("Assignment");
            _node2.SetId(0x62);
            pChild.AddChild(_node2);
            pChild.SetHasEvents(pChild.HasEvents() | _node2.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node48 _node3 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node48();
            _node3.SetClassNameString("Assignment");
            _node3.SetId(0x30);
            pChild.AddChild(_node3);
            pChild.SetHasEvents(pChild.HasEvents() | _node3.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node11 _node4 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node11();
            _node4.SetClassNameString("Assignment");
            _node4.SetId(11);
            pChild.AddChild(_node4);
            pChild.SetHasEvents(pChild.HasEvents() | _node4.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node14 _node5 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node14();
            _node5.SetClassNameString("DecoratorLoop");
            _node5.SetId(14);
            pChild.AddChild(_node5);
            SelectorLoop loop = new SelectorLoop();
            loop.SetClassNameString("SelectorLoop");
            loop.SetId(1);
            _node5.AddChild(loop);
            WithPrecondition precondition = new WithPrecondition();
            precondition.SetClassNameString("WithPrecondition");
            precondition.SetId(60);
            loop.AddChild(precondition);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node61 _node6 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node61();
            _node6.SetClassNameString("Condition");
            _node6.SetId(0x3d);
            precondition.AddChild(_node6);
            precondition.SetHasEvents(precondition.HasEvents() | _node6.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node3 _node7 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node3();
            _node7.SetClassNameString("Action");
            _node7.SetId(3);
            precondition.AddChild(_node7);
            precondition.SetHasEvents(precondition.HasEvents() | _node7.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition.HasEvents());
            WithPrecondition precondition2 = new WithPrecondition();
            precondition2.SetClassNameString("WithPrecondition");
            precondition2.SetId(70);
            loop.AddChild(precondition2);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node71 _node8 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node71();
            _node8.SetClassNameString("Condition");
            _node8.SetId(0x47);
            precondition2.AddChild(_node8);
            precondition2.SetHasEvents(precondition2.HasEvents() | _node8.HasEvents());
            Sequence sequence2 = new Sequence();
            sequence2.SetClassNameString("Sequence");
            sequence2.SetId(12);
            precondition2.AddChild(sequence2);
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node462 _node9 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node462();
            _node9.SetClassNameString("Action");
            _node9.SetId(0x1ce);
            sequence2.AddChild(_node9);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node9.HasEvents());
            IfElse @else = new IfElse();
            @else.SetClassNameString("IfElse");
            @else.SetId(5);
            sequence2.AddChild(@else);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node336 _node10 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node336();
            _node10.SetClassNameString("Condition");
            _node10.SetId(0x150);
            @else.AddChild(_node10);
            @else.SetHasEvents(@else.HasEvents() | _node10.HasEvents());
            Sequence sequence3 = new Sequence();
            sequence3.SetClassNameString("Sequence");
            sequence3.SetId(6);
            @else.AddChild(sequence3);
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node7 _node11 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node7();
            _node11.SetClassNameString("Assignment");
            _node11.SetId(7);
            sequence3.AddChild(_node11);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node11.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node8 _node12 = new Assignment_bt_WrapperAI_Monster_BTMonsterBaozou_node8();
            _node12.SetClassNameString("Assignment");
            _node12.SetId(8);
            sequence3.AddChild(_node12);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node12.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | sequence3.HasEvents());
            Noop noop = new Noop();
            noop.SetClassNameString("Noop");
            noop.SetId(13);
            @else.AddChild(noop);
            @else.SetHasEvents(@else.HasEvents() | noop.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | @else.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node15 _node13 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node15();
            _node13.SetClassNameString("Action");
            _node13.SetId(15);
            sequence2.AddChild(_node13);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node13.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node438 _node14 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node438();
            _node14.SetClassNameString("Action");
            _node14.SetId(0x1b6);
            sequence2.AddChild(_node14);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node14.HasEvents());
            precondition2.SetHasEvents(precondition2.HasEvents() | sequence2.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition2.HasEvents());
            WithPrecondition precondition3 = new WithPrecondition();
            precondition3.SetClassNameString("WithPrecondition");
            precondition3.SetId(0x203);
            loop.AddChild(precondition3);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node516 _node15 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node516();
            _node15.SetClassNameString("Condition");
            _node15.SetId(0x204);
            precondition3.AddChild(_node15);
            precondition3.SetHasEvents(precondition3.HasEvents() | _node15.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node9 _node16 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node9();
            _node16.SetClassNameString("Action");
            _node16.SetId(9);
            precondition3.AddChild(_node16);
            precondition3.SetHasEvents(precondition3.HasEvents() | _node16.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition3.HasEvents());
            WithPrecondition precondition4 = new WithPrecondition();
            precondition4.SetClassNameString("WithPrecondition");
            precondition4.SetId(0x18);
            loop.AddChild(precondition4);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node25 _node17 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node25();
            _node17.SetClassNameString("Condition");
            _node17.SetId(0x19);
            precondition4.AddChild(_node17);
            precondition4.SetHasEvents(precondition4.HasEvents() | _node17.HasEvents());
            Sequence sequence4 = new Sequence();
            sequence4.SetClassNameString("Sequence");
            sequence4.SetId(0x3b);
            precondition4.AddChild(sequence4);
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node488 _node18 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node488();
            _node18.SetClassNameString("Action");
            _node18.SetId(0x1e8);
            sequence4.AddChild(_node18);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node18.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node65 _node19 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node65();
            _node19.SetClassNameString("DecoratorLoop");
            _node19.SetId(0x41);
            sequence4.AddChild(_node19);
            Noop noop2 = new Noop();
            noop2.SetClassNameString("Noop");
            noop2.SetId(0x21);
            _node19.AddChild(noop2);
            _node19.SetHasEvents(_node19.HasEvents() | noop2.HasEvents());
            sequence4.SetHasEvents(sequence4.HasEvents() | _node19.HasEvents());
            precondition4.SetHasEvents(precondition4.HasEvents() | sequence4.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition4.HasEvents());
            WithPrecondition precondition5 = new WithPrecondition();
            precondition5.SetClassNameString("WithPrecondition");
            precondition5.SetId(0x22);
            loop.AddChild(precondition5);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node40 _node20 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node40();
            _node20.SetClassNameString("Condition");
            _node20.SetId(40);
            precondition5.AddChild(_node20);
            precondition5.SetHasEvents(precondition5.HasEvents() | _node20.HasEvents());
            Sequence sequence5 = new Sequence();
            sequence5.SetClassNameString("Sequence");
            sequence5.SetId(0x29);
            precondition5.AddChild(sequence5);
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node42 _node21 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node42();
            _node21.SetClassNameString("Action");
            _node21.SetId(0x2a);
            sequence5.AddChild(_node21);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node21.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node43 _node22 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node43();
            _node22.SetClassNameString("DecoratorLoop");
            _node22.SetId(0x2b);
            sequence5.AddChild(_node22);
            Noop noop3 = new Noop();
            noop3.SetClassNameString("Noop");
            noop3.SetId(0x1ca);
            _node22.AddChild(noop3);
            _node22.SetHasEvents(_node22.HasEvents() | noop3.HasEvents());
            sequence5.SetHasEvents(sequence5.HasEvents() | _node22.HasEvents());
            precondition5.SetHasEvents(precondition5.HasEvents() | sequence5.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition5.HasEvents());
            WithPrecondition precondition6 = new WithPrecondition();
            precondition6.SetClassNameString("WithPrecondition");
            precondition6.SetId(450);
            loop.AddChild(precondition6);
            Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node454 _node23 = new Condition_bt_WrapperAI_Monster_BTMonsterBaozou_node454();
            _node23.SetClassNameString("Condition");
            _node23.SetId(0x1c6);
            precondition6.AddChild(_node23);
            precondition6.SetHasEvents(precondition6.HasEvents() | _node23.HasEvents());
            Sequence sequence6 = new Sequence();
            sequence6.SetClassNameString("Sequence");
            sequence6.SetId(0x1c7);
            precondition6.AddChild(sequence6);
            Action_bt_WrapperAI_Monster_BTMonsterBaozou_node456 _node24 = new Action_bt_WrapperAI_Monster_BTMonsterBaozou_node456();
            _node24.SetClassNameString("Action");
            _node24.SetId(0x1c8);
            sequence6.AddChild(_node24);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node24.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node457 _node25 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterBaozou_node457();
            _node25.SetClassNameString("DecoratorLoop");
            _node25.SetId(0x1c9);
            sequence6.AddChild(_node25);
            Noop noop4 = new Noop();
            noop4.SetClassNameString("Noop");
            noop4.SetId(2);
            _node25.AddChild(noop4);
            _node25.SetHasEvents(_node25.HasEvents() | noop4.HasEvents());
            sequence6.SetHasEvents(sequence6.HasEvents() | _node25.HasEvents());
            precondition6.SetHasEvents(precondition6.HasEvents() | sequence6.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition6.HasEvents());
            _node5.SetHasEvents(_node5.HasEvents() | loop.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | _node5.HasEvents());
            bt.SetHasEvents(bt.HasEvents() | pChild.HasEvents());
            return true;
        }
    }
}

