namespace behaviac
{
    using System;

    public static class bt_WrapperAI_Hero_HeroLowAI
    {
        public static bool build_behavior_tree(BehaviorTree bt)
        {
            bt.SetClassNameString("BehaviorTree");
            bt.SetId(-1);
            bt.SetName("WrapperAI/Hero/HeroLowAI");
            bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
            bt.AddPar("uint", "p_targetID", "0", string.Empty);
            bt.AddPar("int", "p_srchRange", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
            bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
            bt.AddPar("uint", "p_CmdID", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_restorePos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_healthRate", "1000", string.Empty);
            bt.AddPar("int", "p_skillAttackRange", "0", string.Empty);
            bt.AddPar("uint", "p_captainID", "0", string.Empty);
            bt.AddPar("uint", "p_nearstMember", "0", string.Empty);
            bt.AddPar("bool", "p_forceToApproachHero", "false", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_direction", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_useSkillWeight", "100", string.Empty);
            bt.AddPar("int", "p_pursueFrame", "0", string.Empty);
            bt.AddPar("uint", "p_abandonTargetID", "0", string.Empty);
            bt.AddPar("uint", "p_selfID", "0", string.Empty);
            bt.AddPar("int", "p_waitToPlayBornAge", "0", string.Empty);
            bt.AddPar("int", "p_waitBornFrame", "0", string.Empty);
            bt.AddPar("uint", "p_teamTarget", "0", string.Empty);
            Sequence pChild = new Sequence();
            pChild.SetClassNameString("Sequence");
            pChild.SetId(0x19b);
            bt.AddChild(pChild);
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node414 _node = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node414();
            _node.SetClassNameString("Assignment");
            _node.SetId(0x19e);
            pChild.AddChild(_node);
            pChild.SetHasEvents(pChild.HasEvents() | _node.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node436 _node2 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node436();
            _node2.SetClassNameString("Assignment");
            _node2.SetId(0x1b4);
            pChild.AddChild(_node2);
            pChild.SetHasEvents(pChild.HasEvents() | _node2.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node486 _node3 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node486();
            _node3.SetClassNameString("Assignment");
            _node3.SetId(0x1e6);
            pChild.AddChild(_node3);
            pChild.SetHasEvents(pChild.HasEvents() | _node3.HasEvents());
            IfElse @else = new IfElse();
            @else.SetClassNameString("IfElse");
            @else.SetId(0x412);
            pChild.AddChild(@else);
            Action_bt_WrapperAI_Hero_HeroLowAI_node77 _node4 = new Action_bt_WrapperAI_Hero_HeroLowAI_node77();
            _node4.SetClassNameString("Action");
            _node4.SetId(0x4d);
            @else.AddChild(_node4);
            @else.SetHasEvents(@else.HasEvents() | _node4.HasEvents());
            Sequence sequence2 = new Sequence();
            sequence2.SetClassNameString("Sequence");
            sequence2.SetId(0x413);
            @else.AddChild(sequence2);
            Compute_bt_WrapperAI_Hero_HeroLowAI_node1044 _node5 = new Compute_bt_WrapperAI_Hero_HeroLowAI_node1044();
            _node5.SetClassNameString("Compute");
            _node5.SetId(0x414);
            sequence2.AddChild(_node5);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node5.HasEvents());
            Compute_bt_WrapperAI_Hero_HeroLowAI_node1045 _node6 = new Compute_bt_WrapperAI_Hero_HeroLowAI_node1045();
            _node6.SetClassNameString("Compute");
            _node6.SetId(0x415);
            sequence2.AddChild(_node6);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node6.HasEvents());
            Compute_bt_WrapperAI_Hero_HeroLowAI_node100 _node7 = new Compute_bt_WrapperAI_Hero_HeroLowAI_node100();
            _node7.SetClassNameString("Compute");
            _node7.SetId(100);
            sequence2.AddChild(_node7);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node7.HasEvents());
            Compute_bt_WrapperAI_Hero_HeroLowAI_node101 _node8 = new Compute_bt_WrapperAI_Hero_HeroLowAI_node101();
            _node8.SetClassNameString("Compute");
            _node8.SetId(0x65);
            sequence2.AddChild(_node8);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node8.HasEvents());
            IfElse else2 = new IfElse();
            else2.SetClassNameString("IfElse");
            else2.SetId(0x40c);
            sequence2.AddChild(else2);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node1037 _node9 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node1037();
            _node9.SetClassNameString("Condition");
            _node9.SetId(0x40d);
            else2.AddChild(_node9);
            else2.SetHasEvents(else2.HasEvents() | _node9.HasEvents());
            Sequence sequence3 = new Sequence();
            sequence3.SetClassNameString("Sequence");
            sequence3.SetId(0x410);
            else2.AddChild(sequence3);
            Compute_bt_WrapperAI_Hero_HeroLowAI_node1038 _node10 = new Compute_bt_WrapperAI_Hero_HeroLowAI_node1038();
            _node10.SetClassNameString("Compute");
            _node10.SetId(0x40e);
            sequence3.AddChild(_node10);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node10.HasEvents());
            Compute_bt_WrapperAI_Hero_HeroLowAI_node1050 _node11 = new Compute_bt_WrapperAI_Hero_HeroLowAI_node1050();
            _node11.SetClassNameString("Compute");
            _node11.SetId(0x41a);
            sequence3.AddChild(_node11);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node11.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | sequence3.HasEvents());
            Noop noop = new Noop();
            noop.SetClassNameString("Noop");
            noop.SetId(0x40f);
            else2.AddChild(noop);
            else2.SetHasEvents(else2.HasEvents() | noop.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | else2.HasEvents());
            Parallel_bt_WrapperAI_Hero_HeroLowAI_node1046 _node12 = new Parallel_bt_WrapperAI_Hero_HeroLowAI_node1046();
            _node12.SetClassNameString("Parallel");
            _node12.SetId(0x416);
            sequence2.AddChild(_node12);
            Sequence sequence4 = new Sequence();
            sequence4.SetClassNameString("Sequence");
            sequence4.SetId(0x417);
            _node12.AddChild(sequence4);
            WaitFrames_bt_WrapperAI_Hero_HeroLowAI_node1048 _node13 = new WaitFrames_bt_WrapperAI_Hero_HeroLowAI_node1048();
            _node13.SetClassNameString("WaitFrames");
            _node13.SetId(0x418);
            sequence4.AddChild(_node13);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node13.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node1049 _node14 = new Action_bt_WrapperAI_Hero_HeroLowAI_node1049();
            _node14.SetClassNameString("Action");
            _node14.SetId(0x419);
            sequence4.AddChild(_node14);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node14.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node87 _node15 = new Action_bt_WrapperAI_Hero_HeroLowAI_node87();
            _node15.SetClassNameString("Action");
            _node15.SetId(0x57);
            sequence4.AddChild(_node15);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node15.HasEvents());
            _node12.SetHasEvents(_node12.HasEvents() | sequence4.HasEvents());
            WaitFrames_bt_WrapperAI_Hero_HeroLowAI_node1051 _node16 = new WaitFrames_bt_WrapperAI_Hero_HeroLowAI_node1051();
            _node16.SetClassNameString("WaitFrames");
            _node16.SetId(0x41b);
            _node12.AddChild(_node16);
            _node12.SetHasEvents(_node12.HasEvents() | _node16.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | _node12.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | sequence2.HasEvents());
            Noop noop2 = new Noop();
            noop2.SetClassNameString("Noop");
            noop2.SetId(0x403);
            @else.AddChild(noop2);
            @else.SetHasEvents(@else.HasEvents() | noop2.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | @else.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node1035 _node17 = new Action_bt_WrapperAI_Hero_HeroLowAI_node1035();
            _node17.SetClassNameString("Action");
            _node17.SetId(0x40b);
            pChild.AddChild(_node17);
            pChild.SetHasEvents(pChild.HasEvents() | _node17.HasEvents());
            IfElse else3 = new IfElse();
            else3.SetClassNameString("IfElse");
            else3.SetId(0x225);
            pChild.AddChild(else3);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node553 _node18 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node553();
            _node18.SetClassNameString("Condition");
            _node18.SetId(0x229);
            else3.AddChild(_node18);
            else3.SetHasEvents(else3.HasEvents() | _node18.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Hero_HeroLowAI_node546 _node19 = new DecoratorLoopUntil_bt_WrapperAI_Hero_HeroLowAI_node546();
            _node19.SetClassNameString("DecoratorLoopUntil");
            _node19.SetId(0x222);
            else3.AddChild(_node19);
            Sequence sequence5 = new Sequence();
            sequence5.SetClassNameString("Sequence");
            sequence5.SetId(0x22a);
            _node19.AddChild(sequence5);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node555 _node20 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node555();
            _node20.SetClassNameString("Condition");
            _node20.SetId(0x22b);
            sequence5.AddChild(_node20);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node20.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node556 _node21 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node556();
            _node21.SetClassNameString("Condition");
            _node21.SetId(0x22c);
            sequence5.AddChild(_node21);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node21.HasEvents());
            _node19.SetHasEvents(_node19.HasEvents() | sequence5.HasEvents());
            else3.SetHasEvents(else3.HasEvents() | _node19.HasEvents());
            Noop noop3 = new Noop();
            noop3.SetClassNameString("Noop");
            noop3.SetId(0x227);
            else3.AddChild(noop3);
            else3.SetHasEvents(else3.HasEvents() | noop3.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | else3.HasEvents());
            DecoratorLoop_bt_WrapperAI_Hero_HeroLowAI_node14 _node22 = new DecoratorLoop_bt_WrapperAI_Hero_HeroLowAI_node14();
            _node22.SetClassNameString("DecoratorLoop");
            _node22.SetId(14);
            pChild.AddChild(_node22);
            Sequence sequence6 = new Sequence();
            sequence6.SetClassNameString("Sequence");
            sequence6.SetId(0x45);
            _node22.AddChild(sequence6);
            IfElse else4 = new IfElse();
            else4.SetClassNameString("IfElse");
            else4.SetId(0xcd);
            sequence6.AddChild(else4);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node207 _node23 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node207();
            _node23.SetClassNameString("Condition");
            _node23.SetId(0xcf);
            else4.AddChild(_node23);
            else4.SetHasEvents(else4.HasEvents() | _node23.HasEvents());
            Noop noop4 = new Noop();
            noop4.SetClassNameString("Noop");
            noop4.SetId(210);
            else4.AddChild(noop4);
            else4.SetHasEvents(else4.HasEvents() | noop4.HasEvents());
            Sequence sequence7 = new Sequence();
            sequence7.SetClassNameString("Sequence");
            sequence7.SetId(0xd3);
            else4.AddChild(sequence7);
            IfElse else5 = new IfElse();
            else5.SetClassNameString("IfElse");
            else5.SetId(0xe0);
            sequence7.AddChild(else5);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node232 _node24 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node232();
            _node24.SetClassNameString("Condition");
            _node24.SetId(0xe8);
            else5.AddChild(_node24);
            else5.SetHasEvents(else5.HasEvents() | _node24.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node233 _node25 = new Action_bt_WrapperAI_Hero_HeroLowAI_node233();
            _node25.SetClassNameString("Action");
            _node25.SetId(0xe9);
            else5.AddChild(_node25);
            else5.SetHasEvents(else5.HasEvents() | _node25.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node511 _node26 = new Action_bt_WrapperAI_Hero_HeroLowAI_node511();
            _node26.SetClassNameString("Action");
            _node26.SetId(0x1ff);
            else5.AddChild(_node26);
            else5.SetHasEvents(else5.HasEvents() | _node26.HasEvents());
            sequence7.SetHasEvents(sequence7.HasEvents() | else5.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node235 _node27 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node235();
            _node27.SetClassNameString("Assignment");
            _node27.SetId(0xeb);
            sequence7.AddChild(_node27);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node27.HasEvents());
            else4.SetHasEvents(else4.HasEvents() | sequence7.HasEvents());
            sequence6.SetHasEvents(sequence6.HasEvents() | else4.HasEvents());
            SelectorLoop loop = new SelectorLoop();
            loop.SetClassNameString("SelectorLoop");
            loop.SetId(1);
            sequence6.AddChild(loop);
            WithPrecondition precondition = new WithPrecondition();
            precondition.SetClassNameString("WithPrecondition");
            precondition.SetId(0);
            loop.AddChild(precondition);
            Sequence sequence8 = new Sequence();
            sequence8.SetClassNameString("Sequence");
            sequence8.SetId(0xfe);
            precondition.AddChild(sequence8);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node255 _node28 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node255();
            _node28.SetClassNameString("Condition");
            _node28.SetId(0xff);
            sequence8.AddChild(_node28);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node28.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node256 _node29 = new Action_bt_WrapperAI_Hero_HeroLowAI_node256();
            _node29.SetClassNameString("Action");
            _node29.SetId(0x100);
            sequence8.AddChild(_node29);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node29.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node260 _node30 = new Action_bt_WrapperAI_Hero_HeroLowAI_node260();
            _node30.SetClassNameString("Action");
            _node30.SetId(260);
            sequence8.AddChild(_node30);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node30.HasEvents());
            precondition.SetHasEvents(precondition.HasEvents() | sequence8.HasEvents());
            Noop noop5 = new Noop();
            noop5.SetClassNameString("Noop");
            noop5.SetId(0xfc);
            precondition.AddChild(noop5);
            precondition.SetHasEvents(precondition.HasEvents() | noop5.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition.HasEvents());
            WithPrecondition precondition2 = new WithPrecondition();
            precondition2.SetClassNameString("WithPrecondition");
            precondition2.SetId(0x6b);
            loop.AddChild(precondition2);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node108 _node31 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node108();
            _node31.SetClassNameString("Condition");
            _node31.SetId(0x6c);
            precondition2.AddChild(_node31);
            precondition2.SetHasEvents(precondition2.HasEvents() | _node31.HasEvents());
            Sequence sequence9 = new Sequence();
            sequence9.SetClassNameString("Sequence");
            sequence9.SetId(0xd0);
            precondition2.AddChild(sequence9);
            Parallel_bt_WrapperAI_Hero_HeroLowAI_node184 _node32 = new Parallel_bt_WrapperAI_Hero_HeroLowAI_node184();
            _node32.SetClassNameString("Parallel");
            _node32.SetId(0xb8);
            sequence9.AddChild(_node32);
            SelectorLoop loop2 = new SelectorLoop();
            loop2.SetClassNameString("SelectorLoop");
            loop2.SetId(0x68);
            _node32.AddChild(loop2);
            WithPrecondition precondition3 = new WithPrecondition();
            precondition3.SetClassNameString("WithPrecondition");
            precondition3.SetId(70);
            loop2.AddChild(precondition3);
            True @true = new True();
            @true.SetClassNameString("True");
            @true.SetId(0x80);
            precondition3.AddChild(@true);
            precondition3.SetHasEvents(precondition3.HasEvents() | @true.HasEvents());
            Sequence sequence10 = new Sequence();
            sequence10.SetClassNameString("Sequence");
            sequence10.SetId(0xba);
            precondition3.AddChild(sequence10);
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node183 _node33 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node183();
            _node33.SetClassNameString("Assignment");
            _node33.SetId(0xb7);
            sequence10.AddChild(_node33);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node33.HasEvents());
            Sequence sequence11 = new Sequence();
            sequence11.SetClassNameString("Sequence");
            sequence11.SetId(0x69);
            sequence10.AddChild(sequence11);
            IfElse else6 = new IfElse();
            else6.SetClassNameString("IfElse");
            else6.SetId(0x243);
            sequence11.AddChild(else6);
            Selector selector = new Selector();
            selector.SetClassNameString("Selector");
            selector.SetId(580);
            else6.AddChild(selector);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node189 _node34 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node189();
            _node34.SetClassNameString("Condition");
            _node34.SetId(0xbd);
            selector.AddChild(_node34);
            selector.SetHasEvents(selector.HasEvents() | _node34.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node581 _node35 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node581();
            _node35.SetClassNameString("Condition");
            _node35.SetId(0x245);
            selector.AddChild(_node35);
            selector.SetHasEvents(selector.HasEvents() | _node35.HasEvents());
            Sequence sequence12 = new Sequence();
            sequence12.SetClassNameString("Sequence");
            sequence12.SetId(110);
            selector.AddChild(sequence12);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node582 _node36 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node582();
            _node36.SetClassNameString("Condition");
            _node36.SetId(0x246);
            sequence12.AddChild(_node36);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node36.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node187 _node37 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node187();
            _node37.SetClassNameString("Assignment");
            _node37.SetId(0xbb);
            sequence12.AddChild(_node37);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node37.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence12.HasEvents());
            else6.SetHasEvents(else6.HasEvents() | selector.HasEvents());
            DecoratorAlwaysSuccess_bt_WrapperAI_Hero_HeroLowAI_node585 _node38 = new DecoratorAlwaysSuccess_bt_WrapperAI_Hero_HeroLowAI_node585();
            _node38.SetClassNameString("DecoratorAlwaysSuccess");
            _node38.SetId(0x249);
            else6.AddChild(_node38);
            Sequence sequence13 = new Sequence();
            sequence13.SetClassNameString("Sequence");
            sequence13.SetId(0x24a);
            _node38.AddChild(sequence13);
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node587 _node39 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node587();
            _node39.SetClassNameString("Assignment");
            _node39.SetId(0x24b);
            sequence13.AddChild(_node39);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node39.HasEvents());
            IfElse else7 = new IfElse();
            else7.SetClassNameString("IfElse");
            else7.SetId(0x24c);
            sequence13.AddChild(else7);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node589 _node40 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node589();
            _node40.SetClassNameString("Condition");
            _node40.SetId(0x24d);
            else7.AddChild(_node40);
            else7.SetHasEvents(else7.HasEvents() | _node40.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node590 _node41 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node590();
            _node41.SetClassNameString("Assignment");
            _node41.SetId(590);
            else7.AddChild(_node41);
            else7.SetHasEvents(else7.HasEvents() | _node41.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node591 _node42 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node591();
            _node42.SetClassNameString("Assignment");
            _node42.SetId(0x24f);
            else7.AddChild(_node42);
            else7.SetHasEvents(else7.HasEvents() | _node42.HasEvents());
            sequence13.SetHasEvents(sequence13.HasEvents() | else7.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node593 _node43 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node593();
            _node43.SetClassNameString("Condition");
            _node43.SetId(0x251);
            sequence13.AddChild(_node43);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node43.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node594 _node44 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node594();
            _node44.SetClassNameString("Assignment");
            _node44.SetId(0x252);
            sequence13.AddChild(_node44);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node44.HasEvents());
            _node38.SetHasEvents(_node38.HasEvents() | sequence13.HasEvents());
            else6.SetHasEvents(else6.HasEvents() | _node38.HasEvents());
            Noop noop6 = new Noop();
            noop6.SetClassNameString("Noop");
            noop6.SetId(0x253);
            else6.AddChild(noop6);
            else6.SetHasEvents(else6.HasEvents() | noop6.HasEvents());
            sequence11.SetHasEvents(sequence11.HasEvents() | else6.HasEvents());
            IfElse else8 = new IfElse();
            else8.SetClassNameString("IfElse");
            else8.SetId(0x47);
            sequence11.AddChild(else8);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node109 _node45 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node109();
            _node45.SetClassNameString("Condition");
            _node45.SetId(0x6d);
            else8.AddChild(_node45);
            else8.SetHasEvents(else8.HasEvents() | _node45.HasEvents());
            Sequence sequence14 = new Sequence();
            sequence14.SetClassNameString("Sequence");
            sequence14.SetId(0x9a);
            else8.AddChild(sequence14);
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node188 _node46 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node188();
            _node46.SetClassNameString("Assignment");
            _node46.SetId(0xbc);
            sequence14.AddChild(_node46);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node46.HasEvents());
            Selector selector2 = new Selector();
            selector2.SetClassNameString("Selector");
            selector2.SetId(0x98);
            sequence14.AddChild(selector2);
            SelectorProbability_bt_WrapperAI_Hero_HeroLowAI_node469 _node47 = new SelectorProbability_bt_WrapperAI_Hero_HeroLowAI_node469();
            _node47.SetClassNameString("SelectorProbability");
            _node47.SetId(0x1d5);
            selector2.AddChild(_node47);
            DecoratorWeight_bt_WrapperAI_Hero_HeroLowAI_node380 pBehavior = new DecoratorWeight_bt_WrapperAI_Hero_HeroLowAI_node380();
            pBehavior.SetClassNameString("DecoratorWeight");
            pBehavior.SetId(380);
            _node47.AddChild(pBehavior);
            SelectorStochastic_bt_WrapperAI_Hero_HeroLowAI_node381 _node49 = new SelectorStochastic_bt_WrapperAI_Hero_HeroLowAI_node381();
            _node49.SetClassNameString("SelectorStochastic");
            _node49.SetId(0x17d);
            pBehavior.AddChild(_node49);
            Sequence sequence15 = new Sequence();
            sequence15.SetClassNameString("Sequence");
            sequence15.SetId(0x99);
            _node49.AddChild(sequence15);
            Action_bt_WrapperAI_Hero_HeroLowAI_node156 _node50 = new Action_bt_WrapperAI_Hero_HeroLowAI_node156();
            _node50.SetClassNameString("Action");
            _node50.SetId(0x9c);
            sequence15.AddChild(_node50);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node50.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node159 _node51 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node159();
            _node51.SetClassNameString("Assignment");
            _node51.SetId(0x9f);
            sequence15.AddChild(_node51);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node51.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node160 _node52 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node160();
            _node52.SetClassNameString("Assignment");
            _node52.SetId(160);
            sequence15.AddChild(_node52);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node52.HasEvents());
            Selector selector3 = new Selector();
            selector3.SetClassNameString("Selector");
            selector3.SetId(0x11);
            sequence15.AddChild(selector3);
            Sequence sequence16 = new Sequence();
            sequence16.SetClassNameString("Sequence");
            sequence16.SetId(0x58);
            selector3.AddChild(sequence16);
            Action_bt_WrapperAI_Hero_HeroLowAI_node712 _node53 = new Action_bt_WrapperAI_Hero_HeroLowAI_node712();
            _node53.SetClassNameString("Action");
            _node53.SetId(0x2c8);
            sequence16.AddChild(_node53);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node53.HasEvents());
            Selector selector4 = new Selector();
            selector4.SetClassNameString("Selector");
            selector4.SetId(0x59);
            sequence16.AddChild(selector4);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node90 _node54 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node90();
            _node54.SetClassNameString("Condition");
            _node54.SetId(90);
            selector4.AddChild(_node54);
            selector4.SetHasEvents(selector4.HasEvents() | _node54.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node91 _node55 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node91();
            _node55.SetClassNameString("Condition");
            _node55.SetId(0x5b);
            selector4.AddChild(_node55);
            selector4.SetHasEvents(selector4.HasEvents() | _node55.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node92 _node56 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node92();
            _node56.SetClassNameString("Condition");
            _node56.SetId(0x5c);
            selector4.AddChild(_node56);
            selector4.SetHasEvents(selector4.HasEvents() | _node56.HasEvents());
            sequence16.SetHasEvents(sequence16.HasEvents() | selector4.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node97 _node57 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node97();
            _node57.SetClassNameString("Condition");
            _node57.SetId(0x61);
            sequence16.AddChild(_node57);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node57.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node11 _node58 = new Action_bt_WrapperAI_Hero_HeroLowAI_node11();
            _node58.SetClassNameString("Action");
            _node58.SetId(11);
            sequence16.AddChild(_node58);
            sequence16.SetHasEvents(sequence16.HasEvents() | _node58.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence16.HasEvents());
            Sequence sequence17 = new Sequence();
            sequence17.SetClassNameString("Sequence");
            sequence17.SetId(13);
            selector3.AddChild(sequence17);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node98 _node59 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node98();
            _node59.SetClassNameString("Condition");
            _node59.SetId(0x62);
            sequence17.AddChild(_node59);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node59.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node9 _node60 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node9();
            _node60.SetClassNameString("Assignment");
            _node60.SetId(9);
            sequence17.AddChild(_node60);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node60.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node10 _node61 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node10();
            _node61.SetClassNameString("Condition");
            _node61.SetId(10);
            sequence17.AddChild(_node61);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node61.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node12 _node62 = new Action_bt_WrapperAI_Hero_HeroLowAI_node12();
            _node62.SetClassNameString("Action");
            _node62.SetId(12);
            sequence17.AddChild(_node62);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node62.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence17.HasEvents());
            Sequence sequence18 = new Sequence();
            sequence18.SetClassNameString("Sequence");
            sequence18.SetId(0x12);
            selector3.AddChild(sequence18);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node19 _node63 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node19();
            _node63.SetClassNameString("Condition");
            _node63.SetId(0x13);
            sequence18.AddChild(_node63);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node63.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node15 _node64 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node15();
            _node64.SetClassNameString("Condition");
            _node64.SetId(15);
            sequence18.AddChild(_node64);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node64.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node16 _node65 = new Action_bt_WrapperAI_Hero_HeroLowAI_node16();
            _node65.SetClassNameString("Action");
            _node65.SetId(0x10);
            sequence18.AddChild(_node65);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node65.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence18.HasEvents());
            sequence15.SetHasEvents(sequence15.HasEvents() | selector3.HasEvents());
            _node49.SetHasEvents(_node49.HasEvents() | sequence15.HasEvents());
            Sequence sequence19 = new Sequence();
            sequence19.SetClassNameString("Sequence");
            sequence19.SetId(0xa1);
            _node49.AddChild(sequence19);
            Action_bt_WrapperAI_Hero_HeroLowAI_node93 _node66 = new Action_bt_WrapperAI_Hero_HeroLowAI_node93();
            _node66.SetClassNameString("Action");
            _node66.SetId(0x5d);
            sequence19.AddChild(_node66);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node66.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node162 _node67 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node162();
            _node67.SetClassNameString("Assignment");
            _node67.SetId(0xa2);
            sequence19.AddChild(_node67);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node67.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node166 _node68 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node166();
            _node68.SetClassNameString("Assignment");
            _node68.SetId(0xa6);
            sequence19.AddChild(_node68);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node68.HasEvents());
            Selector selector5 = new Selector();
            selector5.SetClassNameString("Selector");
            selector5.SetId(0x14b);
            sequence19.AddChild(selector5);
            Sequence sequence20 = new Sequence();
            sequence20.SetClassNameString("Sequence");
            sequence20.SetId(20);
            selector5.AddChild(sequence20);
            Action_bt_WrapperAI_Hero_HeroLowAI_node21 _node69 = new Action_bt_WrapperAI_Hero_HeroLowAI_node21();
            _node69.SetClassNameString("Action");
            _node69.SetId(0x15);
            sequence20.AddChild(_node69);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node69.HasEvents());
            Selector selector6 = new Selector();
            selector6.SetClassNameString("Selector");
            selector6.SetId(0x16);
            sequence20.AddChild(selector6);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node23 _node70 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node23();
            _node70.SetClassNameString("Condition");
            _node70.SetId(0x17);
            selector6.AddChild(_node70);
            selector6.SetHasEvents(selector6.HasEvents() | _node70.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node24 _node71 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node24();
            _node71.SetClassNameString("Condition");
            _node71.SetId(0x18);
            selector6.AddChild(_node71);
            selector6.SetHasEvents(selector6.HasEvents() | _node71.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node25 _node72 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node25();
            _node72.SetClassNameString("Condition");
            _node72.SetId(0x19);
            selector6.AddChild(_node72);
            selector6.SetHasEvents(selector6.HasEvents() | _node72.HasEvents());
            sequence20.SetHasEvents(sequence20.HasEvents() | selector6.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node26 _node73 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node26();
            _node73.SetClassNameString("Condition");
            _node73.SetId(0x1a);
            sequence20.AddChild(_node73);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node73.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node27 _node74 = new Action_bt_WrapperAI_Hero_HeroLowAI_node27();
            _node74.SetClassNameString("Action");
            _node74.SetId(0x1b);
            sequence20.AddChild(_node74);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node74.HasEvents());
            selector5.SetHasEvents(selector5.HasEvents() | sequence20.HasEvents());
            Sequence sequence21 = new Sequence();
            sequence21.SetClassNameString("Sequence");
            sequence21.SetId(0x1c);
            selector5.AddChild(sequence21);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node29 _node75 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node29();
            _node75.SetClassNameString("Condition");
            _node75.SetId(0x1d);
            sequence21.AddChild(_node75);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node75.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node30 _node76 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node30();
            _node76.SetClassNameString("Assignment");
            _node76.SetId(30);
            sequence21.AddChild(_node76);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node76.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node31 _node77 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node31();
            _node77.SetClassNameString("Condition");
            _node77.SetId(0x1f);
            sequence21.AddChild(_node77);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node77.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node32 _node78 = new Action_bt_WrapperAI_Hero_HeroLowAI_node32();
            _node78.SetClassNameString("Action");
            _node78.SetId(0x20);
            sequence21.AddChild(_node78);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node78.HasEvents());
            selector5.SetHasEvents(selector5.HasEvents() | sequence21.HasEvents());
            Sequence sequence22 = new Sequence();
            sequence22.SetClassNameString("Sequence");
            sequence22.SetId(0x21);
            selector5.AddChild(sequence22);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node34 _node79 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node34();
            _node79.SetClassNameString("Condition");
            _node79.SetId(0x22);
            sequence22.AddChild(_node79);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node79.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node35 _node80 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node35();
            _node80.SetClassNameString("Condition");
            _node80.SetId(0x23);
            sequence22.AddChild(_node80);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node80.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node36 _node81 = new Action_bt_WrapperAI_Hero_HeroLowAI_node36();
            _node81.SetClassNameString("Action");
            _node81.SetId(0x24);
            sequence22.AddChild(_node81);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node81.HasEvents());
            selector5.SetHasEvents(selector5.HasEvents() | sequence22.HasEvents());
            sequence19.SetHasEvents(sequence19.HasEvents() | selector5.HasEvents());
            _node49.SetHasEvents(_node49.HasEvents() | sequence19.HasEvents());
            Sequence sequence23 = new Sequence();
            sequence23.SetClassNameString("Sequence");
            sequence23.SetId(0xa7);
            _node49.AddChild(sequence23);
            Action_bt_WrapperAI_Hero_HeroLowAI_node94 _node82 = new Action_bt_WrapperAI_Hero_HeroLowAI_node94();
            _node82.SetClassNameString("Action");
            _node82.SetId(0x5e);
            sequence23.AddChild(_node82);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node82.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node168 _node83 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node168();
            _node83.SetClassNameString("Assignment");
            _node83.SetId(0xa8);
            sequence23.AddChild(_node83);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node83.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node172 _node84 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node172();
            _node84.SetClassNameString("Assignment");
            _node84.SetId(0xac);
            sequence23.AddChild(_node84);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node84.HasEvents());
            Selector selector7 = new Selector();
            selector7.SetClassNameString("Selector");
            selector7.SetId(0x14c);
            sequence23.AddChild(selector7);
            Sequence sequence24 = new Sequence();
            sequence24.SetClassNameString("Sequence");
            sequence24.SetId(0x25);
            selector7.AddChild(sequence24);
            Action_bt_WrapperAI_Hero_HeroLowAI_node38 _node85 = new Action_bt_WrapperAI_Hero_HeroLowAI_node38();
            _node85.SetClassNameString("Action");
            _node85.SetId(0x26);
            sequence24.AddChild(_node85);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node85.HasEvents());
            Selector selector8 = new Selector();
            selector8.SetClassNameString("Selector");
            selector8.SetId(0x27);
            sequence24.AddChild(selector8);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node40 _node86 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node40();
            _node86.SetClassNameString("Condition");
            _node86.SetId(40);
            selector8.AddChild(_node86);
            selector8.SetHasEvents(selector8.HasEvents() | _node86.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node41 _node87 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node41();
            _node87.SetClassNameString("Condition");
            _node87.SetId(0x29);
            selector8.AddChild(_node87);
            selector8.SetHasEvents(selector8.HasEvents() | _node87.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node42 _node88 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node42();
            _node88.SetClassNameString("Condition");
            _node88.SetId(0x2a);
            selector8.AddChild(_node88);
            selector8.SetHasEvents(selector8.HasEvents() | _node88.HasEvents());
            sequence24.SetHasEvents(sequence24.HasEvents() | selector8.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node43 _node89 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node43();
            _node89.SetClassNameString("Condition");
            _node89.SetId(0x2b);
            sequence24.AddChild(_node89);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node89.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node44 _node90 = new Action_bt_WrapperAI_Hero_HeroLowAI_node44();
            _node90.SetClassNameString("Action");
            _node90.SetId(0x2c);
            sequence24.AddChild(_node90);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node90.HasEvents());
            selector7.SetHasEvents(selector7.HasEvents() | sequence24.HasEvents());
            Sequence sequence25 = new Sequence();
            sequence25.SetClassNameString("Sequence");
            sequence25.SetId(0x2d);
            selector7.AddChild(sequence25);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node46 _node91 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node46();
            _node91.SetClassNameString("Condition");
            _node91.SetId(0x2e);
            sequence25.AddChild(_node91);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node91.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node47 _node92 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node47();
            _node92.SetClassNameString("Assignment");
            _node92.SetId(0x2f);
            sequence25.AddChild(_node92);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node92.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node48 _node93 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node48();
            _node93.SetClassNameString("Condition");
            _node93.SetId(0x30);
            sequence25.AddChild(_node93);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node93.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node49 _node94 = new Action_bt_WrapperAI_Hero_HeroLowAI_node49();
            _node94.SetClassNameString("Action");
            _node94.SetId(0x31);
            sequence25.AddChild(_node94);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node94.HasEvents());
            selector7.SetHasEvents(selector7.HasEvents() | sequence25.HasEvents());
            Sequence sequence26 = new Sequence();
            sequence26.SetClassNameString("Sequence");
            sequence26.SetId(50);
            selector7.AddChild(sequence26);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node51 _node95 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node51();
            _node95.SetClassNameString("Condition");
            _node95.SetId(0x33);
            sequence26.AddChild(_node95);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node95.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node52 _node96 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node52();
            _node96.SetClassNameString("Condition");
            _node96.SetId(0x34);
            sequence26.AddChild(_node96);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node96.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node53 _node97 = new Action_bt_WrapperAI_Hero_HeroLowAI_node53();
            _node97.SetClassNameString("Action");
            _node97.SetId(0x35);
            sequence26.AddChild(_node97);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node97.HasEvents());
            selector7.SetHasEvents(selector7.HasEvents() | sequence26.HasEvents());
            sequence23.SetHasEvents(sequence23.HasEvents() | selector7.HasEvents());
            _node49.SetHasEvents(_node49.HasEvents() | sequence23.HasEvents());
            pBehavior.SetHasEvents(pBehavior.HasEvents() | _node49.HasEvents());
            _node47.SetHasEvents(_node47.HasEvents() | pBehavior.HasEvents());
            DecoratorWeight_bt_WrapperAI_Hero_HeroLowAI_node473 _node98 = new DecoratorWeight_bt_WrapperAI_Hero_HeroLowAI_node473();
            _node98.SetClassNameString("DecoratorWeight");
            _node98.SetId(0x1d9);
            _node47.AddChild(_node98);
            False @false = new False();
            @false.SetClassNameString("False");
            @false.SetId(0x1da);
            _node98.AddChild(@false);
            _node98.SetHasEvents(_node98.HasEvents() | @false.HasEvents());
            _node47.SetHasEvents(_node47.HasEvents() | _node98.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | _node47.HasEvents());
            Sequence sequence27 = new Sequence();
            sequence27.SetClassNameString("Sequence");
            sequence27.SetId(0xad);
            selector2.AddChild(sequence27);
            Action_bt_WrapperAI_Hero_HeroLowAI_node95 _node99 = new Action_bt_WrapperAI_Hero_HeroLowAI_node95();
            _node99.SetClassNameString("Action");
            _node99.SetId(0x5f);
            sequence27.AddChild(_node99);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node99.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node174 _node100 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node174();
            _node100.SetClassNameString("Assignment");
            _node100.SetId(0xae);
            sequence27.AddChild(_node100);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node100.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node178 _node101 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node178();
            _node101.SetClassNameString("Assignment");
            _node101.SetId(0xb2);
            sequence27.AddChild(_node101);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node101.HasEvents());
            Selector selector9 = new Selector();
            selector9.SetClassNameString("Selector");
            selector9.SetId(0x14d);
            sequence27.AddChild(selector9);
            Sequence sequence28 = new Sequence();
            sequence28.SetClassNameString("Sequence");
            sequence28.SetId(0x36);
            selector9.AddChild(sequence28);
            Action_bt_WrapperAI_Hero_HeroLowAI_node55 _node102 = new Action_bt_WrapperAI_Hero_HeroLowAI_node55();
            _node102.SetClassNameString("Action");
            _node102.SetId(0x37);
            sequence28.AddChild(_node102);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node102.HasEvents());
            Selector selector10 = new Selector();
            selector10.SetClassNameString("Selector");
            selector10.SetId(0x38);
            sequence28.AddChild(selector10);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node57 _node103 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node57();
            _node103.SetClassNameString("Condition");
            _node103.SetId(0x39);
            selector10.AddChild(_node103);
            selector10.SetHasEvents(selector10.HasEvents() | _node103.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node58 _node104 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node58();
            _node104.SetClassNameString("Condition");
            _node104.SetId(0x3a);
            selector10.AddChild(_node104);
            selector10.SetHasEvents(selector10.HasEvents() | _node104.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node102 _node105 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node102();
            _node105.SetClassNameString("Condition");
            _node105.SetId(0x66);
            selector10.AddChild(_node105);
            selector10.SetHasEvents(selector10.HasEvents() | _node105.HasEvents());
            sequence28.SetHasEvents(sequence28.HasEvents() | selector10.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node103 _node106 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node103();
            _node106.SetClassNameString("Condition");
            _node106.SetId(0x67);
            sequence28.AddChild(_node106);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node106.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node106 _node107 = new Action_bt_WrapperAI_Hero_HeroLowAI_node106();
            _node107.SetClassNameString("Action");
            _node107.SetId(0x6a);
            sequence28.AddChild(_node107);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node107.HasEvents());
            selector9.SetHasEvents(selector9.HasEvents() | sequence28.HasEvents());
            Sequence sequence29 = new Sequence();
            sequence29.SetClassNameString("Sequence");
            sequence29.SetId(0x3e);
            selector9.AddChild(sequence29);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node63 _node108 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node63();
            _node108.SetClassNameString("Condition");
            _node108.SetId(0x3f);
            sequence29.AddChild(_node108);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node108.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node111 _node109 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node111();
            _node109.SetClassNameString("Assignment");
            _node109.SetId(0x6f);
            sequence29.AddChild(_node109);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node109.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node112 _node110 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node112();
            _node110.SetClassNameString("Condition");
            _node110.SetId(0x70);
            sequence29.AddChild(_node110);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node110.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node113 _node111 = new Action_bt_WrapperAI_Hero_HeroLowAI_node113();
            _node111.SetClassNameString("Action");
            _node111.SetId(0x71);
            sequence29.AddChild(_node111);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node111.HasEvents());
            selector9.SetHasEvents(selector9.HasEvents() | sequence29.HasEvents());
            Sequence sequence30 = new Sequence();
            sequence30.SetClassNameString("Sequence");
            sequence30.SetId(0x43);
            selector9.AddChild(sequence30);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node68 _node112 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node68();
            _node112.SetClassNameString("Condition");
            _node112.SetId(0x44);
            sequence30.AddChild(_node112);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node112.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node114 _node113 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node114();
            _node113.SetClassNameString("Condition");
            _node113.SetId(0x72);
            sequence30.AddChild(_node113);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node113.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node73 _node114 = new Action_bt_WrapperAI_Hero_HeroLowAI_node73();
            _node114.SetClassNameString("Action");
            _node114.SetId(0x49);
            sequence30.AddChild(_node114);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node114.HasEvents());
            selector9.SetHasEvents(selector9.HasEvents() | sequence30.HasEvents());
            sequence27.SetHasEvents(sequence27.HasEvents() | selector9.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence27.HasEvents());
            IfElse else9 = new IfElse();
            else9.SetClassNameString("IfElse");
            else9.SetId(0x7f);
            selector2.AddChild(else9);
            Sequence sequence31 = new Sequence();
            sequence31.SetClassNameString("Sequence");
            sequence31.SetId(0x119);
            else9.AddChild(sequence31);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node429 _node115 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node429();
            _node115.SetClassNameString("Condition");
            _node115.SetId(0x1ad);
            sequence31.AddChild(_node115);
            sequence31.SetHasEvents(sequence31.HasEvents() | _node115.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node430 _node116 = new Action_bt_WrapperAI_Hero_HeroLowAI_node430();
            _node116.SetClassNameString("Action");
            _node116.SetId(430);
            sequence31.AddChild(_node116);
            sequence31.SetHasEvents(sequence31.HasEvents() | _node116.HasEvents());
            else9.SetHasEvents(else9.HasEvents() | sequence31.HasEvents());
            Sequence sequence32 = new Sequence();
            sequence32.SetClassNameString("Sequence");
            sequence32.SetId(0x1af);
            else9.AddChild(sequence32);
            Compute_bt_WrapperAI_Hero_HeroLowAI_node575 _node117 = new Compute_bt_WrapperAI_Hero_HeroLowAI_node575();
            _node117.SetClassNameString("Compute");
            _node117.SetId(0x23f);
            sequence32.AddChild(_node117);
            sequence32.SetHasEvents(sequence32.HasEvents() | _node117.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node432 _node118 = new Action_bt_WrapperAI_Hero_HeroLowAI_node432();
            _node118.SetClassNameString("Action");
            _node118.SetId(0x1b0);
            sequence32.AddChild(_node118);
            sequence32.SetHasEvents(sequence32.HasEvents() | _node118.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node438 _node119 = new Action_bt_WrapperAI_Hero_HeroLowAI_node438();
            _node119.SetClassNameString("Action");
            _node119.SetId(0x1b6);
            sequence32.AddChild(_node119);
            sequence32.SetHasEvents(sequence32.HasEvents() | _node119.HasEvents());
            else9.SetHasEvents(else9.HasEvents() | sequence32.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node439 _node120 = new Action_bt_WrapperAI_Hero_HeroLowAI_node439();
            _node120.SetClassNameString("Action");
            _node120.SetId(0x1b7);
            else9.AddChild(_node120);
            else9.SetHasEvents(else9.HasEvents() | _node120.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | else9.HasEvents());
            sequence14.SetHasEvents(sequence14.HasEvents() | selector2.HasEvents());
            Sequence sequence33 = new Sequence();
            sequence33.SetClassNameString("Sequence");
            sequence33.SetId(0x48);
            sequence14.AddChild(sequence33);
            Action_bt_WrapperAI_Hero_HeroLowAI_node74 _node121 = new Action_bt_WrapperAI_Hero_HeroLowAI_node74();
            _node121.SetClassNameString("Action");
            _node121.SetId(0x4a);
            sequence33.AddChild(_node121);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node121.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node78 _node122 = new Action_bt_WrapperAI_Hero_HeroLowAI_node78();
            _node122.SetClassNameString("Action");
            _node122.SetId(0x4e);
            sequence33.AddChild(_node122);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node122.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Hero_HeroLowAI_node99 _node123 = new DecoratorLoopUntil_bt_WrapperAI_Hero_HeroLowAI_node99();
            _node123.SetClassNameString("DecoratorLoopUntil");
            _node123.SetId(0x63);
            sequence33.AddChild(_node123);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node132 _node124 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node132();
            _node124.SetClassNameString("Condition");
            _node124.SetId(0x84);
            _node123.AddChild(_node124);
            _node123.SetHasEvents(_node123.HasEvents() | _node124.HasEvents());
            sequence33.SetHasEvents(sequence33.HasEvents() | _node123.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node576 _node125 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node576();
            _node125.SetClassNameString("Assignment");
            _node125.SetId(0x240);
            sequence33.AddChild(_node125);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node125.HasEvents());
            sequence14.SetHasEvents(sequence14.HasEvents() | sequence33.HasEvents());
            else8.SetHasEvents(else8.HasEvents() | sequence14.HasEvents());
            Selector selector11 = new Selector();
            selector11.SetClassNameString("Selector");
            selector11.SetId(0xd6);
            else8.AddChild(selector11);
            Sequence sequence34 = new Sequence();
            sequence34.SetClassNameString("Sequence");
            sequence34.SetId(0xd7);
            selector11.AddChild(sequence34);
            Or or = new Or();
            or.SetClassNameString("Or");
            or.SetId(0xd9);
            sequence34.AddChild(or);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node96 _node126 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node96();
            _node126.SetClassNameString("Condition");
            _node126.SetId(0x60);
            or.AddChild(_node126);
            or.SetHasEvents(or.HasEvents() | _node126.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node216 _node127 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node216();
            _node127.SetClassNameString("Condition");
            _node127.SetId(0xd8);
            or.AddChild(_node127);
            or.SetHasEvents(or.HasEvents() | _node127.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node218 _node128 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node218();
            _node128.SetClassNameString("Condition");
            _node128.SetId(0xda);
            or.AddChild(_node128);
            or.SetHasEvents(or.HasEvents() | _node128.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node346 _node129 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node346();
            _node129.SetClassNameString("Condition");
            _node129.SetId(0x15a);
            or.AddChild(_node129);
            or.SetHasEvents(or.HasEvents() | _node129.HasEvents());
            sequence34.SetHasEvents(sequence34.HasEvents() | or.HasEvents());
            IfElse else10 = new IfElse();
            else10.SetClassNameString("IfElse");
            else10.SetId(0x85);
            sequence34.AddChild(else10);
            And and = new And();
            and.SetClassNameString("And");
            and.SetId(0x18c);
            else10.AddChild(and);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node134 _node130 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node134();
            _node130.SetClassNameString("Condition");
            _node130.SetId(0x86);
            and.AddChild(_node130);
            and.SetHasEvents(and.HasEvents() | _node130.HasEvents());
            Or or2 = new Or();
            or2.SetClassNameString("Or");
            or2.SetId(0x18d);
            and.AddChild(or2);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node398 _node131 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node398();
            _node131.SetClassNameString("Condition");
            _node131.SetId(0x18e);
            or2.AddChild(_node131);
            or2.SetHasEvents(or2.HasEvents() | _node131.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node399 _node132 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node399();
            _node132.SetClassNameString("Condition");
            _node132.SetId(0x18f);
            or2.AddChild(_node132);
            or2.SetHasEvents(or2.HasEvents() | _node132.HasEvents());
            Condition_bt_WrapperAI_Hero_HeroLowAI_node400 _node133 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node400();
            _node133.SetClassNameString("Condition");
            _node133.SetId(400);
            or2.AddChild(_node133);
            or2.SetHasEvents(or2.HasEvents() | _node133.HasEvents());
            and.SetHasEvents(and.HasEvents() | or2.HasEvents());
            else10.SetHasEvents(else10.HasEvents() | and.HasEvents());
            Sequence sequence35 = new Sequence();
            sequence35.SetClassNameString("Sequence");
            sequence35.SetId(0x87);
            else10.AddChild(sequence35);
            Action_bt_WrapperAI_Hero_HeroLowAI_node462 _node134 = new Action_bt_WrapperAI_Hero_HeroLowAI_node462();
            _node134.SetClassNameString("Action");
            _node134.SetId(0x1ce);
            sequence35.AddChild(_node134);
            sequence35.SetHasEvents(sequence35.HasEvents() | _node134.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node136 _node135 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node136();
            _node135.SetClassNameString("Assignment");
            _node135.SetId(0x88);
            sequence35.AddChild(_node135);
            sequence35.SetHasEvents(sequence35.HasEvents() | _node135.HasEvents());
            IfElse else11 = new IfElse();
            else11.SetClassNameString("IfElse");
            else11.SetId(0x147);
            sequence35.AddChild(else11);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node328 _node136 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node328();
            _node136.SetClassNameString("Condition");
            _node136.SetId(0x148);
            else11.AddChild(_node136);
            else11.SetHasEvents(else11.HasEvents() | _node136.HasEvents());
            IfElse else12 = new IfElse();
            else12.SetClassNameString("IfElse");
            else12.SetId(0x14f);
            else11.AddChild(else12);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node336 _node137 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node336();
            _node137.SetClassNameString("Condition");
            _node137.SetId(0x150);
            else12.AddChild(_node137);
            else12.SetHasEvents(else12.HasEvents() | _node137.HasEvents());
            Sequence sequence36 = new Sequence();
            sequence36.SetClassNameString("Sequence");
            sequence36.SetId(0x151);
            else12.AddChild(sequence36);
            Action_bt_WrapperAI_Hero_HeroLowAI_node338 _node138 = new Action_bt_WrapperAI_Hero_HeroLowAI_node338();
            _node138.SetClassNameString("Action");
            _node138.SetId(0x152);
            sequence36.AddChild(_node138);
            sequence36.SetHasEvents(sequence36.HasEvents() | _node138.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node339 _node139 = new Action_bt_WrapperAI_Hero_HeroLowAI_node339();
            _node139.SetClassNameString("Action");
            _node139.SetId(0x153);
            sequence36.AddChild(_node139);
            sequence36.SetHasEvents(sequence36.HasEvents() | _node139.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node452 _node140 = new Action_bt_WrapperAI_Hero_HeroLowAI_node452();
            _node140.SetClassNameString("Action");
            _node140.SetId(0x1c4);
            sequence36.AddChild(_node140);
            sequence36.SetHasEvents(sequence36.HasEvents() | _node140.HasEvents());
            WaitFrames_bt_WrapperAI_Hero_HeroLowAI_node445 _node141 = new WaitFrames_bt_WrapperAI_Hero_HeroLowAI_node445();
            _node141.SetClassNameString("WaitFrames");
            _node141.SetId(0x1bd);
            sequence36.AddChild(_node141);
            sequence36.SetHasEvents(sequence36.HasEvents() | _node141.HasEvents());
            else12.SetHasEvents(else12.HasEvents() | sequence36.HasEvents());
            Sequence sequence37 = new Sequence();
            sequence37.SetClassNameString("Sequence");
            sequence37.SetId(340);
            else12.AddChild(sequence37);
            Action_bt_WrapperAI_Hero_HeroLowAI_node444 _node142 = new Action_bt_WrapperAI_Hero_HeroLowAI_node444();
            _node142.SetClassNameString("Action");
            _node142.SetId(0x1bc);
            sequence37.AddChild(_node142);
            sequence37.SetHasEvents(sequence37.HasEvents() | _node142.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node341 _node143 = new Action_bt_WrapperAI_Hero_HeroLowAI_node341();
            _node143.SetClassNameString("Action");
            _node143.SetId(0x155);
            sequence37.AddChild(_node143);
            sequence37.SetHasEvents(sequence37.HasEvents() | _node143.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node342 _node144 = new Action_bt_WrapperAI_Hero_HeroLowAI_node342();
            _node144.SetClassNameString("Action");
            _node144.SetId(0x156);
            sequence37.AddChild(_node144);
            sequence37.SetHasEvents(sequence37.HasEvents() | _node144.HasEvents());
            DecoratorAlwaysSuccess_bt_WrapperAI_Hero_HeroLowAI_node540 _node145 = new DecoratorAlwaysSuccess_bt_WrapperAI_Hero_HeroLowAI_node540();
            _node145.SetClassNameString("DecoratorAlwaysSuccess");
            _node145.SetId(540);
            sequence37.AddChild(_node145);
            Sequence sequence38 = new Sequence();
            sequence38.SetClassNameString("Sequence");
            sequence38.SetId(0x21d);
            _node145.AddChild(sequence38);
            Action_bt_WrapperAI_Hero_HeroLowAI_node548 _node146 = new Action_bt_WrapperAI_Hero_HeroLowAI_node548();
            _node146.SetClassNameString("Action");
            _node146.SetId(0x224);
            sequence38.AddChild(_node146);
            sequence38.SetHasEvents(sequence38.HasEvents() | _node146.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node543 _node147 = new Action_bt_WrapperAI_Hero_HeroLowAI_node543();
            _node147.SetClassNameString("Action");
            _node147.SetId(0x21f);
            sequence38.AddChild(_node147);
            sequence38.SetHasEvents(sequence38.HasEvents() | _node147.HasEvents());
            _node145.SetHasEvents(_node145.HasEvents() | sequence38.HasEvents());
            sequence37.SetHasEvents(sequence37.HasEvents() | _node145.HasEvents());
            WaitFrames_bt_WrapperAI_Hero_HeroLowAI_node446 _node148 = new WaitFrames_bt_WrapperAI_Hero_HeroLowAI_node446();
            _node148.SetClassNameString("WaitFrames");
            _node148.SetId(0x1be);
            sequence37.AddChild(_node148);
            sequence37.SetHasEvents(sequence37.HasEvents() | _node148.HasEvents());
            else12.SetHasEvents(else12.HasEvents() | sequence37.HasEvents());
            else11.SetHasEvents(else11.HasEvents() | else12.HasEvents());
            Sequence sequence39 = new Sequence();
            sequence39.SetClassNameString("Sequence");
            sequence39.SetId(0x149);
            else11.AddChild(sequence39);
            Action_bt_WrapperAI_Hero_HeroLowAI_node447 _node149 = new Action_bt_WrapperAI_Hero_HeroLowAI_node447();
            _node149.SetClassNameString("Action");
            _node149.SetId(0x1bf);
            sequence39.AddChild(_node149);
            sequence39.SetHasEvents(sequence39.HasEvents() | _node149.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node137 _node150 = new Action_bt_WrapperAI_Hero_HeroLowAI_node137();
            _node150.SetClassNameString("Action");
            _node150.SetId(0x89);
            sequence39.AddChild(_node150);
            sequence39.SetHasEvents(sequence39.HasEvents() | _node150.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node138 _node151 = new Action_bt_WrapperAI_Hero_HeroLowAI_node138();
            _node151.SetClassNameString("Action");
            _node151.SetId(0x8a);
            sequence39.AddChild(_node151);
            sequence39.SetHasEvents(sequence39.HasEvents() | _node151.HasEvents());
            DecoratorAlwaysSuccess_bt_WrapperAI_Hero_HeroLowAI_node539 _node152 = new DecoratorAlwaysSuccess_bt_WrapperAI_Hero_HeroLowAI_node539();
            _node152.SetClassNameString("DecoratorAlwaysSuccess");
            _node152.SetId(0x21b);
            sequence39.AddChild(_node152);
            Sequence sequence40 = new Sequence();
            sequence40.SetClassNameString("Sequence");
            sequence40.SetId(0x20d);
            _node152.AddChild(sequence40);
            Action_bt_WrapperAI_Hero_HeroLowAI_node542 _node153 = new Action_bt_WrapperAI_Hero_HeroLowAI_node542();
            _node153.SetClassNameString("Action");
            _node153.SetId(0x21e);
            sequence40.AddChild(_node153);
            sequence40.SetHasEvents(sequence40.HasEvents() | _node153.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node528 _node154 = new Action_bt_WrapperAI_Hero_HeroLowAI_node528();
            _node154.SetClassNameString("Action");
            _node154.SetId(0x210);
            sequence40.AddChild(_node154);
            sequence40.SetHasEvents(sequence40.HasEvents() | _node154.HasEvents());
            _node152.SetHasEvents(_node152.HasEvents() | sequence40.HasEvents());
            sequence39.SetHasEvents(sequence39.HasEvents() | _node152.HasEvents());
            else11.SetHasEvents(else11.HasEvents() | sequence39.HasEvents());
            sequence35.SetHasEvents(sequence35.HasEvents() | else11.HasEvents());
            else10.SetHasEvents(else10.HasEvents() | sequence35.HasEvents());
            Sequence sequence41 = new Sequence();
            sequence41.SetClassNameString("Sequence");
            sequence41.SetId(0x8b);
            else10.AddChild(sequence41);
            Action_bt_WrapperAI_Hero_HeroLowAI_node141 _node155 = new Action_bt_WrapperAI_Hero_HeroLowAI_node141();
            _node155.SetClassNameString("Action");
            _node155.SetId(0x8d);
            sequence41.AddChild(_node155);
            sequence41.SetHasEvents(sequence41.HasEvents() | _node155.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node140 _node156 = new Action_bt_WrapperAI_Hero_HeroLowAI_node140();
            _node156.SetClassNameString("Action");
            _node156.SetId(140);
            sequence41.AddChild(_node156);
            sequence41.SetHasEvents(sequence41.HasEvents() | _node156.HasEvents());
            else10.SetHasEvents(else10.HasEvents() | sequence41.HasEvents());
            sequence34.SetHasEvents(sequence34.HasEvents() | else10.HasEvents());
            selector11.SetHasEvents(selector11.HasEvents() | sequence34.HasEvents());
            else8.SetHasEvents(else8.HasEvents() | selector11.HasEvents());
            sequence11.SetHasEvents(sequence11.HasEvents() | else8.HasEvents());
            sequence10.SetHasEvents(sequence10.HasEvents() | sequence11.HasEvents());
            precondition3.SetHasEvents(precondition3.HasEvents() | sequence10.HasEvents());
            loop2.SetHasEvents(loop2.HasEvents() | precondition3.HasEvents());
            _node32.SetHasEvents(_node32.HasEvents() | loop2.HasEvents());
            IfElse else13 = new IfElse();
            else13.SetClassNameString("IfElse");
            else13.SetId(0xb3);
            _node32.AddChild(else13);
            Sequence sequence42 = new Sequence();
            sequence42.SetClassNameString("Sequence");
            sequence42.SetId(0x1db);
            else13.AddChild(sequence42);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node180 _node157 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node180();
            _node157.SetClassNameString("Condition");
            _node157.SetId(180);
            sequence42.AddChild(_node157);
            sequence42.SetHasEvents(sequence42.HasEvents() | _node157.HasEvents());
            DecoratorNot_bt_WrapperAI_Hero_HeroLowAI_node477 _node158 = new DecoratorNot_bt_WrapperAI_Hero_HeroLowAI_node477();
            _node158.SetClassNameString("DecoratorNot");
            _node158.SetId(0x1dd);
            sequence42.AddChild(_node158);
            Action_bt_WrapperAI_Hero_HeroLowAI_node476 _node159 = new Action_bt_WrapperAI_Hero_HeroLowAI_node476();
            _node159.SetClassNameString("Action");
            _node159.SetId(0x1dc);
            _node158.AddChild(_node159);
            _node158.SetHasEvents(_node158.HasEvents() | _node159.HasEvents());
            sequence42.SetHasEvents(sequence42.HasEvents() | _node158.HasEvents());
            else13.SetHasEvents(else13.HasEvents() | sequence42.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node181 _node160 = new Action_bt_WrapperAI_Hero_HeroLowAI_node181();
            _node160.SetClassNameString("Action");
            _node160.SetId(0xb5);
            else13.AddChild(_node160);
            else13.SetHasEvents(else13.HasEvents() | _node160.HasEvents());
            Noop noop7 = new Noop();
            noop7.SetClassNameString("Noop");
            noop7.SetId(0xb6);
            else13.AddChild(noop7);
            else13.SetHasEvents(else13.HasEvents() | noop7.HasEvents());
            _node32.SetHasEvents(_node32.HasEvents() | else13.HasEvents());
            sequence9.SetHasEvents(sequence9.HasEvents() | _node32.HasEvents());
            precondition2.SetHasEvents(precondition2.HasEvents() | sequence9.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition2.HasEvents());
            WithPrecondition precondition4 = new WithPrecondition();
            precondition4.SetClassNameString("WithPrecondition");
            precondition4.SetId(60);
            loop.AddChild(precondition4);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node61 _node161 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node61();
            _node161.SetClassNameString("Condition");
            _node161.SetId(0x3d);
            precondition4.AddChild(_node161);
            precondition4.SetHasEvents(precondition4.HasEvents() | _node161.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node64 _node162 = new Action_bt_WrapperAI_Hero_HeroLowAI_node64();
            _node162.SetClassNameString("Action");
            _node162.SetId(0x40);
            precondition4.AddChild(_node162);
            precondition4.SetHasEvents(precondition4.HasEvents() | _node162.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition4.HasEvents());
            WithPrecondition precondition5 = new WithPrecondition();
            precondition5.SetClassNameString("WithPrecondition");
            precondition5.SetId(5);
            loop.AddChild(precondition5);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node6 _node163 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node6();
            _node163.SetClassNameString("Condition");
            _node163.SetId(6);
            precondition5.AddChild(_node163);
            precondition5.SetHasEvents(precondition5.HasEvents() | _node163.HasEvents());
            Sequence sequence43 = new Sequence();
            sequence43.SetClassNameString("Sequence");
            sequence43.SetId(8);
            precondition5.AddChild(sequence43);
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node559 _node164 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node559();
            _node164.SetClassNameString("Assignment");
            _node164.SetId(0x22f);
            sequence43.AddChild(_node164);
            sequence43.SetHasEvents(sequence43.HasEvents() | _node164.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node558 _node165 = new Action_bt_WrapperAI_Hero_HeroLowAI_node558();
            _node165.SetClassNameString("Action");
            _node165.SetId(0x22e);
            sequence43.AddChild(_node165);
            sequence43.SetHasEvents(sequence43.HasEvents() | _node165.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node80 _node166 = new Action_bt_WrapperAI_Hero_HeroLowAI_node80();
            _node166.SetClassNameString("Action");
            _node166.SetId(80);
            sequence43.AddChild(_node166);
            sequence43.SetHasEvents(sequence43.HasEvents() | _node166.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node7 _node167 = new Action_bt_WrapperAI_Hero_HeroLowAI_node7();
            _node167.SetClassNameString("Action");
            _node167.SetId(7);
            sequence43.AddChild(_node167);
            sequence43.SetHasEvents(sequence43.HasEvents() | _node167.HasEvents());
            DecoratorAlwaysSuccess_bt_WrapperAI_Hero_HeroLowAI_node544 _node168 = new DecoratorAlwaysSuccess_bt_WrapperAI_Hero_HeroLowAI_node544();
            _node168.SetClassNameString("DecoratorAlwaysSuccess");
            _node168.SetId(0x220);
            sequence43.AddChild(_node168);
            Sequence sequence44 = new Sequence();
            sequence44.SetClassNameString("Sequence");
            sequence44.SetId(0x221);
            _node168.AddChild(sequence44);
            Action_bt_WrapperAI_Hero_HeroLowAI_node527 _node169 = new Action_bt_WrapperAI_Hero_HeroLowAI_node527();
            _node169.SetClassNameString("Action");
            _node169.SetId(0x20f);
            sequence44.AddChild(_node169);
            sequence44.SetHasEvents(sequence44.HasEvents() | _node169.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node547 _node170 = new Action_bt_WrapperAI_Hero_HeroLowAI_node547();
            _node170.SetClassNameString("Action");
            _node170.SetId(0x223);
            sequence44.AddChild(_node170);
            sequence44.SetHasEvents(sequence44.HasEvents() | _node170.HasEvents());
            _node168.SetHasEvents(_node168.HasEvents() | sequence44.HasEvents());
            sequence43.SetHasEvents(sequence43.HasEvents() | _node168.HasEvents());
            precondition5.SetHasEvents(precondition5.HasEvents() | sequence43.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition5.HasEvents());
            WithPrecondition precondition6 = new WithPrecondition();
            precondition6.SetClassNameString("WithPrecondition");
            precondition6.SetId(0x203);
            loop.AddChild(precondition6);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node516 _node171 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node516();
            _node171.SetClassNameString("Condition");
            _node171.SetId(0x204);
            precondition6.AddChild(_node171);
            precondition6.SetHasEvents(precondition6.HasEvents() | _node171.HasEvents());
            Selector selector12 = new Selector();
            selector12.SetClassNameString("Selector");
            selector12.SetId(0x4b);
            precondition6.AddChild(selector12);
            Sequence sequence45 = new Sequence();
            sequence45.SetClassNameString("Sequence");
            sequence45.SetId(0x4c);
            selector12.AddChild(sequence45);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node79 _node172 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node79();
            _node172.SetClassNameString("Condition");
            _node172.SetId(0x4f);
            sequence45.AddChild(_node172);
            sequence45.SetHasEvents(sequence45.HasEvents() | _node172.HasEvents());
            Assignment_bt_WrapperAI_Hero_HeroLowAI_node81 _node173 = new Assignment_bt_WrapperAI_Hero_HeroLowAI_node81();
            _node173.SetClassNameString("Assignment");
            _node173.SetId(0x51);
            sequence45.AddChild(_node173);
            sequence45.SetHasEvents(sequence45.HasEvents() | _node173.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node82 _node174 = new Action_bt_WrapperAI_Hero_HeroLowAI_node82();
            _node174.SetClassNameString("Action");
            _node174.SetId(0x52);
            sequence45.AddChild(_node174);
            sequence45.SetHasEvents(sequence45.HasEvents() | _node174.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node83 _node175 = new Action_bt_WrapperAI_Hero_HeroLowAI_node83();
            _node175.SetClassNameString("Action");
            _node175.SetId(0x53);
            sequence45.AddChild(_node175);
            sequence45.SetHasEvents(sequence45.HasEvents() | _node175.HasEvents());
            selector12.SetHasEvents(selector12.HasEvents() | sequence45.HasEvents());
            Sequence sequence46 = new Sequence();
            sequence46.SetClassNameString("Sequence");
            sequence46.SetId(0x205);
            selector12.AddChild(sequence46);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node84 _node176 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node84();
            _node176.SetClassNameString("Condition");
            _node176.SetId(0x54);
            sequence46.AddChild(_node176);
            sequence46.SetHasEvents(sequence46.HasEvents() | _node176.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node518 _node177 = new Action_bt_WrapperAI_Hero_HeroLowAI_node518();
            _node177.SetClassNameString("Action");
            _node177.SetId(0x206);
            sequence46.AddChild(_node177);
            sequence46.SetHasEvents(sequence46.HasEvents() | _node177.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node519 _node178 = new Action_bt_WrapperAI_Hero_HeroLowAI_node519();
            _node178.SetClassNameString("Action");
            _node178.SetId(0x207);
            sequence46.AddChild(_node178);
            sequence46.SetHasEvents(sequence46.HasEvents() | _node178.HasEvents());
            IfElse else14 = new IfElse();
            else14.SetClassNameString("IfElse");
            else14.SetId(520);
            sequence46.AddChild(else14);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node521 _node179 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node521();
            _node179.SetClassNameString("Condition");
            _node179.SetId(0x209);
            else14.AddChild(_node179);
            else14.SetHasEvents(else14.HasEvents() | _node179.HasEvents());
            Sequence sequence47 = new Sequence();
            sequence47.SetClassNameString("Sequence");
            sequence47.SetId(0x20a);
            else14.AddChild(sequence47);
            Action_bt_WrapperAI_Hero_HeroLowAI_node523 _node180 = new Action_bt_WrapperAI_Hero_HeroLowAI_node523();
            _node180.SetClassNameString("Action");
            _node180.SetId(0x20b);
            sequence47.AddChild(_node180);
            sequence47.SetHasEvents(sequence47.HasEvents() | _node180.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node524 _node181 = new Action_bt_WrapperAI_Hero_HeroLowAI_node524();
            _node181.SetClassNameString("Action");
            _node181.SetId(0x20c);
            sequence47.AddChild(_node181);
            sequence47.SetHasEvents(sequence47.HasEvents() | _node181.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node526 _node182 = new Action_bt_WrapperAI_Hero_HeroLowAI_node526();
            _node182.SetClassNameString("Action");
            _node182.SetId(0x20e);
            sequence47.AddChild(_node182);
            sequence47.SetHasEvents(sequence47.HasEvents() | _node182.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node85 _node183 = new Action_bt_WrapperAI_Hero_HeroLowAI_node85();
            _node183.SetClassNameString("Action");
            _node183.SetId(0x55);
            sequence47.AddChild(_node183);
            sequence47.SetHasEvents(sequence47.HasEvents() | _node183.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node530 _node184 = new Action_bt_WrapperAI_Hero_HeroLowAI_node530();
            _node184.SetClassNameString("Action");
            _node184.SetId(530);
            sequence47.AddChild(_node184);
            sequence47.SetHasEvents(sequence47.HasEvents() | _node184.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Hero_HeroLowAI_node531 _node185 = new DecoratorLoopUntil_bt_WrapperAI_Hero_HeroLowAI_node531();
            _node185.SetClassNameString("DecoratorLoopUntil");
            _node185.SetId(0x213);
            sequence47.AddChild(_node185);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node532 _node186 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node532();
            _node186.SetClassNameString("Condition");
            _node186.SetId(0x214);
            _node185.AddChild(_node186);
            _node185.SetHasEvents(_node185.HasEvents() | _node186.HasEvents());
            sequence47.SetHasEvents(sequence47.HasEvents() | _node185.HasEvents());
            else14.SetHasEvents(else14.HasEvents() | sequence47.HasEvents());
            Sequence sequence48 = new Sequence();
            sequence48.SetClassNameString("Sequence");
            sequence48.SetId(0x215);
            else14.AddChild(sequence48);
            Action_bt_WrapperAI_Hero_HeroLowAI_node86 _node187 = new Action_bt_WrapperAI_Hero_HeroLowAI_node86();
            _node187.SetClassNameString("Action");
            _node187.SetId(0x56);
            sequence48.AddChild(_node187);
            sequence48.SetHasEvents(sequence48.HasEvents() | _node187.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node535 _node188 = new Action_bt_WrapperAI_Hero_HeroLowAI_node535();
            _node188.SetClassNameString("Action");
            _node188.SetId(0x217);
            sequence48.AddChild(_node188);
            sequence48.SetHasEvents(sequence48.HasEvents() | _node188.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Hero_HeroLowAI_node536 _node189 = new DecoratorLoopUntil_bt_WrapperAI_Hero_HeroLowAI_node536();
            _node189.SetClassNameString("DecoratorLoopUntil");
            _node189.SetId(0x218);
            sequence48.AddChild(_node189);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node537 _node190 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node537();
            _node190.SetClassNameString("Condition");
            _node190.SetId(0x219);
            _node189.AddChild(_node190);
            _node189.SetHasEvents(_node189.HasEvents() | _node190.HasEvents());
            sequence48.SetHasEvents(sequence48.HasEvents() | _node189.HasEvents());
            else14.SetHasEvents(else14.HasEvents() | sequence48.HasEvents());
            sequence46.SetHasEvents(sequence46.HasEvents() | else14.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node538 _node191 = new Action_bt_WrapperAI_Hero_HeroLowAI_node538();
            _node191.SetClassNameString("Action");
            _node191.SetId(0x21a);
            sequence46.AddChild(_node191);
            sequence46.SetHasEvents(sequence46.HasEvents() | _node191.HasEvents());
            selector12.SetHasEvents(selector12.HasEvents() | sequence46.HasEvents());
            precondition6.SetHasEvents(precondition6.HasEvents() | selector12.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition6.HasEvents());
            WithPrecondition precondition7 = new WithPrecondition();
            precondition7.SetClassNameString("WithPrecondition");
            precondition7.SetId(2);
            loop.AddChild(precondition7);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node3 _node192 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node3();
            _node192.SetClassNameString("Condition");
            _node192.SetId(3);
            precondition7.AddChild(_node192);
            precondition7.SetHasEvents(precondition7.HasEvents() | _node192.HasEvents());
            Sequence sequence49 = new Sequence();
            sequence49.SetClassNameString("Sequence");
            sequence49.SetId(0x3b);
            precondition7.AddChild(sequence49);
            Action_bt_WrapperAI_Hero_HeroLowAI_node603 _node193 = new Action_bt_WrapperAI_Hero_HeroLowAI_node603();
            _node193.SetClassNameString("Action");
            _node193.SetId(0x25b);
            sequence49.AddChild(_node193);
            sequence49.SetHasEvents(sequence49.HasEvents() | _node193.HasEvents());
            Selector selector13 = new Selector();
            selector13.SetClassNameString("Selector");
            selector13.SetId(0x1e7);
            sequence49.AddChild(selector13);
            Action_bt_WrapperAI_Hero_HeroLowAI_node488 _node194 = new Action_bt_WrapperAI_Hero_HeroLowAI_node488();
            _node194.SetClassNameString("Action");
            _node194.SetId(0x1e8);
            selector13.AddChild(_node194);
            selector13.SetHasEvents(selector13.HasEvents() | _node194.HasEvents());
            Action_bt_WrapperAI_Hero_HeroLowAI_node4 _node195 = new Action_bt_WrapperAI_Hero_HeroLowAI_node4();
            _node195.SetClassNameString("Action");
            _node195.SetId(4);
            selector13.AddChild(_node195);
            selector13.SetHasEvents(selector13.HasEvents() | _node195.HasEvents());
            sequence49.SetHasEvents(sequence49.HasEvents() | selector13.HasEvents());
            DecoratorLoop_bt_WrapperAI_Hero_HeroLowAI_node65 _node196 = new DecoratorLoop_bt_WrapperAI_Hero_HeroLowAI_node65();
            _node196.SetClassNameString("DecoratorLoop");
            _node196.SetId(0x41);
            sequence49.AddChild(_node196);
            Noop noop8 = new Noop();
            noop8.SetClassNameString("Noop");
            noop8.SetId(0x42);
            _node196.AddChild(noop8);
            _node196.SetHasEvents(_node196.HasEvents() | noop8.HasEvents());
            sequence49.SetHasEvents(sequence49.HasEvents() | _node196.HasEvents());
            precondition7.SetHasEvents(precondition7.HasEvents() | sequence49.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition7.HasEvents());
            WithPrecondition precondition8 = new WithPrecondition();
            precondition8.SetClassNameString("WithPrecondition");
            precondition8.SetId(450);
            loop.AddChild(precondition8);
            Condition_bt_WrapperAI_Hero_HeroLowAI_node454 _node197 = new Condition_bt_WrapperAI_Hero_HeroLowAI_node454();
            _node197.SetClassNameString("Condition");
            _node197.SetId(0x1c6);
            precondition8.AddChild(_node197);
            precondition8.SetHasEvents(precondition8.HasEvents() | _node197.HasEvents());
            Sequence sequence50 = new Sequence();
            sequence50.SetClassNameString("Sequence");
            sequence50.SetId(0x1c7);
            precondition8.AddChild(sequence50);
            Action_bt_WrapperAI_Hero_HeroLowAI_node456 _node198 = new Action_bt_WrapperAI_Hero_HeroLowAI_node456();
            _node198.SetClassNameString("Action");
            _node198.SetId(0x1c8);
            sequence50.AddChild(_node198);
            sequence50.SetHasEvents(sequence50.HasEvents() | _node198.HasEvents());
            DecoratorLoop_bt_WrapperAI_Hero_HeroLowAI_node457 _node199 = new DecoratorLoop_bt_WrapperAI_Hero_HeroLowAI_node457();
            _node199.SetClassNameString("DecoratorLoop");
            _node199.SetId(0x1c9);
            sequence50.AddChild(_node199);
            Noop noop9 = new Noop();
            noop9.SetClassNameString("Noop");
            noop9.SetId(0x1ca);
            _node199.AddChild(noop9);
            _node199.SetHasEvents(_node199.HasEvents() | noop9.HasEvents());
            sequence50.SetHasEvents(sequence50.HasEvents() | _node199.HasEvents());
            precondition8.SetHasEvents(precondition8.HasEvents() | sequence50.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition8.HasEvents());
            sequence6.SetHasEvents(sequence6.HasEvents() | loop.HasEvents());
            _node22.SetHasEvents(_node22.HasEvents() | sequence6.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | _node22.HasEvents());
            bt.SetHasEvents(bt.HasEvents() | pChild.HasEvents());
            return true;
        }
    }
}

