namespace behaviac
{
    using System;

    public static class bt_WrapperAI_Monster_BTMonsterRunToInitiative
    {
        public static bool build_behavior_tree(BehaviorTree bt)
        {
            bt.SetClassNameString("BehaviorTree");
            bt.SetId(-1);
            bt.SetName("WrapperAI/Monster/BTMonsterRunToInitiative");
            bt.AddPar("Assets.Scripts.GameLogic.SkillSlotType", "p_curSlotType", "SLOT_SKILL_0", string.Empty);
            bt.AddPar("uint", "p_targetID", "0", string.Empty);
            bt.AddPar("int", "p_srchRange", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_AttackMoveDest", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("bool", "p_IsAttackMove_Attack", "false", string.Empty);
            bt.AddPar("bool", "p_AttackIsFinished", "true", string.Empty);
            bt.AddPar("uint", "p_CmdID", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_attackPathCurTargetPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_skillAttackRange", "0", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_orignalPos", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_follow_range", "9000", string.Empty);
            bt.AddPar("UnityEngine.Vector3", "p_orignalDirection", "{kEpsilon=0;x=0;y=0;z=0;}", string.Empty);
            bt.AddPar("int", "p_pursuitRange", "0", string.Empty);
            bt.AddPar("uint", "p_selfID", "0", string.Empty);
            bt.AddPar("int", "p_waitFramesToSearch", "10", string.Empty);
            Sequence pChild = new Sequence();
            pChild.SetClassNameString("Sequence");
            pChild.SetId(0);
            bt.AddChild(pChild);
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node98 _node = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node98();
            _node.SetClassNameString("Assignment");
            _node.SetId(0x62);
            pChild.AddChild(_node);
            pChild.SetHasEvents(pChild.HasEvents() | _node.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node20 _node2 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node20();
            _node2.SetClassNameString("Assignment");
            _node2.SetId(20);
            pChild.AddChild(_node2);
            pChild.SetHasEvents(pChild.HasEvents() | _node2.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node63 _node3 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node63();
            _node3.SetClassNameString("Action");
            _node3.SetId(0x3f);
            pChild.AddChild(_node3);
            pChild.SetHasEvents(pChild.HasEvents() | _node3.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node64 _node4 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node64();
            _node4.SetClassNameString("Action");
            _node4.SetId(0x40);
            pChild.AddChild(_node4);
            pChild.SetHasEvents(pChild.HasEvents() | _node4.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node82 _node5 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node82();
            _node5.SetClassNameString("Assignment");
            _node5.SetId(0x52);
            pChild.AddChild(_node5);
            pChild.SetHasEvents(pChild.HasEvents() | _node5.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node83 _node6 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node83();
            _node6.SetClassNameString("Assignment");
            _node6.SetId(0x53);
            pChild.AddChild(_node6);
            pChild.SetHasEvents(pChild.HasEvents() | _node6.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node11 _node7 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node11();
            _node7.SetClassNameString("Assignment");
            _node7.SetId(11);
            pChild.AddChild(_node7);
            pChild.SetHasEvents(pChild.HasEvents() | _node7.HasEvents());
            WaitFrames_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node10 _node8 = new WaitFrames_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node10();
            _node8.SetClassNameString("WaitFrames");
            _node8.SetId(10);
            pChild.AddChild(_node8);
            pChild.SetHasEvents(pChild.HasEvents() | _node8.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node14 _node9 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node14();
            _node9.SetClassNameString("DecoratorLoop");
            _node9.SetId(14);
            pChild.AddChild(_node9);
            SelectorLoop loop = new SelectorLoop();
            loop.SetClassNameString("SelectorLoop");
            loop.SetId(1);
            _node9.AddChild(loop);
            WithPrecondition precondition = new WithPrecondition();
            precondition.SetClassNameString("WithPrecondition");
            precondition.SetId(0x3b);
            loop.AddChild(precondition);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node78 _node10 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node78();
            _node10.SetClassNameString("Condition");
            _node10.SetId(0x4e);
            precondition.AddChild(_node10);
            precondition.SetHasEvents(precondition.HasEvents() | _node10.HasEvents());
            Sequence sequence2 = new Sequence();
            sequence2.SetClassNameString("Sequence");
            sequence2.SetId(0x4f);
            precondition.AddChild(sequence2);
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node104 _node11 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node104();
            _node11.SetClassNameString("Assignment");
            _node11.SetId(0x68);
            sequence2.AddChild(_node11);
            sequence2.SetHasEvents(sequence2.HasEvents() | _node11.HasEvents());
            IfElse @else = new IfElse();
            @else.SetClassNameString("IfElse");
            @else.SetId(0x77);
            sequence2.AddChild(@else);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node120 _node12 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node120();
            _node12.SetClassNameString("Condition");
            _node12.SetId(120);
            @else.AddChild(_node12);
            @else.SetHasEvents(@else.HasEvents() | _node12.HasEvents());
            IfElse else2 = new IfElse();
            else2.SetClassNameString("IfElse");
            else2.SetId(0x1f);
            @else.AddChild(else2);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node48 _node13 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node48();
            _node13.SetClassNameString("Condition");
            _node13.SetId(0x30);
            else2.AddChild(_node13);
            else2.SetHasEvents(else2.HasEvents() | _node13.HasEvents());
            Sequence sequence3 = new Sequence();
            sequence3.SetClassNameString("Sequence");
            sequence3.SetId(0x79);
            else2.AddChild(sequence3);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node463 _node14 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node463();
            _node14.SetClassNameString("Action");
            _node14.SetId(0x1cf);
            sequence3.AddChild(_node14);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node14.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node123 _node15 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node123();
            _node15.SetClassNameString("Action");
            _node15.SetId(0x7b);
            sequence3.AddChild(_node15);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node15.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node124 _node16 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node124();
            _node16.SetClassNameString("Action");
            _node16.SetId(0x7c);
            sequence3.AddChild(_node16);
            sequence3.SetHasEvents(sequence3.HasEvents() | _node16.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | sequence3.HasEvents());
            IfElse else3 = new IfElse();
            else3.SetClassNameString("IfElse");
            else3.SetId(0x31);
            else2.AddChild(else3);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node50 _node17 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node50();
            _node17.SetClassNameString("Condition");
            _node17.SetId(50);
            else3.AddChild(_node17);
            else3.SetHasEvents(else3.HasEvents() | _node17.HasEvents());
            Sequence sequence4 = new Sequence();
            sequence4.SetClassNameString("Sequence");
            sequence4.SetId(0x36);
            else3.AddChild(sequence4);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node55 _node18 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node55();
            _node18.SetClassNameString("Condition");
            _node18.SetId(0x37);
            sequence4.AddChild(_node18);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node18.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node56 _node19 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node56();
            _node19.SetClassNameString("Action");
            _node19.SetId(0x38);
            sequence4.AddChild(_node19);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node19.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node57 _node20 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node57();
            _node20.SetClassNameString("Assignment");
            _node20.SetId(0x39);
            sequence4.AddChild(_node20);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node20.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node65 _node21 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node65();
            _node21.SetClassNameString("Action");
            _node21.SetId(0x41);
            sequence4.AddChild(_node21);
            sequence4.SetHasEvents(sequence4.HasEvents() | _node21.HasEvents());
            else3.SetHasEvents(else3.HasEvents() | sequence4.HasEvents());
            Sequence sequence5 = new Sequence();
            sequence5.SetClassNameString("Sequence");
            sequence5.SetId(0x33);
            else3.AddChild(sequence5);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node52 _node22 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node52();
            _node22.SetClassNameString("Action");
            _node22.SetId(0x34);
            sequence5.AddChild(_node22);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node22.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node53 _node23 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node53();
            _node23.SetClassNameString("Action");
            _node23.SetId(0x35);
            sequence5.AddChild(_node23);
            sequence5.SetHasEvents(sequence5.HasEvents() | _node23.HasEvents());
            else3.SetHasEvents(else3.HasEvents() | sequence5.HasEvents());
            else2.SetHasEvents(else2.HasEvents() | else3.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | else2.HasEvents());
            Sequence sequence6 = new Sequence();
            sequence6.SetClassNameString("Sequence");
            sequence6.SetId(0x7d);
            @else.AddChild(sequence6);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node126 _node24 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node126();
            _node24.SetClassNameString("Action");
            _node24.SetId(0x7e);
            sequence6.AddChild(_node24);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node24.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node127 _node25 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node127();
            _node25.SetClassNameString("Action");
            _node25.SetId(0x7f);
            sequence6.AddChild(_node25);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node25.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node58 _node26 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node58();
            _node26.SetClassNameString("Action");
            _node26.SetId(0x3a);
            sequence6.AddChild(_node26);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node26.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node62 _node27 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node62();
            _node27.SetClassNameString("Assignment");
            _node27.SetId(0x3e);
            sequence6.AddChild(_node27);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node27.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node81 _node28 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node81();
            _node28.SetClassNameString("Action");
            _node28.SetId(0x51);
            sequence6.AddChild(_node28);
            sequence6.SetHasEvents(sequence6.HasEvents() | _node28.HasEvents());
            @else.SetHasEvents(@else.HasEvents() | sequence6.HasEvents());
            sequence2.SetHasEvents(sequence2.HasEvents() | @else.HasEvents());
            precondition.SetHasEvents(precondition.HasEvents() | sequence2.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition.HasEvents());
            WithPrecondition precondition2 = new WithPrecondition();
            precondition2.SetClassNameString("WithPrecondition");
            precondition2.SetId(60);
            loop.AddChild(precondition2);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node61 _node29 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node61();
            _node29.SetClassNameString("Condition");
            _node29.SetId(0x3d);
            precondition2.AddChild(_node29);
            precondition2.SetHasEvents(precondition2.HasEvents() | _node29.HasEvents());
            Sequence sequence7 = new Sequence();
            sequence7.SetClassNameString("Sequence");
            sequence7.SetId(0x2e);
            precondition2.AddChild(sequence7);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node47 _node30 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node47();
            _node30.SetClassNameString("Action");
            _node30.SetId(0x2f);
            sequence7.AddChild(_node30);
            sequence7.SetHasEvents(sequence7.HasEvents() | _node30.HasEvents());
            IfElse else4 = new IfElse();
            else4.SetClassNameString("IfElse");
            else4.SetId(0xf5);
            sequence7.AddChild(else4);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node246 _node31 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node246();
            _node31.SetClassNameString("Condition");
            _node31.SetId(0xf6);
            else4.AddChild(_node31);
            else4.SetHasEvents(else4.HasEvents() | _node31.HasEvents());
            IfElse else5 = new IfElse();
            else5.SetClassNameString("IfElse");
            else5.SetId(0x1b);
            else4.AddChild(else5);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node28 _node32 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node28();
            _node32.SetClassNameString("Condition");
            _node32.SetId(0x1c);
            else5.AddChild(_node32);
            else5.SetHasEvents(else5.HasEvents() | _node32.HasEvents());
            Sequence sequence8 = new Sequence();
            sequence8.SetClassNameString("Sequence");
            sequence8.SetId(0xf7);
            else5.AddChild(sequence8);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node248 _node33 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node248();
            _node33.SetClassNameString("Action");
            _node33.SetId(0xf8);
            sequence8.AddChild(_node33);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node33.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node21 _node34 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node21();
            _node34.SetClassNameString("Action");
            _node34.SetId(0x15);
            sequence8.AddChild(_node34);
            sequence8.SetHasEvents(sequence8.HasEvents() | _node34.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node66 _node35 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node66();
            _node35.SetClassNameString("DecoratorLoop");
            _node35.SetId(0x42);
            sequence8.AddChild(_node35);
            Sequence sequence9 = new Sequence();
            sequence9.SetClassNameString("Sequence");
            sequence9.SetId(0x19);
            _node35.AddChild(sequence9);
            WaitFrames_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node9 _node36 = new WaitFrames_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node9();
            _node36.SetClassNameString("WaitFrames");
            _node36.SetId(9);
            sequence9.AddChild(_node36);
            sequence9.SetHasEvents(sequence9.HasEvents() | _node36.HasEvents());
            Selector selector = new Selector();
            selector.SetClassNameString("Selector");
            selector.SetId(0x43);
            sequence9.AddChild(selector);
            Sequence sequence10 = new Sequence();
            sequence10.SetClassNameString("Sequence");
            sequence10.SetId(0x16);
            selector.AddChild(sequence10);
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node30 _node37 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node30();
            _node37.SetClassNameString("Assignment");
            _node37.SetId(30);
            sequence10.AddChild(_node37);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node37.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node15 _node38 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node15();
            _node38.SetClassNameString("Assignment");
            _node38.SetId(15);
            sequence10.AddChild(_node38);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node38.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node16 _node39 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node16();
            _node39.SetClassNameString("Assignment");
            _node39.SetId(0x10);
            sequence10.AddChild(_node39);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node39.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node12 _node40 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node12();
            _node40.SetClassNameString("Condition");
            _node40.SetId(12);
            sequence10.AddChild(_node40);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node40.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node13 _node41 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node13();
            _node41.SetClassNameString("Action");
            _node41.SetId(13);
            sequence10.AddChild(_node41);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node41.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node17 _node42 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node17();
            _node42.SetClassNameString("Action");
            _node42.SetId(0x11);
            sequence10.AddChild(_node42);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node42.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node18 _node43 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node18();
            _node43.SetClassNameString("Action");
            _node43.SetId(0x12);
            sequence10.AddChild(_node43);
            sequence10.SetHasEvents(sequence10.HasEvents() | _node43.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence10.HasEvents());
            Sequence sequence11 = new Sequence();
            sequence11.SetClassNameString("Sequence");
            sequence11.SetId(0x44);
            selector.AddChild(sequence11);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node69 _node44 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node69();
            _node44.SetClassNameString("Condition");
            _node44.SetId(0x45);
            sequence11.AddChild(_node44);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node44.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node231 _node45 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node231();
            _node45.SetClassNameString("Action");
            _node45.SetId(0xe7);
            sequence11.AddChild(_node45);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node45.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node232 _node46 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node232();
            _node46.SetClassNameString("Action");
            _node46.SetId(0xe8);
            sequence11.AddChild(_node46);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node46.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node233 _node47 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node233();
            _node47.SetClassNameString("Action");
            _node47.SetId(0xe9);
            sequence11.AddChild(_node47);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node47.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node234 _node48 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node234();
            _node48.SetClassNameString("Assignment");
            _node48.SetId(0xea);
            sequence11.AddChild(_node48);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node48.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node32 _node49 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node32();
            _node49.SetClassNameString("Action");
            _node49.SetId(0x20);
            sequence11.AddChild(_node49);
            sequence11.SetHasEvents(sequence11.HasEvents() | _node49.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence11.HasEvents());
            Sequence sequence12 = new Sequence();
            sequence12.SetClassNameString("Sequence");
            sequence12.SetId(0xeb);
            selector.AddChild(sequence12);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node236 _node50 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node236();
            _node50.SetClassNameString("Condition");
            _node50.SetId(0xec);
            sequence12.AddChild(_node50);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node50.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node237 _node51 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node237();
            _node51.SetClassNameString("Action");
            _node51.SetId(0xed);
            sequence12.AddChild(_node51);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node51.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node238 _node52 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node238();
            _node52.SetClassNameString("Action");
            _node52.SetId(0xee);
            sequence12.AddChild(_node52);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node52.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node239 _node53 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node239();
            _node53.SetClassNameString("Assignment");
            _node53.SetId(0xef);
            sequence12.AddChild(_node53);
            sequence12.SetHasEvents(sequence12.HasEvents() | _node53.HasEvents());
            selector.SetHasEvents(selector.HasEvents() | sequence12.HasEvents());
            sequence9.SetHasEvents(sequence9.HasEvents() | selector.HasEvents());
            _node35.SetHasEvents(_node35.HasEvents() | sequence9.HasEvents());
            sequence8.SetHasEvents(sequence8.HasEvents() | _node35.HasEvents());
            else5.SetHasEvents(else5.HasEvents() | sequence8.HasEvents());
            Noop noop = new Noop();
            noop.SetClassNameString("Noop");
            noop.SetId(0x1d);
            else5.AddChild(noop);
            else5.SetHasEvents(else5.HasEvents() | noop.HasEvents());
            else4.SetHasEvents(else4.HasEvents() | else5.HasEvents());
            Sequence sequence13 = new Sequence();
            sequence13.SetClassNameString("Sequence");
            sequence13.SetId(0xff);
            else4.AddChild(sequence13);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node256 _node54 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node256();
            _node54.SetClassNameString("Action");
            _node54.SetId(0x100);
            sequence13.AddChild(_node54);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node54.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node257 _node55 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node257();
            _node55.SetClassNameString("Action");
            _node55.SetId(0x101);
            sequence13.AddChild(_node55);
            sequence13.SetHasEvents(sequence13.HasEvents() | _node55.HasEvents());
            else4.SetHasEvents(else4.HasEvents() | sequence13.HasEvents());
            sequence7.SetHasEvents(sequence7.HasEvents() | else4.HasEvents());
            precondition2.SetHasEvents(precondition2.HasEvents() | sequence7.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition2.HasEvents());
            WithPrecondition precondition3 = new WithPrecondition();
            precondition3.SetClassNameString("WithPrecondition");
            precondition3.SetId(70);
            loop.AddChild(precondition3);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node71 _node56 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node71();
            _node56.SetClassNameString("Condition");
            _node56.SetId(0x47);
            precondition3.AddChild(_node56);
            precondition3.SetHasEvents(precondition3.HasEvents() | _node56.HasEvents());
            Selector selector2 = new Selector();
            selector2.SetClassNameString("Selector");
            selector2.SetId(0x21);
            precondition3.AddChild(selector2);
            Sequence sequence14 = new Sequence();
            sequence14.SetClassNameString("Sequence");
            sequence14.SetId(0x22);
            selector2.AddChild(sequence14);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node130 _node57 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node130();
            _node57.SetClassNameString("Condition");
            _node57.SetId(130);
            sequence14.AddChild(_node57);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node57.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node35 _node58 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node35();
            _node58.SetClassNameString("Action");
            _node58.SetId(0x23);
            sequence14.AddChild(_node58);
            sequence14.SetHasEvents(sequence14.HasEvents() | _node58.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence14.HasEvents());
            Sequence sequence15 = new Sequence();
            sequence15.SetClassNameString("Sequence");
            sequence15.SetId(0x4b);
            selector2.AddChild(sequence15);
            IfElse else6 = new IfElse();
            else6.SetClassNameString("IfElse");
            else6.SetId(0x4d);
            sequence15.AddChild(else6);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node100 _node59 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node100();
            _node59.SetClassNameString("Condition");
            _node59.SetId(100);
            else6.AddChild(_node59);
            else6.SetHasEvents(else6.HasEvents() | _node59.HasEvents());
            Noop noop2 = new Noop();
            noop2.SetClassNameString("Noop");
            noop2.SetId(0x83);
            else6.AddChild(noop2);
            else6.SetHasEvents(else6.HasEvents() | noop2.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node133 _node60 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node133();
            _node60.SetClassNameString("Assignment");
            _node60.SetId(0x85);
            else6.AddChild(_node60);
            else6.SetHasEvents(else6.HasEvents() | _node60.HasEvents());
            sequence15.SetHasEvents(sequence15.HasEvents() | else6.HasEvents());
            IfElse else7 = new IfElse();
            else7.SetClassNameString("IfElse");
            else7.SetId(0x86);
            sequence15.AddChild(else7);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node5 _node61 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node5();
            _node61.SetClassNameString("Condition");
            _node61.SetId(5);
            else7.AddChild(_node61);
            else7.SetHasEvents(else7.HasEvents() | _node61.HasEvents());
            Sequence sequence16 = new Sequence();
            sequence16.SetClassNameString("Sequence");
            sequence16.SetId(0x89);
            else7.AddChild(sequence16);
            Selector selector3 = new Selector();
            selector3.SetClassNameString("Selector");
            selector3.SetId(0x8a);
            sequence16.AddChild(selector3);
            Sequence sequence17 = new Sequence();
            sequence17.SetClassNameString("Sequence");
            sequence17.SetId(0x8b);
            selector3.AddChild(sequence17);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node156 _node62 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node156();
            _node62.SetClassNameString("Action");
            _node62.SetId(0x9c);
            sequence17.AddChild(_node62);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node62.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node159 _node63 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node159();
            _node63.SetClassNameString("Assignment");
            _node63.SetId(0x9f);
            sequence17.AddChild(_node63);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node63.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node160 _node64 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node160();
            _node64.SetClassNameString("Assignment");
            _node64.SetId(160);
            sequence17.AddChild(_node64);
            sequence17.SetHasEvents(sequence17.HasEvents() | _node64.HasEvents());
            Selector selector4 = new Selector();
            selector4.SetClassNameString("Selector");
            selector4.SetId(0x92);
            sequence17.AddChild(selector4);
            Sequence sequence18 = new Sequence();
            sequence18.SetClassNameString("Sequence");
            sequence18.SetId(0x91);
            selector4.AddChild(sequence18);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node712 _node65 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node712();
            _node65.SetClassNameString("Action");
            _node65.SetId(0x2c8);
            sequence18.AddChild(_node65);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node65.HasEvents());
            Selector selector5 = new Selector();
            selector5.SetClassNameString("Selector");
            selector5.SetId(3);
            sequence18.AddChild(selector5);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node2 _node66 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node2();
            _node66.SetClassNameString("Condition");
            _node66.SetId(2);
            selector5.AddChild(_node66);
            selector5.SetHasEvents(selector5.HasEvents() | _node66.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node4 _node67 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node4();
            _node67.SetClassNameString("Condition");
            _node67.SetId(4);
            selector5.AddChild(_node67);
            selector5.SetHasEvents(selector5.HasEvents() | _node67.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node147 _node68 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node147();
            _node68.SetClassNameString("Condition");
            _node68.SetId(0x93);
            selector5.AddChild(_node68);
            selector5.SetHasEvents(selector5.HasEvents() | _node68.HasEvents());
            sequence18.SetHasEvents(sequence18.HasEvents() | selector5.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node6 _node69 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node6();
            _node69.SetClassNameString("Condition");
            _node69.SetId(6);
            sequence18.AddChild(_node69);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node69.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node148 _node70 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node148();
            _node70.SetClassNameString("Action");
            _node70.SetId(0x94);
            sequence18.AddChild(_node70);
            sequence18.SetHasEvents(sequence18.HasEvents() | _node70.HasEvents());
            selector4.SetHasEvents(selector4.HasEvents() | sequence18.HasEvents());
            Sequence sequence19 = new Sequence();
            sequence19.SetClassNameString("Sequence");
            sequence19.SetId(0x17);
            selector4.AddChild(sequence19);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node149 _node71 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node149();
            _node71.SetClassNameString("Condition");
            _node71.SetId(0x95);
            sequence19.AddChild(_node71);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node71.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node150 _node72 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node150();
            _node72.SetClassNameString("Assignment");
            _node72.SetId(150);
            sequence19.AddChild(_node72);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node72.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node152 _node73 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node152();
            _node73.SetClassNameString("Condition");
            _node73.SetId(0x98);
            sequence19.AddChild(_node73);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node73.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node153 _node74 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node153();
            _node74.SetClassNameString("Action");
            _node74.SetId(0x99);
            sequence19.AddChild(_node74);
            sequence19.SetHasEvents(sequence19.HasEvents() | _node74.HasEvents());
            selector4.SetHasEvents(selector4.HasEvents() | sequence19.HasEvents());
            Sequence sequence20 = new Sequence();
            sequence20.SetClassNameString("Sequence");
            sequence20.SetId(0x9a);
            selector4.AddChild(sequence20);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node39 _node75 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node39();
            _node75.SetClassNameString("Condition");
            _node75.SetId(0x27);
            sequence20.AddChild(_node75);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node75.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node40 _node76 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node40();
            _node76.SetClassNameString("Condition");
            _node76.SetId(40);
            sequence20.AddChild(_node76);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node76.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node41 _node77 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node41();
            _node77.SetClassNameString("Action");
            _node77.SetId(0x29);
            sequence20.AddChild(_node77);
            sequence20.SetHasEvents(sequence20.HasEvents() | _node77.HasEvents());
            selector4.SetHasEvents(selector4.HasEvents() | sequence20.HasEvents());
            sequence17.SetHasEvents(sequence17.HasEvents() | selector4.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence17.HasEvents());
            Sequence sequence21 = new Sequence();
            sequence21.SetClassNameString("Sequence");
            sequence21.SetId(0x97);
            selector3.AddChild(sequence21);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node76 _node78 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node76();
            _node78.SetClassNameString("Action");
            _node78.SetId(0x4c);
            sequence21.AddChild(_node78);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node78.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node155 _node79 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node155();
            _node79.SetClassNameString("Assignment");
            _node79.SetId(0x9b);
            sequence21.AddChild(_node79);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node79.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node182 _node80 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node182();
            _node80.SetClassNameString("Assignment");
            _node80.SetId(0xb6);
            sequence21.AddChild(_node80);
            sequence21.SetHasEvents(sequence21.HasEvents() | _node80.HasEvents());
            Selector selector6 = new Selector();
            selector6.SetClassNameString("Selector");
            selector6.SetId(0x24);
            sequence21.AddChild(selector6);
            Sequence sequence22 = new Sequence();
            sequence22.SetClassNameString("Sequence");
            sequence22.SetId(0x2a);
            selector6.AddChild(sequence22);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node43 _node81 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node43();
            _node81.SetClassNameString("Action");
            _node81.SetId(0x2b);
            sequence22.AddChild(_node81);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node81.HasEvents());
            Selector selector7 = new Selector();
            selector7.SetClassNameString("Selector");
            selector7.SetId(0x2c);
            sequence22.AddChild(selector7);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node45 _node82 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node45();
            _node82.SetClassNameString("Condition");
            _node82.SetId(0x2d);
            selector7.AddChild(_node82);
            selector7.SetHasEvents(selector7.HasEvents() | _node82.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node72 _node83 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node72();
            _node83.SetClassNameString("Condition");
            _node83.SetId(0x48);
            selector7.AddChild(_node83);
            selector7.SetHasEvents(selector7.HasEvents() | _node83.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node73 _node84 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node73();
            _node84.SetClassNameString("Condition");
            _node84.SetId(0x49);
            selector7.AddChild(_node84);
            selector7.SetHasEvents(selector7.HasEvents() | _node84.HasEvents());
            sequence22.SetHasEvents(sequence22.HasEvents() | selector7.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node74 _node85 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node74();
            _node85.SetClassNameString("Condition");
            _node85.SetId(0x4a);
            sequence22.AddChild(_node85);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node85.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node80 _node86 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node80();
            _node86.SetClassNameString("Action");
            _node86.SetId(80);
            sequence22.AddChild(_node86);
            sequence22.SetHasEvents(sequence22.HasEvents() | _node86.HasEvents());
            selector6.SetHasEvents(selector6.HasEvents() | sequence22.HasEvents());
            Sequence sequence23 = new Sequence();
            sequence23.SetClassNameString("Sequence");
            sequence23.SetId(0x54);
            selector6.AddChild(sequence23);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node157 _node87 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node157();
            _node87.SetClassNameString("Condition");
            _node87.SetId(0x9d);
            sequence23.AddChild(_node87);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node87.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node158 _node88 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node158();
            _node88.SetClassNameString("Assignment");
            _node88.SetId(0x9e);
            sequence23.AddChild(_node88);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node88.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node161 _node89 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node161();
            _node89.SetClassNameString("Condition");
            _node89.SetId(0xa1);
            sequence23.AddChild(_node89);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node89.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node162 _node90 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node162();
            _node90.SetClassNameString("Action");
            _node90.SetId(0xa2);
            sequence23.AddChild(_node90);
            sequence23.SetHasEvents(sequence23.HasEvents() | _node90.HasEvents());
            selector6.SetHasEvents(selector6.HasEvents() | sequence23.HasEvents());
            Sequence sequence24 = new Sequence();
            sequence24.SetClassNameString("Sequence");
            sequence24.SetId(0xa3);
            selector6.AddChild(sequence24);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node90 _node91 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node90();
            _node91.SetClassNameString("Condition");
            _node91.SetId(90);
            sequence24.AddChild(_node91);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node91.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node164 _node92 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node164();
            _node92.SetClassNameString("Condition");
            _node92.SetId(0xa4);
            sequence24.AddChild(_node92);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node92.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node92 _node93 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node92();
            _node93.SetClassNameString("Action");
            _node93.SetId(0x5c);
            sequence24.AddChild(_node93);
            sequence24.SetHasEvents(sequence24.HasEvents() | _node93.HasEvents());
            selector6.SetHasEvents(selector6.HasEvents() | sequence24.HasEvents());
            sequence21.SetHasEvents(sequence21.HasEvents() | selector6.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence21.HasEvents());
            Sequence sequence25 = new Sequence();
            sequence25.SetClassNameString("Sequence");
            sequence25.SetId(0xb7);
            selector3.AddChild(sequence25);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node89 _node94 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node89();
            _node94.SetClassNameString("Action");
            _node94.SetId(0x59);
            sequence25.AddChild(_node94);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node94.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node184 _node95 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node184();
            _node95.SetClassNameString("Assignment");
            _node95.SetId(0xb8);
            sequence25.AddChild(_node95);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node95.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node193 _node96 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node193();
            _node96.SetClassNameString("Assignment");
            _node96.SetId(0xc1);
            sequence25.AddChild(_node96);
            sequence25.SetHasEvents(sequence25.HasEvents() | _node96.HasEvents());
            Selector selector8 = new Selector();
            selector8.SetClassNameString("Selector");
            selector8.SetId(0x25);
            sequence25.AddChild(selector8);
            Sequence sequence26 = new Sequence();
            sequence26.SetClassNameString("Sequence");
            sequence26.SetId(0xa5);
            selector8.AddChild(sequence26);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node166 _node97 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node166();
            _node97.SetClassNameString("Action");
            _node97.SetId(0xa6);
            sequence26.AddChild(_node97);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node97.HasEvents());
            Selector selector9 = new Selector();
            selector9.SetClassNameString("Selector");
            selector9.SetId(0xa7);
            sequence26.AddChild(selector9);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node96 _node98 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node96();
            _node98.SetClassNameString("Condition");
            _node98.SetId(0x60);
            selector9.AddChild(_node98);
            selector9.SetHasEvents(selector9.HasEvents() | _node98.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node97 _node99 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node97();
            _node99.SetClassNameString("Condition");
            _node99.SetId(0x61);
            selector9.AddChild(_node99);
            selector9.SetHasEvents(selector9.HasEvents() | _node99.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node99 _node100 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node99();
            _node100.SetClassNameString("Condition");
            _node100.SetId(0x63);
            selector9.AddChild(_node100);
            selector9.SetHasEvents(selector9.HasEvents() | _node100.HasEvents());
            sequence26.SetHasEvents(sequence26.HasEvents() | selector9.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node101 _node101 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node101();
            _node101.SetClassNameString("Condition");
            _node101.SetId(0x65);
            sequence26.AddChild(_node101);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node101.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node102 _node102 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node102();
            _node102.SetClassNameString("Action");
            _node102.SetId(0x66);
            sequence26.AddChild(_node102);
            sequence26.SetHasEvents(sequence26.HasEvents() | _node102.HasEvents());
            selector8.SetHasEvents(selector8.HasEvents() | sequence26.HasEvents());
            Sequence sequence27 = new Sequence();
            sequence27.SetClassNameString("Sequence");
            sequence27.SetId(0x67);
            selector8.AddChild(sequence27);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node105 _node103 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node105();
            _node103.SetClassNameString("Condition");
            _node103.SetId(0x69);
            sequence27.AddChild(_node103);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node103.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node106 _node104 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node106();
            _node104.SetClassNameString("Assignment");
            _node104.SetId(0x6a);
            sequence27.AddChild(_node104);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node104.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node107 _node105 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node107();
            _node105.SetClassNameString("Condition");
            _node105.SetId(0x6b);
            sequence27.AddChild(_node105);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node105.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node108 _node106 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node108();
            _node106.SetClassNameString("Action");
            _node106.SetId(0x6c);
            sequence27.AddChild(_node106);
            sequence27.SetHasEvents(sequence27.HasEvents() | _node106.HasEvents());
            selector8.SetHasEvents(selector8.HasEvents() | sequence27.HasEvents());
            Sequence sequence28 = new Sequence();
            sequence28.SetClassNameString("Sequence");
            sequence28.SetId(0x6d);
            selector8.AddChild(sequence28);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node110 _node107 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node110();
            _node107.SetClassNameString("Condition");
            _node107.SetId(110);
            sequence28.AddChild(_node107);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node107.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node111 _node108 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node111();
            _node108.SetClassNameString("Condition");
            _node108.SetId(0x6f);
            sequence28.AddChild(_node108);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node108.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node112 _node109 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node112();
            _node109.SetClassNameString("Action");
            _node109.SetId(0x70);
            sequence28.AddChild(_node109);
            sequence28.SetHasEvents(sequence28.HasEvents() | _node109.HasEvents());
            selector8.SetHasEvents(selector8.HasEvents() | sequence28.HasEvents());
            sequence25.SetHasEvents(sequence25.HasEvents() | selector8.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence25.HasEvents());
            Sequence sequence29 = new Sequence();
            sequence29.SetClassNameString("Sequence");
            sequence29.SetId(0xc2);
            selector3.AddChild(sequence29);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node91 _node110 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node91();
            _node110.SetClassNameString("Action");
            _node110.SetId(0x5b);
            sequence29.AddChild(_node110);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node110.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node195 _node111 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node195();
            _node111.SetClassNameString("Assignment");
            _node111.SetId(0xc3);
            sequence29.AddChild(_node111);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node111.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node200 _node112 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node200();
            _node112.SetClassNameString("Assignment");
            _node112.SetId(200);
            sequence29.AddChild(_node112);
            sequence29.SetHasEvents(sequence29.HasEvents() | _node112.HasEvents());
            Selector selector10 = new Selector();
            selector10.SetClassNameString("Selector");
            selector10.SetId(0x26);
            sequence29.AddChild(selector10);
            Sequence sequence30 = new Sequence();
            sequence30.SetClassNameString("Sequence");
            sequence30.SetId(0x71);
            selector10.AddChild(sequence30);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node114 _node113 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node114();
            _node113.SetClassNameString("Action");
            _node113.SetId(0x72);
            sequence30.AddChild(_node113);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node113.HasEvents());
            Selector selector11 = new Selector();
            selector11.SetClassNameString("Selector");
            selector11.SetId(0x73);
            sequence30.AddChild(selector11);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node116 _node114 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node116();
            _node114.SetClassNameString("Condition");
            _node114.SetId(0x74);
            selector11.AddChild(_node114);
            selector11.SetHasEvents(selector11.HasEvents() | _node114.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node117 _node115 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node117();
            _node115.SetClassNameString("Condition");
            _node115.SetId(0x75);
            selector11.AddChild(_node115);
            selector11.SetHasEvents(selector11.HasEvents() | _node115.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node118 _node116 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node118();
            _node116.SetClassNameString("Condition");
            _node116.SetId(0x76);
            selector11.AddChild(_node116);
            selector11.SetHasEvents(selector11.HasEvents() | _node116.HasEvents());
            sequence30.SetHasEvents(sequence30.HasEvents() | selector11.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node122 _node117 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node122();
            _node117.SetClassNameString("Condition");
            _node117.SetId(0x7a);
            sequence30.AddChild(_node117);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node117.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node128 _node118 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node128();
            _node118.SetClassNameString("Action");
            _node118.SetId(0x80);
            sequence30.AddChild(_node118);
            sequence30.SetHasEvents(sequence30.HasEvents() | _node118.HasEvents());
            selector10.SetHasEvents(selector10.HasEvents() | sequence30.HasEvents());
            Sequence sequence31 = new Sequence();
            sequence31.SetClassNameString("Sequence");
            sequence31.SetId(0x81);
            selector10.AddChild(sequence31);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node132 _node119 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node132();
            _node119.SetClassNameString("Condition");
            _node119.SetId(0x84);
            sequence31.AddChild(_node119);
            sequence31.SetHasEvents(sequence31.HasEvents() | _node119.HasEvents());
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node135 _node120 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node135();
            _node120.SetClassNameString("Assignment");
            _node120.SetId(0x87);
            sequence31.AddChild(_node120);
            sequence31.SetHasEvents(sequence31.HasEvents() | _node120.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node136 _node121 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node136();
            _node121.SetClassNameString("Condition");
            _node121.SetId(0x88);
            sequence31.AddChild(_node121);
            sequence31.SetHasEvents(sequence31.HasEvents() | _node121.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node140 _node122 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node140();
            _node122.SetClassNameString("Action");
            _node122.SetId(140);
            sequence31.AddChild(_node122);
            sequence31.SetHasEvents(sequence31.HasEvents() | _node122.HasEvents());
            selector10.SetHasEvents(selector10.HasEvents() | sequence31.HasEvents());
            Sequence sequence32 = new Sequence();
            sequence32.SetClassNameString("Sequence");
            sequence32.SetId(0x8d);
            selector10.AddChild(sequence32);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node142 _node123 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node142();
            _node123.SetClassNameString("Condition");
            _node123.SetId(0x8e);
            sequence32.AddChild(_node123);
            sequence32.SetHasEvents(sequence32.HasEvents() | _node123.HasEvents());
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node143 _node124 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node143();
            _node124.SetClassNameString("Condition");
            _node124.SetId(0x8f);
            sequence32.AddChild(_node124);
            sequence32.SetHasEvents(sequence32.HasEvents() | _node124.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node144 _node125 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node144();
            _node125.SetClassNameString("Action");
            _node125.SetId(0x90);
            sequence32.AddChild(_node125);
            sequence32.SetHasEvents(sequence32.HasEvents() | _node125.HasEvents());
            selector10.SetHasEvents(selector10.HasEvents() | sequence32.HasEvents());
            sequence29.SetHasEvents(sequence29.HasEvents() | selector10.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | sequence29.HasEvents());
            IfElse else8 = new IfElse();
            else8.SetClassNameString("IfElse");
            else8.SetId(0x13);
            selector3.AddChild(else8);
            Sequence sequence33 = new Sequence();
            sequence33.SetClassNameString("Sequence");
            sequence33.SetId(0x1a);
            else8.AddChild(sequence33);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node93 _node126 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node93();
            _node126.SetClassNameString("Condition");
            _node126.SetId(0x5d);
            sequence33.AddChild(_node126);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node126.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node8 _node127 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node8();
            _node127.SetClassNameString("Action");
            _node127.SetId(8);
            sequence33.AddChild(_node127);
            sequence33.SetHasEvents(sequence33.HasEvents() | _node127.HasEvents());
            else8.SetHasEvents(else8.HasEvents() | sequence33.HasEvents());
            Sequence sequence34 = new Sequence();
            sequence34.SetClassNameString("Sequence");
            sequence34.SetId(0x5e);
            else8.AddChild(sequence34);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node201 _node128 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node201();
            _node128.SetClassNameString("Action");
            _node128.SetId(0xc9);
            sequence34.AddChild(_node128);
            sequence34.SetHasEvents(sequence34.HasEvents() | _node128.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node241 _node129 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node241();
            _node129.SetClassNameString("Action");
            _node129.SetId(0xf1);
            sequence34.AddChild(_node129);
            sequence34.SetHasEvents(sequence34.HasEvents() | _node129.HasEvents());
            else8.SetHasEvents(else8.HasEvents() | sequence34.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node7 _node130 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node7();
            _node130.SetClassNameString("Action");
            _node130.SetId(7);
            else8.AddChild(_node130);
            else8.SetHasEvents(else8.HasEvents() | _node130.HasEvents());
            selector3.SetHasEvents(selector3.HasEvents() | else8.HasEvents());
            sequence16.SetHasEvents(sequence16.HasEvents() | selector3.HasEvents());
            Sequence sequence35 = new Sequence();
            sequence35.SetClassNameString("Sequence");
            sequence35.SetId(0xca);
            sequence16.AddChild(sequence35);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node85 _node131 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node85();
            _node131.SetClassNameString("Action");
            _node131.SetId(0x55);
            sequence35.AddChild(_node131);
            sequence35.SetHasEvents(sequence35.HasEvents() | _node131.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node86 _node132 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node86();
            _node132.SetClassNameString("Action");
            _node132.SetId(0x56);
            sequence35.AddChild(_node132);
            sequence35.SetHasEvents(sequence35.HasEvents() | _node132.HasEvents());
            DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node87 _node133 = new DecoratorLoopUntil_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node87();
            _node133.SetClassNameString("DecoratorLoopUntil");
            _node133.SetId(0x57);
            sequence35.AddChild(_node133);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node88 _node134 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node88();
            _node134.SetClassNameString("Condition");
            _node134.SetId(0x58);
            _node133.AddChild(_node134);
            _node133.SetHasEvents(_node133.HasEvents() | _node134.HasEvents());
            sequence35.SetHasEvents(sequence35.HasEvents() | _node133.HasEvents());
            sequence16.SetHasEvents(sequence16.HasEvents() | sequence35.HasEvents());
            else7.SetHasEvents(else7.HasEvents() | sequence16.HasEvents());
            Sequence sequence36 = new Sequence();
            sequence36.SetClassNameString("Sequence");
            sequence36.SetId(0xd0);
            else7.AddChild(sequence36);
            Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node229 _node135 = new Assignment_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node229();
            _node135.SetClassNameString("Assignment");
            _node135.SetId(0xe5);
            sequence36.AddChild(_node135);
            sequence36.SetHasEvents(sequence36.HasEvents() | _node135.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node224 _node136 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node224();
            _node136.SetClassNameString("Action");
            _node136.SetId(0xe0);
            sequence36.AddChild(_node136);
            sequence36.SetHasEvents(sequence36.HasEvents() | _node136.HasEvents());
            else7.SetHasEvents(else7.HasEvents() | sequence36.HasEvents());
            sequence15.SetHasEvents(sequence15.HasEvents() | else7.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node95 _node137 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node95();
            _node137.SetClassNameString("Action");
            _node137.SetId(0x5f);
            sequence15.AddChild(_node137);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node137.HasEvents());
            WaitFrames_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node24 _node138 = new WaitFrames_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node24();
            _node138.SetClassNameString("WaitFrames");
            _node138.SetId(0x18);
            sequence15.AddChild(_node138);
            sequence15.SetHasEvents(sequence15.HasEvents() | _node138.HasEvents());
            selector2.SetHasEvents(selector2.HasEvents() | sequence15.HasEvents());
            precondition3.SetHasEvents(precondition3.HasEvents() | selector2.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition3.HasEvents());
            WithPrecondition precondition4 = new WithPrecondition();
            precondition4.SetClassNameString("WithPrecondition");
            precondition4.SetId(0xab);
            loop.AddChild(precondition4);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node172 _node139 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node172();
            _node139.SetClassNameString("Condition");
            _node139.SetId(0xac);
            precondition4.AddChild(_node139);
            precondition4.SetHasEvents(precondition4.HasEvents() | _node139.HasEvents());
            Sequence sequence37 = new Sequence();
            sequence37.SetClassNameString("Sequence");
            sequence37.SetId(0xad);
            precondition4.AddChild(sequence37);
            Selector selector12 = new Selector();
            selector12.SetClassNameString("Selector");
            selector12.SetId(0x1e7);
            sequence37.AddChild(selector12);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node488 _node140 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node488();
            _node140.SetClassNameString("Action");
            _node140.SetId(0x1e8);
            selector12.AddChild(_node140);
            selector12.SetHasEvents(selector12.HasEvents() | _node140.HasEvents());
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node174 _node141 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node174();
            _node141.SetClassNameString("Action");
            _node141.SetId(0xae);
            selector12.AddChild(_node141);
            selector12.SetHasEvents(selector12.HasEvents() | _node141.HasEvents());
            sequence37.SetHasEvents(sequence37.HasEvents() | selector12.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node175 _node142 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node175();
            _node142.SetClassNameString("DecoratorLoop");
            _node142.SetId(0xaf);
            sequence37.AddChild(_node142);
            Noop noop3 = new Noop();
            noop3.SetClassNameString("Noop");
            noop3.SetId(0xb0);
            _node142.AddChild(noop3);
            _node142.SetHasEvents(_node142.HasEvents() | noop3.HasEvents());
            sequence37.SetHasEvents(sequence37.HasEvents() | _node142.HasEvents());
            precondition4.SetHasEvents(precondition4.HasEvents() | sequence37.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition4.HasEvents());
            WithPrecondition precondition5 = new WithPrecondition();
            precondition5.SetClassNameString("WithPrecondition");
            precondition5.SetId(450);
            loop.AddChild(precondition5);
            Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node454 _node143 = new Condition_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node454();
            _node143.SetClassNameString("Condition");
            _node143.SetId(0x1c6);
            precondition5.AddChild(_node143);
            precondition5.SetHasEvents(precondition5.HasEvents() | _node143.HasEvents());
            Sequence sequence38 = new Sequence();
            sequence38.SetClassNameString("Sequence");
            sequence38.SetId(0x1c7);
            precondition5.AddChild(sequence38);
            Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node456 _node144 = new Action_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node456();
            _node144.SetClassNameString("Action");
            _node144.SetId(0x1c8);
            sequence38.AddChild(_node144);
            sequence38.SetHasEvents(sequence38.HasEvents() | _node144.HasEvents());
            DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node457 _node145 = new DecoratorLoop_bt_WrapperAI_Monster_BTMonsterRunToInitiative_node457();
            _node145.SetClassNameString("DecoratorLoop");
            _node145.SetId(0x1c9);
            sequence38.AddChild(_node145);
            Noop noop4 = new Noop();
            noop4.SetClassNameString("Noop");
            noop4.SetId(0x1ca);
            _node145.AddChild(noop4);
            _node145.SetHasEvents(_node145.HasEvents() | noop4.HasEvents());
            sequence38.SetHasEvents(sequence38.HasEvents() | _node145.HasEvents());
            precondition5.SetHasEvents(precondition5.HasEvents() | sequence38.HasEvents());
            loop.SetHasEvents(loop.HasEvents() | precondition5.HasEvents());
            _node9.SetHasEvents(_node9.HasEvents() | loop.HasEvents());
            pChild.SetHasEvents(pChild.HasEvents() | _node9.HasEvents());
            bt.SetHasEvents(bt.HasEvents() | pChild.HasEvents());
            return true;
        }
    }
}

